### ISSUE TITLE
Volume attribute always zero and muted always false, no pause/play state

### ISSUE THREAD

**Issue by IanAdd** [ollo69/ha-samsungtv-smart#101]
**Describe the bug**
QA65Q70A TV
Installed and set up with Smartthings
All works as expected, nice long list of exposed attributes show up in Develop Tools / States
Can pause and play a video stream.
Can mute or adjust volume

However:
- the attribute 'muted' always shows false
- the attribute 'volume' always shows 0
- no attribute to be able to read the play/pause state

**Expected behavior**
Described above

**Screenshots**

**Environment details:**
 - HA running on Pi4 using standard os v 5.13
 - Home Assistant version installed: 2021.9.7
 - Component version installed:  0.4.0
 - Last know working version:
 - TV model: QA65Q70A

**Output of HA logs**
N/A

![2021-09-26 11 31 53](https://user-images.githubusercontent.com/10492213/134790252-3df492de-a50e-4b92-a2f7-605eda43f9d2.jpg)
**Additional context**

**Comment by ollo69** [comment]
Do you have external sound device attached to your TV (soundbar or other)? This could cause the issue with volume info.
Related to the play/pause status, as I know there is no way to get this information.

**Comment by IanAdd** [comment]
Aha, you give me an idea. Yes I have an optical link to a Sonos soundbar and surround sound. I can maybe pick up evidence of the pauses from this media_player.
I had an old samsung tv and a chromecast and it was so easy to detect a pause ! New Tv and gone backwards !
