### ISSUE TITLE
Option for logos no available

### ISSUE THREAD

**Issue by pepsonEL** [ollo69/ha-samsungtv-smart#104]
Hi. I Installed latets version component from HACS and connect it with my Tizen Samsung QLED QE65Q64TAU and i dont have available in configuration Integration option whis is describe this: 
[https://github.com/ollo69/ha-samsungtv-smart#configuration-options](https://github.com/ollo69/ha-samsungtv-smart#configuration-options)

Why? I want add to show logos for channel number
![logos_option](https://user-images.githubusercontent.com/71824185/137482565-16587b91-9db2-45db-8a37-06e46a0b1f31.jpg)
.

**Comment by pepsonEL** [comment]
On first page option is only two scroll menu list show also on advanced
option(image screenshot)

pt., 15 paź 2021, 15:43 użytkownik ollo69 ***@***.***>
napisał:

**Comment by ollo69** [comment]
I don't see the screenshot of first page, can you attach here?

**Comment by pepsonEL** [comment]
But what you mean first page?

pt., 15 paź 2021, 17:15 użytkownik ollo69 ***@***.***>
napisał:

**Comment by pepsonEL** [comment]
pt., 15 paź 2021, 20:33 użytkownik Piotr Kuchciak ***@***.***>
napisał:

**Comment by pepsonEL** [comment]
But i dont have this option button....

**Comment by pepsonEL** [comment]
Where is the option button?

pt., 15 paź 2021, 21:38 użytkownik ollo69 ***@***.***>
napisał:

**Comment by pepsonEL** [comment]
Any help please.. .

sob., 16 paź 2021, 19:02 użytkownik Piotr Kuchciak ***@***.***>
napisał:

**Comment by pepsonEL** [comment]
Very very thanks :) works perfect. Thanks.

**Comment by pepsonEL** [comment]
thanks
