### ISSUE TITLE
Status on/off extremely slow to propagate

### ISSUE THREAD

**Issue by gringoireDM** [ollo69/ha-samsungtv-smart#108]
**Describe the bug**
I have a scene setup when the tv is turned on and another one when the tv is turned off. Turning on/off the tv from HA is extremely slow. if I use the remote the status is propagated sometimes even 5 minutes after. 

**Expected behavior**
the on/off status should propagated quickly

**Screenshots**
<img width="404" alt="Screenshot 2021-10-31 at 02 08 51" src="https://user-images.githubusercontent.com/5121938/139561676-a1a946d3-fb5f-4669-a743-5dcb815df8af.png">
<img width="413" alt="Screenshot 2021-10-31 at 02 09 06" src="https://user-images.githubusercontent.com/5121938/139561678-eb2279f3-d498-4fe6-981c-913e13865107.png">

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Home Assistant Bue
 - Home Assistant version installed: Home Assistant OS 6.5
 - Component version installed: 0.4.4
 - Last know working version: NA
 - TV model: Samsung QN95A

**Additional context**
Smartthings is correctly setup. In fact I can use other commands such as app changes, volume up/down etc.

Thanks for your help

**Comment by ollo69** [comment]
Power detection is very complex story, but 5 minutes is very long time. TV is polling by integration every 15 seconds, but probably your TV answer to ping for long time after power off. I think that setting the option "Second to delay power ON status" to 1 will only complicate the status detection, better leave it to default.
Anyway power detection normally take max 30-45 seconds, you should enable debug for integration and investigate your TV behavior on power status change.

**Comment by gringoireDM** [comment]
by looking at the behaviour of the tv, the ping works well for turn on, it's not reliable for turn off. 

I'll explain. as an experiment I sat up a sensor that was using a ping to my tv to detect the on-off state with intervals of 1 second. If I was turning on the tv, the feedback is almost immediate and reliable. very satisfied. for turn off instead the tv was probably talking to smart things every 30 minutes triggering a falso positive.

Putting together these info, would it be possible to to rely on ping and make a request to SmartThings to validate the state just in turn off state which seems to be the problematic one?

Thanks for your help, really appreciate the work you've been doing here.

**Comment by ollo69** [comment]
Normally power status reported by SmartThings is worst than ping and for this reason is not used, but if in your case it is more reliable it is not a problem to add an option to use also this information. But you should enable debug and analyze information that are provided by API to avoid useless work. 
Related to the ping every some minutes, is a know behavior and for this reason exist the 2 option "Use volume status to detect fake power on" and "Delay power in status"...

**Comment by gringoireDM** [comment]
seems like monitoring power consumption to determine on/off status is the most reliable way so far. Samsung indeed does a bad job with integration with SmartThings... which is ridiculous as it is the same made by the same company... anyhow, the workaround I guess fixes the issue. Thank you for your help.

**Comment by ollo69** [comment]
This give to me a good idea to improve power on detection: I could add an option to provide an external `binary sensor` to detect power state. I reopen this issue so that I will refer to this when this implementation will be ready.

**Comment by gringoireDM** [comment]
That would actually be fantastic. Thanks!

**Comment by ollo69** [comment]
Just released a new version that include the new options. Please test and let me know if it help.

**Comment by benjycov** [comment]
This should be a useful update. 

I have been using a SONOFF POW R2 to detect power level usage to give on/off status for the Samsung for sometime, there is no reliable method that I can see to detect the power status from the device itself. Its very frustrating.

**Comment by ollo69** [comment]
> This should be a useful update.

So did you test it?

**Comment by benjycov** [comment]
Unfortunately I can't at the moment as that particular panel is sat on the floor awaiting redeployment. I will once I get in hung in the new room.

**Comment by ollo69** [comment]
> that particular panel is sat on the floor awaiting redeployment

So it should be off 🤣

**Comment by pilot1981** [comment]
Hi, how I can find this new option? binary_sensor?

**Comment by ollo69** [comment]
Configuration -> Show Advanced Options -> Submit.
The combo box at the bottom of the page.

**Comment by pilot1981** [comment]
I tried again and now it worked! There was a bug…

but I have to choose an existing binary_sensor? Which? I can’t create a new binary sensor?!

**Comment by ollo69** [comment]
> I tried again and now it worked! There was a bug…

No bug, may be you have to clean your browser cache. Bug do not fix by themselves.

> but I have to choose an existing binary_sensor? Which? I can’t create a new binary sensor?!

You can create `binary_sensor` using [template platform](https://www.home-assistant.io/integrations/template/). Obviously you need a source to base it.

**Comment by gringoireDM** [comment]
I still didn't receive the smart plug I ordered. Will update this thread with my test results as soon as I receive the hardware to test this with. Thanks for doing the work!!

**Comment by pilot1981** [comment]
> > I tried again and now it worked! There was a bug…
> 
> No bug, may be you have to clean your browser cache. Bug do not fix by themselves.
> 
> > but I have to choose an existing binary_sensor? Which? I can’t create a new binary sensor?!
> 
> You can create `binary_sensor` using [template platform](https://www.home-assistant.io/integrations/template/). Obviously you need a source to base it.

so, if I understood well: I couldn't create a new binar_sensor associated to media_player entity of Samsung TV, but I could create a new binary sensor based on my switch.samsung_tv_power entity?

I reporte below my teamplate configuration of switch.samsung_tv_power:


`  - platform: template
    switches:
        samsung_tv_power:
            value_template: "{{ is_state('media_player.samsung_tv', 'on') }}"
            turn_on:
                service: media_player.turn_on
                target:
                    entity_id: media_player.samsung_tv
            turn_off:
                service: samsungtv_smart.set_art_mode
                target:
                    entity_id: media_player.samsung_tv`

**Comment by ollo69** [comment]
@pilot1981,

I think tat you don't understand the scope of this feature.
You should create a binary sensor using `template` platform based on a sensor that have nothing to with tv integration (for example a sonoff energy sensor that measure the power used by the TV). The binary sensor should report `on` when energy consumption go over some values, because this indicate that the TV is on. So you can select this binary sensor in TV integration, to help the integration to better determinate the on/off status.

**Comment by pilot1981** [comment]
> @pilot1981,
> 
> I think tat you don't understand the scope of this feature. You should create a binary sensor using `template` platform based on a sensor that have nothing to with tv integration (for example a sonoff energy sensor that measure the power used by the TV). The binary sensor should report `on` when energy consumption go over some values, because this indicate that the TV is on. So you can select this binary sensor in TV integration, to help the integration to better determinate the on/off status.

understood only now....thanks!

before, I have to measure energy consumtpion on powered onm state and art mode state...

**Comment by gringoireDM** [comment]
it appears it's not woking. could be because of the new home assistant update. in fact not even other methods to track states are currently working for me.

Let me know what to do to help you getting meaningful informations to debug this

**Comment by ollo69** [comment]
> it appears it's not woking. could be because of the new home assistant update. in fact not even other methods to track states are currently working for me.

Please explain better what do you mean.

**Comment by gringoireDM** [comment]
What I said in my previous comment. The integration is not working anymore. my entity is unresponsive. no status is reported, turn on/off has no effects. I'll try to reinstall it as soon as I have some time.

**Comment by gringoireDM** [comment]
I figured that for some reason the ip of my tv changed. -_- how do I update the ip on the integration? Is there a way, or should I re-configure it from scratch?

**Comment by ollo69** [comment]
IP is used as `uniqueID`, so you need to reconfigure it. I suggest to configure IP reservation in the router to avoid this problems.

**Comment by gringoireDM** [comment]
yeah, I recently changed apartment and I didn't do that yet. :D Completely forgot about it. I'll reconfigure and let you know if the sensor thingy works.

Thanks!

**Comment by mindtripper** [comment]
I've recently integrated a Shelly S switch with power monitoring. This device is very fast at reporting power measurements. From the time I turn on the 65" The Frame 2020 (using remote, this integration, WOL whatever). It takes about 1-2 seconds for the binary template to show "on". This binary sensor is connected to this integration.
![image](https://user-images.githubusercontent.com/26619531/143775956-a590b3f8-67fc-4589-9ce4-48f3cceb9fea.png)
Even though the binary sensor is quick to trigger "on". This integrations media_player.xyz can take everything from a few seconds to 10-40 seconds to indicate that it is on. What is the logic when using "Binary sensor to help detect power status"? And how does it interact with "Seconds to delay power ON status"?
Can I perform any specific tests that can help @ollo69 with this feature?

Note: Turing off the TV, the binary sensor also takes but 2 seconds to turn "off". And this integrations media_player.xyz is also quick to react. 3-4 seconds.

So, using "Binary sensor to help detect power status" doesn't provide the added benefit of detecting "on" status any quicker than not using it. Any idea why?

**Comment by ollo69** [comment]
Binary sensor is used to help detect status, but until the TV do accept the web socket connection it cannot be considered on, because it is not possible to determinate all related TV attributes. But the binary sensor also help to avoid false "on" state, because if the binary sensor do not report "on" the TV is always considered off

**Comment by ollo69** [comment]
I close this issue, no feed-back from 2 months. Open a new one if there are specific problem with status report.
