### ISSUE TITLE
Error - User input malformed

### ISSUE THREAD

**Issue by nelsonamen** [ollo69/ha-samsungtv-smart#110]
**Describe the bug**

**Expected behavior**
If applicable, a clear and concise description of what you expected to happen.

**Screenshots**
![Screenshot_2021-11-01-22-53-45-535_io homeassistant companion android](https://user-images.githubusercontent.com/5807434/139752656-16ab4d94-65bb-420a-b476-e2ddcf6a290b.jpg)

**Environment details:**
 - Environment (HASSIO, Raspbian, etc):
 - Home Assistant version installed:
 - Component version installed:
 - Last know working version:
 - TV model:

**Output of HA logs**
Paste the relavant output of the HA log here.

```

```

**Additional context**

**Comment by ollo69** [comment]
Can you provide more details about HA and integration version as requested by issue template.

**Comment by nelsonamen** [comment]
Fixed in v0.4.6? Thanks 👍
