### ISSUE TITLE
Found yaml configuration for not configured device IP. Please use UI to configure

### ISSUE THREAD

**Issue by leranp** [ollo69/ha-samsungtv-smart#111]
**Describe the bug**
i tried in the past to add the TV with different IP , but now HA give me an error that say:
Found yaml configuration for not configured device 192.168.31.39. Please use UI to configure

tried to delete the integration in HA and from the HAC , didn't see files from this integration on the HA folders
also tried to see in the .storage files if there any device with this IP , but didn't found
**Expected behavior**

**Screenshots**

**Environment details:**
docker , rasbian

**Output of HA logs**

```
2021-11-04 21:14:05 WARNING (MainThread) [custom_components.samsungtv_smart] Found yaml configuration for not configured device 192.168.31.39. Please use UI to configure
```

**Additional context**

**Comment by ollo69** [comment]
I don't see any issue here. You have in `configuration.yaml` integration settings for that ip address that is not configured in HA. Remove the section in `configuration.yaml` and the warning will disappear.

**Comment by leranp** [comment]
My mistake, i forgot that i have configuration of this integration also in the configuration file
