### ISSUE TITLE
TV switching on spontaneously

### ISSUE THREAD

**Issue by dgthomson** [ollo69/ha-samsungtv-smart#112]
**Describe the bug**

My Samsung TV has been powering itself on recently.

<img width="138" alt="Screenshot 2021-11-06 at 08 54 29" src="https://user-images.githubusercontent.com/2021563/140604078-c5351ce9-b0da-4288-8bc9-5d1d968a470a.png">

This is one example today, I was still fast asleep at 6.37 am! I don't have any automations linked to this TV.

The logs show:

`
2021-11-06 06:37:22 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.samsung_series_8 is taking over 10 seconds
`
`
2021-11-06 06:37:58 WARNING (MainThread) [custom_components.samsungtv_smart.media_player] SamsungTV Smart - SmartThings connection is offline. Check connection status on the phone App
`
`
2021-11-06 06:39:00 WARNING (MainThread) [custom_components.samsungtv_smart.media_player] SamsungTV Smart - SmartThings connection now is online
`

TV event log says

`
2021/11/06 6:37: Power-on Reason, WoL
`

Not sure of the exact sequence of events, but in these circumstances a random WoL packet is sent.

**Expected behaviour**

Not to do this.

**Environment details:**

Linux rpi-ws 5.10.63-v7+ #1459 SMP Wed Oct 6 16:41:10 BST 2021 armv7l GNU/Linux (Pi 3B)
Docker version 20.10.9, build c2ea9bc
Home Assistant Container core-2021.11.0
ha-samsungtv-smart v0.4.7
TV: UE43TU8600UXXU running T-NKLDEUC-2014.1 BT-S

**Comment by ollo69** [comment]
Only because there are network connection problem doesn't means that the integration is responsible for this. WOL packet is only sent on request, so I suppose that it come from another source.

**Comment by holdestmade** [comment]
I have had the same issue, mainly at night. If I check the power and network usage, I can see the power goes up to about 40W for a short while and network activity spikes and then it turns on. I assume its to do with updating. I have now set my power plug that my tv is connected to for power monitoring to switch off the TV overnight so it doesn't wake me up.

**Comment by xwsjfx** [comment]
I had the same issue without using this component. It happend when my TV was connected to SmartThings. When I removed from SmartThings the issue disappeared.
I hope this helps, please give a feedback.

**Comment by ollo69** [comment]
Any feed-back here? Can we close this issue that seems not related to integration?

**Comment by Stooovie** [comment]
Same here. I don't remember this ever happening before I started using HA and/or this integration.

**Comment by Stooovie** [comment]
> I had the same issue without using this component. It happend when my TV was connected to SmartThings. When I removed from SmartThings the issue disappeared.
> I hope this helps, please give a feedback.

Won't the functionality tied to Smartthings such as retrieving TV channel/app names stop working?
