### ISSUE TITLE
Switch Audio Output Support

### ISSUE THREAD

**Issue by ArbiterGR** [ollo69/ha-samsungtv-smart#113]
**Describe the solution you'd like**
It would be nice to switch Audio output from internal speakers to external (eg soundbar) directly within the integration. Right now i use key chaining to do so, but it would be nice if there was just a simple toggle.

**Comment by ollo69** [comment]
As I now there is no command for this.

**Comment by ArbiterGR** [comment]
That's a bummer. Thank you for the response though!
