### ISSUE TITLE
Samsung Tizen UE48JS8500 always OFF

### ISSUE THREAD

**Issue by PrzemekSkw** [ollo69/ha-samsungtv-smart#114]
**Describe the bug**
Integgration don't work on Smasung Tizen UE48JS8500. I see my TV but it always off. I cannot turn it on or don't see any other options for that TV. I try also official integration but have the same issue.

**Expected behavior**
Play, pause, stop, tunr off, turn on TV

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Home Assistant installed on Dietpi (Debian Bullseye) on HP-MiniPC, intel, x64.
 - Home Assistant version installed: 
 ## System Health

version | core-2021.11.3
-- | --
installation_type | Unknown
dev | false
hassio | false
docker | false
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.0-9-amd64
arch | x86_64
timezone | Europe/Warsaw

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4786
Installed Version | 1.17.0
Stage | running
Available Repositories | 966
Installed Repositories | 31

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 19
views | 8
mode | storage

</details>
 - Component version installed: v0.4.8
 - Last know working version:?
 - TV model: UE48JS8500

It is supperted model?
Regards.

**Comment by nmsousa76** [comment]
I have the same issue with my TV.  Works for a few days, then it stops working.  If I reload the integration, it works fine for a few minutes, then it goes back to a status off.     I am also using the SamsungTV Tizen hacs integration (which this is a spinoff of) and that works fine.
