### ISSUE TITLE
Sleep timer, can’t turn on after

### ISSUE THREAD

**Issue by djcath** [ollo69/ha-samsungtv-smart#115]
Loving the integration (mainly being able to send the exact volume level via a script)
However I seem to be having an issue where if the TV goes into its auto sleep timer to turn off after no use, I am then unable to turn on or off using the integration.

have a Samsung Q70/75, I’m very new to HA, can you point me in the right direction?

**Comment by ollo69** [comment]
Your TV is connected with WiFi or Cable? What turn-on method are you using (WOL or SmartThings)?

**Comment by djcath** [comment]
TV connected via WiFi, using the WOL method. 
I have 3 scripts, one that turns on the tv with volume set one that turns stereo and tv on and one that turns it off and the stereo off.

after the tv has gone to sleep if the “on” scripts don’t work, if I try the “off” script it will turn the tv on.

**Comment by ollo69** [comment]
WOL packet with WIFI do not work very well, probably because the TV wifi adapter is turned off. With cable connection normally does not have problem.
You can try 2 ways:

1) Try to use the other turn-on method based on SmartThings
2) Increase the number of WOL packet sent to turn on the TV

**Comment by djcath** [comment]
Thanks for getting back to me. 

how does the SmartThings method work?

**Comment by ollo69** [comment]
It use a cloud command sent to SmartThings cloud. Basically is the same method used by SmartThings phone app or by Alexa SmartThings skill. It normally works with WIFI and not work with cable, but I don't know why.
Of course you need to configure SmartThings in integration during setup, and before you need to register your TV on SmartThings phone app

**Comment by djcath** [comment]
Will give it a shot. Thanks for your help!
