### ISSUE TITLE
Multiple TV Support

### ISSUE THREAD

**Issue by moseisleydk** [ollo69/ha-samsungtv-smart#116]
I have several Samsung TVs that I would like in HA.

Config via Lovelave only supports one, and documentation states:

From v0.3.16 initial configuration from yaml is not allowed.
You can still use configuration.yaml to set the additional parameter as explained below.

**Comment by ollo69** [comment]
> Config via Lovelave only supports one

This is not true, you can configure multiple TV via Lovelace.

**Comment by moseisleydk** [comment]
@ollo69 - Via the UI (or in a file)? Fo me "via Lovelace" is the UI under Integrations

**Comment by ollo69** [comment]
Via UI. You can add multiple TV, just they need to have different IP address.

**Comment by ollo69** [comment]
Can we close this? As I said integration allow configure multiple devices, so there nothing to change or implement here.

**Comment by moseisleydk** [comment]
Sure. I assume this in only via configuration.yaml :-)
