### ISSUE TITLE
Icon Logo isues!!!

### ISSUE THREAD

**Issue by kotana** [ollo69/ha-samsungtv-smart#120]
I have the following problem.
Icon logo on Youtube Kids does not exist or is visible.
![2021-12-14 11_14_53-Samsung DeX](https://user-images.githubusercontent.com/760382/145979982-484ec30f-5ad3-4cae-9d99-c1b3f6b976b0.png)

**Comment by ollo69** [comment]
You should follow [this guide](https://github.com/jaruba/ha-samsungtv-tizen/blob/master/Logos.md) for updating the logo database this component is relying on.

**Comment by kotana** [comment]
OK.
The logo is inside, what else do I have to do?
The logo is still not displayed in the media player.
![2021-12-14 17_06_36-youtube — The Movie Database (TMDB)](https://user-images.githubusercontent.com/760382/146035185-affe8d0e-6d34-4719-9256-4673f0d42cc7.png)

**Comment by GrubyRabbit** [comment]
I have problem with netflix and hbo go:
![image](https://user-images.githubusercontent.com/95305101/149349229-dd87bff8-a0f1-475d-9594-2bd63f1f720f.png)

**Comment by antonio1475** [comment]
Yeah the app has the complete package name, and no icon/background in .0.5.0
It's the same in the official integration.

A normal TV channel:
![image](https://user-images.githubusercontent.com/63130724/159179150-6bbb0def-c6fe-433d-93ce-7c4bb3ab2613.png)

Netflix:
![image](https://user-images.githubusercontent.com/63130724/159179074-7d99ce74-a197-4baa-8c4a-8fa1ddc5d760.png)

But in the latest release, 0.6.0, I just saw in the mention in #134 , Netflix is now fine. YouTube too.
![image](https://user-images.githubusercontent.com/63130724/159179506-3703fb31-93b3-4c83-a121-21781791d85b.png)

Thanks @ollo69 !!

Prime Video, Plex, Apple TV,... don't have an icon so I'll try the custom icons mention in 134.
