### ISSUE TITLE
TVs showing as “not loaded”

### ISSUE THREAD

**Issue by jtizzel** [ollo69/ha-samsungtv-smart#124]
My two TVs were working fine with this integration. Since updating the integration today it is now showing as “not loaded” on the intergrations page. 

Message in log shows:

Setup failed for samsungtv_smart: Integration not found.

**Comment by ollo69** [comment]
This is an HACS issue. Upgrade HACS to last release and install integration again, should solve.

**Comment by jtizzel** [comment]
You’re right. It’s ok again now. Many thanks for your quick response, and your work on this. I’ve tried a few Samsung integrations, and this is by far the best, and most reliable.
