### ISSUE TITLE
Wrong ITV logo being used

### ISSUE THREAD

**Issue by holdestmade** [ollo69/ha-samsungtv-smart#125]
**Describe the bug**
The ITV logo used is shown as:

https://www.themoviedb.org/network/997

**Expected behavior**
It should be:

https://www.themoviedb.org/network/9

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HAOS
 - Home Assistant version installed: 2021.12.9
 - Component version installed: 0.4.11
 - Last know working version:
 - TV model: Samsung Q6

**Comment by ollo69** [comment]
Logo is retrieved from a separate database not managed directly from this integration. If you think that logos are wrong use [this guide](https://github.com/jaruba/ha-samsungtv-tizen/blob/master/Logos.md) to update database.
