### ISSUE TITLE
Open Youtube Urls using the Youtube app or cast Youtube urls

### ISSUE THREAD

**Issue by dibyadip-das** [ollo69/ha-samsungtv-smart#127]
**Is your feature request related to a problem? Please describe.**
This is more of a feature extending the current URL cast functionality

**Describe the solution you'd like**
Functionality should be similar to casting of any file
`{
  "entity_id": "media_player.samsungtv",
  "media_content_type": "url",
  "media_content_id": "https://www.youtube.com/watch?v=video_id",
}`
using youtube URL should open the video in the Youtube app

**Describe alternatives you've considered**
It could be a separate media content-type too.
`{
  "entity_id": "media_player.samsungtv",
  "media_content_type": "youtube",
  "media_content_id": "https://www.youtube.com/watch?v=video_id",
}`

**Additional context**
N/A

**Comment by mkny** [comment]
It would be nice to have this!

**Comment by dibyadip-das** [comment]
I think this feature is already a part of [release v0.6.0](https://github.com/ollo69/ha-samsungtv-smart/releases/tag/v0.6.0) @ollo69  Could you please confirm and close?
