### ISSUE TITLE
How to change tv input using Alexa voice commands?

### ISSUE THREAD

**Issue by gamer85** [ollo69/ha-samsungtv-smart#128]
I have successfully installed this from HACS. I was able to enable smart things. I am running HA from a container.  I am using Alexa on a Sonos speaker.  I see in the Alexa app the ability to turn tv on and off, but I don't see other functionality. Do I need a smart things hub in order to change inputs?

I wanted to ask how to change tv input using Alexa voice commands with this hacs add on.  I see from the documentation the below however cannot figure it out. "Change input source to DEVICE-NAME-HERE on SAMSUNG-TV-NAME-HERE (only works if DEVICE-NAME-HERE is a whitelisted word from this page under "Mode Settings").

May I please ask for the steps to get voice command tv input changes working?  My HA is not accessible over SSL so I cannot simply integrate Alexa..  Happy to support this effort if I can use this HA add in to change tv inputs with Alexa voice commands.

**Comment by thierry-rhone** [comment]
It's not possible, alexa support this feature only with devices with embedded alexa.
The only thing you can is create scripts who change source.
