### ISSUE TITLE
Is it possible to scroll TV menus with the mouse wheel? 

### ISSUE THREAD

**Issue by Lepelot** [ollo69/ha-samsungtv-smart#131]
Hello, 

It took me some time, but thanks to you and all the blog participants, this integration is now working and  I can use the various features and controls that I need via Lovelace. Naturally all this could be improved , but it is working. Again, big thank you

The one thing I would like to do now is to scroll up and down using the mouse wheel,  but I don't even know it it is possible. 

Can someone help me with this?

**Comment by ollo69** [comment]
> The one thing I would like to do now is to scroll up and down using the mouse wheel

Not understanding what you are asking for.

**Comment by Lepelot** [comment]
![lovelace](https://user-images.githubusercontent.com/76974827/154809785-96aab07d-211f-4ac5-9548-8d7345dbe819.gif)
Thanks for your reply. 
Now that I have a lovelace control panel like this picture, I was wondering if there is a way to use the mouse wheel instead of clicking multiple times on the up or down arrows.

**Comment by ollo69** [comment]
Interaction with UI and lovelace have nothing to do with integrations that represent the "backgroud" part that manage communication with devices. To found helps to your question you should use the community forum.
Can we close this issue? Seems that there is nothing to fix or feature to add here.

**Comment by Lepelot** [comment]
Yes, no problem, thanks for your help. I'll continue digging. Other people are trying to do something similar by holding the button down : https://community.home-assistant.io/t/hold-action-keep-firing-until-i-let-go/311156

**Comment by ollo69** [comment]
[Hold a key](https://github.com/ollo69/ha-samsungtv-smart#hold-keys) is supported by integration, but how you manage this inside UI is another story.
I close this issue.
