### ISSUE TITLE
Allow users to use custom local logos form channels/apps

### ISSUE THREAD

**Issue by kauelima** [ollo69/ha-samsungtv-smart#134]
As a user that primarily watches local channels on TV I would like to assign custom local logos for some channels. I've already tried to download a new batch using Jaruba's logo-channel (https://github.com/jaruba/channel-logos) but despite having success in downloading the logos, I found out that changing logo_paths.json on the custom component does nothing since it's linked to the live version on github.

I'll try to modify my version (as best as I can since i'm a designer with little knowledge in development) to fetch from the local logo_paths.json but I think it would be great to check. A local file to override/fetch logos as this will give users a better control.

Thanks for the great work @ollo69

**Comment by ollo69** [comment]
Local logo is implemented with last release. You can create local logo and copy them in the `remote` subfolder (see readme options section for more details). Please try the feature and let me know if we can close this FR.

**Comment by antonio1475** [comment]
Hi @ollo69,

Thank you. Can you clarify how this is supposed to work? In here you mention the `remote` folder, but ReadMe says 

I did some testing with Netflix (org.tizen.netflix-app):
- netflix.png (original): works
- org.tizen.netflix-app.png : doesn't work
- orgtizennetflixapp.png : doesn't work
- netflix-app.png: doesn't work
- netflixapp.png: doesn't work

For Prime Video (org.tizen.primevideo):
- primevideo.png (original): doesn't work
- orgtizenprimevideo.png: works

For YouTube (9Ur5IzDKqV.TizenYouTube):
- youtube.png (original): works
- other name variations don't work

But for Plex (kIciSQlYEM.plex), uploading a new (400x400px, png) image to the static folder with the rest:
- kIciSQlYEM.plex.png: doesn't work
- kIciSQlYEMplex.png: doesn't work
- plex.png: doesn't work

Can you clarify the folder and the name logic?

Thank you!!

**Comment by ollo69** [comment]
Name `remote` is my mistake, don't know why I wrote this. Right folder name is `static`.
Going to fix case sensitive search, lowercase file name requirement and other little issue on next release.

**Comment by kauelima** [comment]
Awesome! Thanks a lot, my TV is currently out of service, but I'll test as soon as it's back on the job. It works for apps and channels, right? For an example, if I have a channel here called "Channel Television" I'll upload an image named "channeltelevision.png" for it to be replaced, right?

**Comment by ollo69** [comment]
Yes, that's the logic

**Comment by kauelima** [comment]
I did not test this yet but as I see more people did and it seem to work. I'm closing the issue since I don't know for how long I'll be battling Samsung support with my broken TV.

Thanks @ollo69 for the great feature :)
