### ISSUE TITLE
Can SmartThings API work without internet?

### ISSUE THREAD

**Issue by Bagunda** [ollo69/ha-samsungtv-smart#136]
TV: UE40NU7100U

HDMI1, HDMI2 and HDMI3 can only be enabled via the SmartThings API.

Can SmartThings API work offline?
How to switch between HMDI without internet?

**Comment by ollo69** [comment]
SmartThings is the Samsung Cloud platform, so cannot work off-line by definition.
I have no idea on how to switch `source` without SmartThings, this is one of the main reason for which it was introduced in this and other integration.

This is an issue session, for q&a please use others tools like the HA community forum.👍
I close this issue, nothing to fix here
