### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by sczaps** [ollo69/ha-samsungtv-smart#137]
Hello.
I have problem with connection. 
In configuration i write ip, name and generated token. Then in pop up i click allow. In next window i write device ID (di from site) and click allow again on  pop up. After typing and clicking allow, the same window appears. the situation repeats itself over and over again. 

Below I am pasting information from "http://device-id:8001/api/v2/"

{"device":{"FrameTVSupport":"false","GamePadSupport":"true","ImeSyncedSupport":"true","OS":"Tizen","TokenAuthSupport":"true","VoiceSupport":"true","countryCode":"PL","description":"Samsung DTV RCR","developerIP":"0.0.0.0","developerMode":"0","duid":"uuid:62c4e1f4-61d8-4c60-b94c-39d95a89694a","firmwareVersion":"Unknown","id":"uuid:62c4e1f4-61d8-4c60-b94c-39d95a89694a","ip":"192.168.50.129","model":"17_KANTM_UHD","modelName":"UE55MU7052","name":"[TV] Samsung 7 Series (55)","networkType":"none","resolution":"3840x2160","smartHubAgreement":"true","type":"Samsung SmartTV","udn":"uuid:62c4e1f4-61d8-4c60-b94c-39d95a89694a","wifiMac":"none"},"id":"uuid:62c4e1f4-61d8-4c60-b94c-39d95a89694a","isSupport":"{\"DMP_DRM_PLAYREADY\":\"false\",\"DMP_DRM_WIDEVINE\":\"false\",\"DMP_available\":\"true\",\"EDEN_available\":\"true\",\"FrameTVSupport\":\"false\",\"ImeSyncedSupport\":\"true\",\"TokenAuthSupport\":\"true\",\"remote_available\":\"true\",\"remote_fourDirections\":\"true\",\"remote_touchPad\":\"true\",\"remote_voiceControl\":\"true\"}\n","name":"[TV] Samsung 7 Series (55)","remote":"1.0","type":"Samsung SmartTV","uri":"http://192.168.50.129:8001/api/v2/","version":"2.0.25"}

Could there be anything else I could do?

**Comment by ollo69** [comment]
You need to change settings on your TV to ask authorization for external device "only first time"!

**Comment by sczaps** [comment]
of course I have it set up.

**Comment by ollo69** [comment]
Did you try to `cold boot` your TV. If nothing solve, enable debug add attach here HA log file.
