### ISSUE TITLE
No option for Smart Things token

### ISSUE THREAD

**Issue by iFe1d** [ollo69/ha-samsungtv-smart#139]
Everything works for connecting the integration to my TV but there is no place for pasting the Smart Things token when integrating...  Only Host and Name
![Samsung](https://user-images.githubusercontent.com/95878947/156902344-5960a46b-c054-438a-b26f-5ae27f1ce40f.png)

EDIT:

I am on the latest version of everything running home assistant off an ODROID-N2+ (home assistant blue)

**Comment by ollo69** [comment]
This image is related to the setup of default HA integration. The name of this integration is `SamsungTV Smart`. Select the right integration during setup and you will sii the option to insert SmartThing token.
