### ISSUE TITLE
state looses sync after turning TV OFF via IR / HDMI CEC (turn on slow to detect also)

### ISSUE THREAD

**Issue by DER31K** [ollo69/ha-samsungtv-smart#14]
version 0.2.1
tv model: UN58NU7100
tv connected to LAN via wifi
smartthings api setup: YES.

When turning on TV via IR remote or HDMI CEC (kodi running on rpi4 connected to TV - wake from screensaver typically when pressing a button) the integration is very slow to react and show state change, typically about a minute or two - is this normal (something like a ping/pull delay)? if so - that is OK.

The more concerning issue is that when TV is turned off via HDMI CEC or by IR the integration seems to will lose sync with the actual TV..... and the TV state will show "on" in HA, but its actually off.

I have tried turning the TV off via HDMI CEC or IR remote and waiting a few minutes but the status never changes - then if i control the TV through HA to turn it "off" even though it's already off, the now TV turns on but the act of turning off in HA now means the integration believes TV is off....

anyone else see this issue?
FYI, My main goal with this integration is not so much to  CONTROL the TV from HA - I have HDMI CEC and my own remotes to control the TV.... my goal is to get an accurate STATE of whether the TV is actually on or off, but so far it is not reliable and looking to see if anyone has advice.

Thanks.

**Comment by Mathmxp** [comment]
version 0.2.1
tv model: QE49Q60RATXZT
tv connected to LAN via wifi
smartthings api setup: NO

Exact same behaviour as yours

**Comment by ollo69** [comment]
I have to review ping method, seems that in some case do not work. I will work on this next w.e.
Can you try using version v0,1.8 and let me know if this works?

**Comment by DER31K** [comment]
I'm noticing a different issue with 0.1.8... TV turned off manually via
hdmi-cec or IR. Then integration state turns to off after 10 to 15 seconds
- as expected..... But then about a minute later it's showing my TV as on,
yet TV is still off.  Then another few minutes go by and TV is showing as
off.

Not sure why 0.1.8 is doing a random inaccurate "on" state change shortly
after it learns and states TV had been turned off.

Hopefully this behavior doesn't carry over into pending 0.2 ping fix.

**Comment by ollo69** [comment]
This should be fixed from a lot
Pls reopen or create a new one if you still have issue
