### ISSUE TITLE
Add Sound Output selectable option ? (not to be confused with Sound Mode)

### ISSUE THREAD

**Issue by pascalkrielen** [ollo69/ha-samsungtv-smart#142]
**Is your feature request related to a problem? Please describe.**
Not a problem, but request for additional functionality 

**Describe the solution you'd like**
The TV has options for the sound output, like "speakers", "Soundbar", "Speakers+Soundbar".
I would like to be able to select those.

**Describe alternatives you've considered**
No alternative tried, other that selecting it on the TV itself.

**Additional context**
The options to select "Sound Mode (list)" and "Picture Mode (list)" seem similar to my request.

**Comment by ollo69** [comment]
I don't think that exist a direct method to do this. Also using TV remote you normally have to navigate through menu to change sound output.
