### ISSUE TITLE
Move Local logos in www Folder to not lose them when updating

### ISSUE THREAD

**Issue by holdestmade** [ollo69/ha-samsungtv-smart#146]
**Describe the bug**
I did some custom local logos in Static folder and they were lost when updating

**Expected behavior**
Logos to remain after updating

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Home Assistant OS
 - Home Assistant version installed: 2022.3.5
 - Component version installed: 0.6.1
 - Last know working version:
 - TV model: QE65Q7FNA 

**Output of HA logs**

```

```

**Additional context**

**Comment by ollo69** [comment]
Upgrade is not managed by integration, there is nothing that I can do. I will eventually add a warning in Readme.

**Comment by holdestmade** [comment]
Might be worth using another folder, say in www to store the logos ?

**Comment by ollo69** [comment]
This should be available with last release. Please check and let me know if everything is ok.

**Comment by holdestmade** [comment]
Works great, many thanks
