### ISSUE TITLE
How to add channel_list: (json)(Optional)

### ISSUE THREAD

**Issue by Dirdan** [ollo69/ha-samsungtv-smart#147]
First of all thanks for your integration and for updates.

My question is how can i add some favourite channel to source list or wherever? I don't understand how can get it.

Thanks for you support.

Best regards

**Comment by ollo69** [comment]
This is explained [here](https://github.com/ollo69/ha-samsungtv-smart#custom-configuration-parameters) in readme

**Comment by Dirdan** [comment]
Very thanks ollo69, I managed to add my favorite channel list with the following code:

samsungtv_smart:
  - host: <YOUR TV IP ADDRES>
     channel_list: '{"MTV": "14", "Eurosport": "20", "TLC": "21"}'

It's correct that channel are showed in source list, together my apps?
Or there is the possibility to separate them from this last ones?

**Comment by ollo69** [comment]
Media player entity do not provide a separate options to select channels, so they will be inside source list, is the only options.
Close this issue.
