### ISSUE TITLE
Error while enabling integration

### ISSUE THREAD

**Issue by DjBac** [ollo69/ha-samsungtv-smart#149]
I am on the latest HASS version (Raspberry) and after installing the component through HACS, and trying to enable the custom integration I get the following error:

"This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant."

**Comment by ollo69** [comment]
Probably you have some conflict with dependencies due to some others custom integration. Please check for errors in the log.
