### ISSUE TITLE
Integration causing networking on TV to stop

### ISSUE THREAD

**Issue by salty2011** [ollo69/ha-samsungtv-smart#150]
**Describe the bug**
When the integration is enabled after several hours the tv begin to report it is unable to connect to the network. Even after trying to manually reconnect. Issue is only resolved by performing a cold reboot. Disabling the integration stops the issue from occuring

For power on functionality I am using the suggested smart things instead of WOL as it is wireless.

**Expected behavior**
Integration should not cause network stack of TV to stop working

**Screenshots**

**Environment details:**
 - Environment: HASS Supervised
 - Home Assistant version installed: 2022.3.7
 - Component version installed: .6.1
 - Last know working version: unknown
 - TV model: Samsung Q80 - QA75Q80TAWXXY

**Comment by ollo69** [comment]
Please attach diagnostic file generated when TV is on

**Comment by salty2011** [comment]
Hello, please find attached the diagnostic file
[config_entry-samsungtv_smart-0f9f275bb81d43d9bfcebe0ac703392a.json.txt](https://github.com/ollo69/ha-samsungtv-smart/files/8370235/config_entry-samsungtv_smart-0f9f275bb81d43d9bfcebe0ac703392a.json.txt)
