### ISSUE TITLE
NU8000 TV randomly turns on

### ISSUE THREAD

**Issue by Stooovie** [ollo69/ha-samsungtv-smart#155]
**Describe the bug**
NU8000 TV randomly turns on.

**Expected behavior**
TV stays turned off until I turn it on.

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HAOS
 - Home Assistant version installed:  2022.4.2
 - Component version installed: 0.6.2
 - Last know working version:
 - TV model: Samsung NU8000

**Output of HA logs**
I don´t see anything relevant in the log.

**Device diagnostics**

[config_entry-samsungtv_smart-346a278a84f8b0586679f4d9322af501.json.txt](https://github.com/ollo69/ha-samsungtv-smart/files/8472952/config_entry-samsungtv_smart-346a278a84f8b0586679f4d9322af501.json.txt)

**Additional context**
Wired connection, Smartthings token is used to enable getting HDMI input names.
Started happening about a month or two ago. I have been using this integration for more than two years witout many issues. 

How can I debug this further?

**Comment by Drealine** [comment]
Same issue like me : https://github.com/ollo69/ha-samsungtv-smart/issues/156
