### ISSUE TITLE
TV won't start after severals secondes via WIFI

### ISSUE THREAD

**Issue by Drealine** [ollo69/ha-samsungtv-smart#156]
**Describe the bug**
My TV won't start after serverals seconds when I poweroff TV. I've to poweron TV manually then I can control poweroff.

**Expected behavior**
If applicable, a clear and concise description of what you expected to happen.

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Intel NUC
 - Home Assistant version installed: 2022.3.7
 - Component version installed: v0.6.2
 - Last know working version: Not working since installed
 - TV model: UE43NU7025

**Output of HA logs**
Paste the relavant output of the HA log here.

```
2022-04-13 13:25:46 DEBUG (SyncWorker_2) [custom_components.samsungtv_smart.api.samsungws] Sending key KEY_POWER
2022-04-13 13:25:46 DEBUG (SyncWorker_2) [custom_components.samsungtv_smart.api.samsungws] WS url wss://192.168.10.212:8002/api/v2/channels/samsung.remote.control?name=W0hvbWUgQXNzaXN0YW50XSBUVi1TYWxvbg%3D%3D&token=14447318
2022-04-13 13:25:53 DEBUG (SyncWorker_2) [custom_components.samsungtv_smart.media_player] Error in send_command() -> OSError
```

**Additional context**
My TV is connected via WIFI.

**Comment by ZeroOmar** [comment]
I face a similar issue. but sadly that is an issue from the TV side.

I have 2 TVs one connected with ethernet and the other with WIFI
The WIFI one always faces issues and doesn't respond to power on and after powering on with the remote it doesn't appear ON on HASS even Samsung SmartThings and also it doesn't reply to ping but from the TV OS it says its connected fine to the internet.
It works randomly sometimes its fine and sometimes it just doesn't work.
sometimes the power on command arrives very late.

but I cant blame the plugin for that if the TV is not reachable on the network.
if possible connect it with an ethernet cable. it will work flawlessly.
