### ISSUE TITLE
After restarting HA, no art_mode_status unless "Allow" is pushed on the TV

### ISSUE THREAD

**Issue by mbrennan** [ollo69/ha-samsungtv-smart#157]
**Describe the bug**
After restarting Home Assistant, the TV always requests permission to allow the integration access to the TV.  A box pops up on the TV requesting access to it.  If you don't push "Allow," then the "art_mode_status" attribute of the TV state is not available. 
 Given how frequent Home Assistant restarts occur, it's nearly impossible to keep up with this by pushing the "Allow" button on the TV.

**Expected behavior**
The TV should only ask permission once, not upon every restart of Home Assistant.  The "art_mode_status" should be available after restarting Home Assistant without allowing permission every time from the TV.

**Comment by ollo69** [comment]
Is the configuration in the TV for external device set to "ask only once"?

**Comment by mbrennan** [comment]
It’s set to “Never”

**Comment by ollo69** [comment]
Must be set to "only first time" or the TV will not provide the token for next access

**Comment by mbrennan** [comment]
I put it on first time only and it still asks for permission on every reboot. It also asks for permission when trying to go into art mode.

**Comment by ollo69** [comment]
This is strange, never see this behavior. Please attach diagnostics file.

**Comment by mbrennan** [comment]
After tinkering for a bit, I found the problem was that I had the TV added through the standard HA Samsung TV integration as well as this one.  After I removed that integration this problem went away.
