### ISSUE TITLE
The Frame TV reports state as 'off' when it is on

### ISSUE THREAD

**Issue by mbrennan** [ollo69/ha-samsungtv-smart#158]
**Describe the bug**
I use an automation in Node Red to turn my Frame TV to art mode when the state is 'off' and the 'art_mode_status' is 'off'.  However, sometimes, the TV will change its state to 'off' when it is still turned on.  The automation in Node Red runs and turns the TV to art mode while we're watching TV.

**Expected behavior**
The TV shouldn't report a state of 'off' if it's on.

**Screenshots**

**Environment details:**
 - Environment:
 Bare Metal Raspberry Pi 3, HASSIO

 - Home Assistant version installed:
core-2022.4.5
supervisor-2022.04.0
Home Assistant OS 7.6

 - Component version installed:
 - v0.6.3

 - TV model:
Samsung "The Frame" 75 (2019)

**Additional context**
We usually only ever watch content from a separate AppleTV plugged into one of the HDMI ports.  My wife was watching something while the state from the device switched to 'off'.

**Comment by idoaflalo** [comment]
I fixed this problem in #154.
Hope the developer will approve it soon.

**Comment by mbrennan** [comment]
It looks like #154 is completely different - it addresses whether to set the TV to "art mode" when the power is turned off or not.  The issue I've reported is different:  the TV's state reports "off" intermittently while it's actually in the "on" state (while I'm watching the TV).

**Comment by idoaflalo** [comment]
> It looks like #154 is completely different - it addresses whether to set the TV to "art mode" when the power is turned off or not. The issue I've reported is different: the TV's state reports "off" intermittently while I'm watching the TV.

This feature will solve the "patch" of using an automation to detect when the tv is off and just then going to art mode. Instead of, it will go to art mode immediately when turning the tv off.
Moreover, check if disabling the feature "Use volume mute status to detect fake power ON" solves your problem.
It may be a network problem because the integration uses a ping mechanism to decide if the tv is on or not.

**Comment by ripburger** [comment]
I use a TP-LINK energy consumption meter to know for sure whether the TV is on or off, works like a charm!

**Comment by skynet01** [comment]
> Moreover, check if disabling the feature "Use volume mute status to detect fake power ON" solves your problem.
This solved it for me :)
