### ISSUE TITLE
My TV keeps asking me to authorize

### ISSUE THREAD

**Issue by thisisbenwoo** [ollo69/ha-samsungtv-smart#16]
I love your integration. It works beautifully. However, every time I turn the TV on it asks me to authorize. Is that something to do with the integration, or a TV thing please? I have a UN55MU7100.

**Comment by ollo69** [comment]
Is the TV set to ask for authorization only the first time?
Is the token file created in the integration directory?

**Comment by thisisbenwoo** [comment]
OK, put me down for being a dimwit! I never knew that the TV could just ask for auth for the first time only! Fixed! Thanks for the quick reply!

**Comment by Leon99** [comment]
I'm having the same problem with my Q80. Where do I change that auth setting? Just went through the whole menu with no luck.

**Comment by ollo69** [comment]
Don't know if all TV have same options, for me is:

menu->settings->general->External device->Manage Device Connection->Access Notification (set to only first time)

I translate form italian so maybe is not exactly this the name...

**Comment by Leon99** [comment]
Strange, that setting was actually set to never ask for access confirmation (always allow), which didn't seem to have an effect, but setting it to ask first time only solved the issue. Thanks!

**Comment by ollo69** [comment]
Yes, you must set "ask first time" or the TV will not generate access token and wss connection will not work properly.
