### ISSUE TITLE
Remote Control Button Pressed

### ISSUE THREAD

**Issue by ripburger** [ollo69/ha-samsungtv-smart#163]
I have a 2021 Samsung The Frame, a Philips hue Syncbox, a Bose Soundbar, and a Google Chromecast with Google TV. Even though CEC should turn everything on and off when one of the devices switches on/off, this isnt working properly.

With some automations in Home Assistant, I have a better working solution though it doesnt work flawlessly. It works based upon assumptions (eg when the Chromecast switches on HA switches on everything else). But sometimes you get a false positive, and everything switches on while it shouldnt.

This would be solved if this integration could register actual buttons on the remote being pressed. Is this possible? For example, I press the power button on the remote and this is then registered by HA. This way, I know for sure whether the automations should run because I have actually pressed the power button.

Thanks!

**Comment by heyjared** [comment]
I'd also be interested to know if events can be emitted when the volume buttons are pressed.

**Comment by drewancil** [comment]
> tomations in Home Assistant, I have a better working solution though it doesnt work flawlessly. It works based upon assumptions (eg when the Chromecast switches on HA switches on everything else). But sometimes you get a false positive, and everything switches on while it shouldnt.
> 
> This would be solved if this integration could register actual buttons on the remote being pressed. Is this possible? For example, I press the power button on the remote and this is then registered by HA. This way, I know for sure whether the automations should run because I have actually pressed the power button.

I haven't dealt with the exact issue you described, but you could potentially use an IR receiver/emitter to receive/automate the remote presses.  I'm using 4 broadlink IR/RF emitters and the Broadlink HA Integration around my house to automate things such as a power amplifier, my bed (raise head/foot/massage), some other random AV equipment, and even my Toto toilet ;). They are inexpensive and work well after you understand how they work.
