### ISSUE TITLE
TV changed from wired to wireless - how to update?

### ISSUE THREAD

**Issue by JeffSteinbok** [ollo69/ha-samsungtv-smart#164]
**Describe the bug**
My TV got changed to be on wired Internet. SmartThings sees it correctly but the HA integration seems to be pretty fixated on using the old IP address. 

**Expected behavior**
Would like to be able to update IP/MAC without having to create a new device. 

**Additional context**

**Comment by ollo69** [comment]
If you reconfigure integration setup should be aborted and IP/MAC updated for existing entry based on unique id.

**Comment by soyxan** [comment]
Please can you give more details on how to do it? The IP address of my TV changed and I want to force the integration to reuse it. Thanks!
