### ISSUE TITLE
Tizen TV Always off after HA reboot

### ISSUE THREAD

**Issue by FilippoS1973** [ollo69/ha-samsungtv-smart#167]
**Describe the bug**
Samsung TV is Always off

**Environment details:**
HA 2022.5.5
TV Model: QE75Q7FNA ([TV] Samsung Q7 Series (75))

**Output of HA logs**
Paste the relavant output of the HA log here.

Logger: websocket
Source: /usr/local/lib/python3.9/site-packages/websocket/_logging.py:61
First occurred: 20:52:43 (3 occurrences)
Last logged: 20:52:55

error from callback <bound method SamsungTVWS._on_message_remote of <custom_components.samsungtv_smart.api.samsungws.SamsungTVWS object at 0x672b7f88>>: _on_message_remote() missing 1 required positional argument: 'message'
error from callback <bound method SamsungTVWS._on_ping_remote of <custom_components.samsungtv_smart.api.samsungws.SamsungTVWS object at 0x672b7f88>>: _on_ping_remote() missing 1 required positional argument: 'payload'

**Additional context**

**Comment by ollo69** [comment]
You have installed a custom integration that is forcing an old version of `websocket-client` library. Check your integrations and remove the one that is causing the issue.

**Comment by FilippoS1973** [comment]
You are right. 
now it works!
thank you

**Comment by FilippoS1973** [comment]
I still have installed https://github.com/jaruba/ha-samsungtv-tizen
