### ISSUE TITLE
Custom logo for channels with ":" character

### ISSUE THREAD

**Issue by webjib** [ollo69/ha-samsungtv-smart#168]
**Describe the bug**
In France, we've got a TV channel that use a ":" character in its name: "franceinfo:". I've tried to place a custom logo for this channel in the www/samsungtv_smart_logos folder, but the ":" is not allowed in a filename. Thus, it's not working, the integration can't use the logo (the best filename I can set is "franceinfo.png"). Could you adapt the code to support this special character when the media_title contains a ":" character?

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Raspberry Pi 4
 - Home Assistant version installed: 2022.06
 - Component version installed: lastest
 - TV model: Samsung Q7N55 (2018)

**Comment by ollo69** [comment]
This is fixed with last release, just create local logo file without ":" character.
