### ISSUE TITLE
Entity not reflecting ON state

### ISSUE THREAD

**Issue by jagjordi** [ollo69/ha-samsungtv-smart#179]
**Describe the bug**
Entyty reported as off but the TV is on. I can turn on the tv from HA but the entity state never switches to on. Then I cannot turn it off from home assistant.

**Expected behavior**
State should switch to ON when TV is ON

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HASSIO
 - Home Assistant version installed: 
```
Home Assistant 2022.8.7
Supervisor 2022.08.5
Operating System 8.5
Frontend 20220802.0 - latest
```
 - Component version installed: `
 - Last know working version: latest one (not sure where to see the number)
 - TV model: NeoQLED QN90B 50"

**Output of HA logs**
No error/warning seen in logs

**Additional context**
It started happening around 2/3 weeks ago

**Comment by gyanez91** [comment]
Same here , the log shows a warning
This error originated from a custom integration.

Logger: websocket
Source: custom_components/samsungtv_smart/api/samsungws.py:592
Integration: SamsungTV Smart (documentation, issues)
First occurred: September 2, 2022 at 10:30:42 AM (22 occurrences)
Last logged: 3:56:18 PM

websocket connected

If i reload the integración the state update fine for a time and then happen again showing off

**Comment by jagjordi** [comment]
> Please provide logs
What logs do you need exactly? As I said in OP there is no log entry from Samsung integration (I filter with "samsung" and nothing comes)

**Comment by jagjordi** [comment]
I have searched again and I found this entry
`Logger: pychromecast.socket_client
Source: /usr/local/lib/python3.10/site-packages/pychromecast/socket_client.py:663
First occurred: September 3, 2022, 6:07:28 PM (1 occurrences)
Last logged: September 3, 2022, 6:07:28 PM

[Kitchen TV(192.168.1.234):8009] Error communicating with socket, resetting connection `

**Comment by jagjordi** [comment]
I suspect that the on functionality works because I use WOL instead of smartthings for the turn on functionality, but I could be wrong.

**Comment by ollo69** [comment]
Was the integration working in the past? In any case try updating to last release [v0.7.6](https://github.com/ollo69/ha-samsungtv-smart/releases/tag/v0.7.6) and let me know if this fix the issue.

**Comment by ollo69** [comment]
Any updates here?

**Comment by nattgris** [comment]
The reported behaviour matches what I see with v0.7.7; TV (QE65Q7FNA) can be turned ON from the integration but still the integration shows OFF and nothing else can be done.

I don't regularly control the TV from HA, mostly because it's never really worked that reliably. I'm mostly interested in being able to turn the TV off and I'm sure that has worked at some point.

**Comment by Calzor-Suzay** [comment]
Same issue here as well with HA not reporting status of TV as ON so kind of locks you out of using it.

I'm a new user this addon so took me a while.
I can power it on/off (Toggle) via the HA button and TV responds.
I have mine set to port 8080 as from a port scan I had 8000, 8080 or 9999, all from a port query show as closed when TV is off and open when on (with a short delay to respond and shutdown upon TV status change.

Like others though if I turn the TV on via HA or via the remote the status doesn't update in HA to on and allow me to use it.
If you then reload the addon it works out the status and you can use it till it powers off (which is acknowledges) but on power back on HA won't update till a reload occurs.

**Comment by chupacabra71** [comment]
Same issue here, running: 
 Home Assistant 2022.10.5 
 Supervisor 2022.10.0 
 Operating System 9.3 
 Frontend 20221010.0 - latest 

I can confirm it was working in the past as i have it tied into some TV back lights that used to come on when the TV was turned on.  Now the TV status never shows on.

**Comment by jagjordi** [comment]
> Was the integration working in the past? In any case try updating to last release [v0.7.6](https://github.com/ollo69/ha-samsungtv-smart/releases/tag/v0.7.6) and let me know if this fix the issue.

Can confirm it's working again after downgrading to v0.7.6.

Sorry for taking so long!

**Comment by Calzor-Suzay** [comment]
How do you downgrade it?
Do you have to remove it totally and again from scratch?

**Comment by ollo69** [comment]
> Can confirm it's working again after downgrading to v0.7.6.

So any version above 0.7.6 are not working for you?


> How do you downgrade it?

If you have HACS you can select a specific version to install

**Comment by Calzor-Suzay** [comment]
I have HACS but can't work out how to downgrade so like I said assuming I have to remove the current one then install as 0.7.6.

**Comment by jagjordi** [comment]
This way @Calzor-Suzay 
![image](https://user-images.githubusercontent.com/14058667/200841343-d3100e6f-ddb7-4758-92dc-17f472df9634.png)
![image](https://user-images.githubusercontent.com/14058667/200841371-141c2955-266b-437c-827d-9c6cedd003a8.png)

**Comment by Calzor-Suzay** [comment]
Ok I did this choosing 0.7.6, it ran through the motions, re started HA and it still doesn't work.
Have to reload the configuration and then it works out the TV is on.
How do I know it's running version 0.7.6 though? In HACS when I browse to it, it still says 0.8.0 top left like in your screenshot.
Not sure if that's the version running or just the latest details available.

**Comment by Calzor-Suzay** [comment]
I totally removed the plugin, installed from fresh as 0.7.6 along with smartthings tokens etc.
Still the same, doesn't see the TV being turned on unless you reload the integration.

**Comment by jawn22** [comment]
I'm facing a similar issue where turning the TV on via the remote - it takes around 20 seconds for HA to change state to ON. If I turn the TV on via the HA Integration, it does turn on and reflect status as ON within 2-3 seconds. I've tried adjusting the advanced settings but that didn't seem to speed up the delay - has anyone found a way to tweak this to improve the detection speed?

**Comment by Saponelli** [comment]
> Same issue here as well with HA not reporting status of TV as ON so kind of locks you out of using it.
> 
> I'm a new user this addon so took me a while. I can power it on/off (Toggle) via the HA button and TV responds. I have mine set to port 8080 as from a port scan I had 8000, 8080 or 9999, all from a port query show as closed when TV is off and open when on (with a short delay to respond and shutdown upon TV status change.
> 
> Like others though if I turn the TV on via HA or via the remote the status doesn't update in HA to on and allow me to use it. If you then reload the addon it works out the status and you can use it till it powers off (which is acknowledges) but on power back on HA won't update till a reload occurs.

Hi everyone. I have the same problem. After some time the ignition status goes OFF with TV on and I have to restart the component. From the log I see this...
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.samsungtv_smart.media_player
Source: custom_components/samsungtv_smart/media_player.py:868
Integration: SamsungTV Smart (documentation, issues)
First occurred: 12:58:45 (2 occurrences)
Last logged: 12:59:08

media_player.tv_salone - Error refreshing from SmartThings. Check connection status with TV on the phone App
media_player.tv_salone - Connection to SmartThings restored

I tried to map the tv ports off and they are... 
8001/tcp   open vcom-tunnel
8002/tcp   open teradataordbms
8080/tcp   open http-proxy
9999/tcp   open abyss
12345/tcp open netbus

i tried 8001, 8002 and 8080 but it doesn't change. Advice???

**Comment by ollo69** [comment]
Did you try to put 0 in the port (that means use ping)

**Comment by Saponelli** [comment]
I just tried. But it doesn't change, it worked for a short time and then it was OFF again. I can still change the channel and volume (I created a remote control) but it always turns off

**Comment by Calzor-Suzay** [comment]
Think I might have fixed my issue, need to do some more testing but it seems to detect it on (Not instant but works in say 10 seconds) and and power off (which always seemed to work anyway after a few seconds).

For me it was turning off this option "Use volume mute status to detect fake power ON".
My TV isn't 'muted' as such but is linked via ARC to an external AV Amp that handles all the picture/sound so the 'sound' isn't controllable via the TV per se so perhaps it thinks its muted.

Like I say I'll do some more testing but looks to be working.

**Comment by ollo69** [comment]
@Calzor-Suzay,

good catch. I should probably set this options disabled by default because could create issue in that condition.

**Comment by jawn22** [comment]
I tried changing the mute advanced setting and it’s still taking around 10-20 seconds to detect the TV status when I use the physical remote to turn on/off the TV. Feels like a polling interval thing. Checked through the documentation for this integration but there doesn’t seem to be a way to adjust the polling interval?? 

For reference I have the wait time for status on set to 0 too.

Any other thoughts?

**Comment by ollo69** [comment]
10-20 seconds delay is not the point of this issue (Entity not reflecting ON state). Because refresh is based on polling, it is normal have this kind of delay, and action like set polling to 1 second or similar will just broke the HA state machine and probably kick you out from SmartThings because you are going over the rate limit. I'm just curious to understand why some seconds delay could be an issue,

**Comment by jawn22** [comment]
It used to work pretty instantly about 3-4 months ago (couldn’t pinpoint exactly when though…). The reason the delay is undesirable is that I have an Onkyo stereo amp connected to the TV via Optical cable (stereo amp so doesn’t have HDMI). I have an automation to turn the amp on when TV comes on and off when TV goes off (although aware the integration supports synched entity but I set the automation up before that existed). The 10-20 second delay means a long wait for the sound to start coming out of the amp after the TV turns on. 

I’m not using smartthings if that makes any difference. 

Rest of the integration is excellent - can’t fault it. Once a physical all in one remote comes out that works well with home assistant (pinning my hopes on Yio Remote Two) then I plan to move to that and ditch the physical Samsung remote.

**Comment by ollo69** [comment]
> It used to work pretty instantly about 3-4 months ago

This is strange, anyway I'm working on a different method to detect power status... stay tuned😉

**Comment by ollo69** [comment]
@Saponelli,

I completed the changes, could you try last version and give me your feed-back? In any case I will not be able to do better than this😉

**Comment by wigster** [comment]
Hi. I have to say whatever you did for .11 works great here: MU 2018 series TV. HA recognises that it’s on within a second, while before if would take around 20-30. 

Thanks a lot!

**Comment by jawn22** [comment]
@ollo69 after a few days testing, it’s working really well. Very fast to detect power on/off state - great work!!

**Comment by yusrimathews** [comment]
I also struggled to get any of the "TCP port used to check power status" options working; `0, 9110, 9119, 9197`
I even tried a port I know was working for sure; `8001`

So I created a binary sensor using the REST platform:
```
binary_sensor:
  - platform: rest
    name: SamsungTV Alt Power State
    resource: 'http://TV_IP:8001/api/v2/'
    value_template: >
      {% if ( value_json.device.PowerState == 'on' ) %}
        on
      {% else %}
        off
      {% endif %}
```

Then I use this sensor as the "Binary sensor to help detect power status", and it works!

There is also other useful information returned on the above endpoint.
In case this helps anyone else 🙏🏽
