### ISSUE TITLE
Homekit Exposition

### ISSUE THREAD

**Issue by epalzeolithe** [ollo69/ha-samsungtv-smart#18]
Hi you did a great JOB !!!! Thanks

Now it's working again (jaruba discontinued ?)

Small issue there, the channels are not exposed anymore to homekit, only tv and HDMI.

Do i have to do something ?

Thanks :)

**Comment by ollo69** [comment]
Smartthings is not refresh channel and channel number automatically from some time. 
If you open smartthings app on the phone, then the information are updated again, until the TV is switched off.
I still do not exactly understand what the phone application do when is open...

**Comment by rosch100** [comment]
Could this be related? I keep getting this error from homekit quite frequently: 
Logger: homeassistant.components.homekit.type_media_players

```
Source: components/homekit/type_media_players.py:408 
Integration: HomeKit (documentation, issues) 
First occurred: 7:22:18 (15 occurrences) 
Last logged: 15:37:57

media_player.samsung_tv_2: Sources out of sync. Restart Home Assistant
```

**Comment by ollo69** [comment]
I don't have home kit. Do you know what `Sources out of sync` means?

**Comment by rosch100** [comment]
Sources out of sync means that the channels/(apps?) list do not match anymore.

**Comment by Krocko** [comment]
I have the same problem (HomeKit)
```
Logger: homeassistant.components.homekit.type_media_players
Source: components/homekit/type_media_players.py:408 
Integration: HomeKit (documentation, issues) 
First occurred: 18:48:52 (2 occurrences) 
Last logged: 19:23:07

media_player.fernseher_wohnzimmer: Sources out of sync. Restart Home Assistant
```

**Comment by ollo69** [comment]
I took a look to the piece of code that generate this warning in HomeKit, I think that this can happen if you launch an app or you select a source in the TV that is not in your app_list / source_list.
This can happen in the component because you can create your custom app_list and source_list, so seems more a problem in HomeKit that should not care about this. To try avoid the problem configure the app and source that you normally use.

**Comment by rosch100** [comment]
@ollo69 Thank you for looking into this! So, I'll just ignore it.
