### ISSUE TITLE
The handshake operation timed out ERROR 

### ISSUE THREAD

**Issue by leranp** [ollo69/ha-samsungtv-smart#180]
**Describe the bug**
After updating HA to 2022.9.0 there's an of the addon

**Expected behavior**
If applicable, a clear and concise description of what you expected to happen.

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc):
 - Home Assistant version installed:
 - Component version installed:
 - Last know working version:
 - TV model:
Docker On NUC

**Output of HA logs**
Paste the relavant output of the HA log here.

```
websocket connected
_ssl.c:980: The handshake operation timed out - goodbye
Connection timed out - goodbye
```

**Additional context**

**Comment by ollo69** [comment]
Please provide more logs and diagnostics.

**Comment by leranp** [comment]
after debug the result was that the smarting's wasn't connected , i have remove the option related to smarting's and now look good, will reopen if it returned

**Comment by ollo69** [comment]
You should check on your mobile phone app if SmartThings is properly connected to your TV, sometimes you must remove and add it again due to some update at Samsung cloud. SmartThings add many feature to the integration.

**Comment by leranp** [comment]
> You should check on your mobile phone app if SmartThings is properly connected to your TV, sometimes you must remove and add it again due to some update at Samsung cloud. SmartThings add many feature to the integration.

Probably this is the issue in this case because Google Assistant doesn't connect to my smartthing in the past 3 months
Thank a lot
