### ISSUE TITLE
Repetitive warning message from websocket library

### ISSUE THREAD

**Issue by Opontios** [ollo69/ha-samsungtv-smart#181]
For some days after the last update it stopped giving any notifications. Now this again. Should we just ignore it?
![Безымянный](https://user-images.githubusercontent.com/71525089/189380907-7f85ecbc-e377-4fe5-9db9-906d113234ef.jpg)

**Comment by ollo69** [comment]
Did you update to last version? Please attach diagnostics and logs.

**Comment by Opontios** [comment]
> Did you update to last version? Please attach diagnostics and logs.

Yes, it's updated, and I mentioned it.

> For some days after the last update it stopped giving any notifications. Now this again. Should we just ignore it?

```
2022-09-11 02:10:41.138 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration samsungtv_smart which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-09-11 02:10:51.447 WARNING (SamsungRemote) [websocket] websocket connected
2022-09-11 02:10:51.583 WARNING (SamsungControl) [websocket] websocket connected
2022-09-11 02:10:51.605 WARNING (SamsungArt) [websocket] websocket connected
2022-09-11 11:44:40.631 WARNING (SamsungRemote) [websocket] websocket connected
2022-09-11 11:44:40.767 WARNING (SamsungControl) [websocket] websocket connected
2022-09-11 11:44:40.796 WARNING (SamsungArt) [websocket] websocket connected
```
[config_entry-samsungtv_smart-48d1cc88e5693d6f92bd373e8cc47ac1.json.txt](https://github.com/ollo69/ha-samsungtv-smart/files/9542295/config_entry-samsungtv_smart-48d1cc88e5693d6f92bd373e8cc47ac1.json.txt)

**Comment by ollo69** [comment]
The integration is working properly or you have some issue?

**Comment by Opontios** [comment]
> The integration is working properly or you have some issue?

It's working nicely, at least I haven't noticed anything strange.

**Comment by ollo69** [comment]
This warnings are really strange, because they are not in integration code. I'm not understanding where they are coming from!

**Comment by dwd1** [comment]
I see the same "warning".

![image](https://user-images.githubusercontent.com/3084630/190869702-19d51f24-7a64-44e2-b8f2-622c48c41749.png)

 Source: custom_components/samsungtv_smart/api/samsungws.py:376 
 Source: custom_components/samsungtv_smart/api/samsungws.py:466 
 Source: custom_components/samsungtv_smart/api/samsungws.py:592

**Comment by maxgiordan** [comment]
![SharedScreenshot](https://user-images.githubusercontent.com/51880181/196231734-79c91cde-b464-4335-8bea-71c190088059.jpg)

The same for me, for at least a couple of months and with some variations: Connection refused - goodbye - Error handling message: Unauthorized (unauthorized)

**Comment by jandado** [comment]
Could there have been a change in websocket library logging recently? It is appears to be coming from the websocket logger - is there code in the integration to configure it? (as per https://websockets.readthedocs.io/en/stable/topics/logging.html#disable-logging)

**Comment by maxgiordan** [comment]
Great job, thanks!

**Comment by ollo69** [comment]
Can we close this issue?

**Comment by Opontios** [comment]
> Can we close this issue?

I think it must be closed. Thanks for the effort! Finally without those three constant warnings.
