### ISSUE TITLE
write text in phone and send to app (netflix, amazon prime...)

### ISSUE THREAD

**Issue by jalejandrio2** [ollo69/ha-samsungtv-smart#183]
I would like to see if it's possible to write a text message in the companion app of HA in the android phone (text input) and send that text to any app that is currently open (netflix, hbo...) so we don't have to go to every letter with the commands of up, down...

**Describe the solution you'd like**
write it on the phone and send it to the screen

**Comment by treynairn** [comment]
Im pretty sure its a limitation of Tizen.. Keyboards have never worked on remote apps etc when everything else does
