### ISSUE TITLE
Service select_picture_mode no longer works

### ISSUE THREAD

**Issue by sepodele** [ollo69/ha-samsungtv-smart#184]
**Describe the bug**
After update to 0.7.7 I'm unable to change picture mode with samsungtv_smart.select_picture_mode

**Expected behavior**
I expect the service to change picture mode.

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HAOS
 - Home Assistant version installed: 2022.9.7
 - Component version installed: 0.7.7
 - Last know working version: 0.7.6
 - TV model: QE65Q80T

**Output of HA logs**
Paste the relavant output of the HA log here.
```
samsungtv_smart.select_picture_mode extra keys not allowed @ data['entity_id']. Got None
```

**Additional context**
Here is the script:
`
service: samsungtv_smart.select_picture_mode
data:
  entity_id: media_player.qe65q80t
  picture_mode: Standard
`

**Comment by IceyyBoi** [comment]
Same here

**Comment by maximlefebvre** [comment]
Same here with 0.7.7, Home Assistant on 2022.9.7 and QE50Q80T.

**Comment by ollo69** [comment]
Close this because fixed with last release. Please open again if still have issue.

**Comment by maximlefebvre** [comment]
Hi @ollo69, thanks for your help. Great jobs with this integration!
