### ISSUE TITLE
Show Mute, Source and Power on iOS Remote Control

### ISSUE THREAD

**Issue by Lou-i3** [ollo69/ha-samsungtv-smart#187]
**Is your feature request related to a problem? Please describe.**
The current integration of the iOS Remote Control doesn't allow using the muse, source and power buttons available at the top of the remote's UI. 

**Describe the solution you'd like**
Find a way to map the keys to the remote as explained in issue https://github.com/ollo69/ha-samsungtv-smart/issues/51 

**Describe alternatives you've considered**
Create another entry in homekit for the TV where it is possible to turn on/off the TV and select the source configured. 

**Additional context**
Thanks a lot!

**Comment by git-novembre** [comment]
I would like too this feature :)
