### ISSUE TITLE
Fake turn on status

### ISSUE THREAD

**Issue by matata86** [ollo69/ha-samsungtv-smart#196]
**Describe the bug**
I'm testing different settings, but after turning off the TV, I always get a fake TV on status after about two minutes.

**Screenshots**
![1](https://user-images.githubusercontent.com/28623294/206845964-d16ef9ba-757a-47b0-8268-60d3822df0d9.png)
![2](https://user-images.githubusercontent.com/28623294/206845969-302fe999-8086-4223-91fb-17598c027c35.png)
![3](https://user-images.githubusercontent.com/28623294/206845972-4b891801-573d-46d1-823d-67902d24cfc9.png)

**Comment by ollo69** [comment]
Is this issue still present with last  releases? Status detection method was totally review.

**Comment by matata86** [comment]
Yes... :-(

![Domov-–-Home-Assistant](https://user-images.githubusercontent.com/28623294/214701272-020abaa3-65c6-4f4d-a1cf-42456aec4af5.png)
![1](https://user-images.githubusercontent.com/28623294/214701277-68b2f5d5-824a-433d-9f9d-e5985d8dd0ff.png)
![2](https://user-images.githubusercontent.com/28623294/214701280-54c0f9e6-e24f-4d55-ac58-dd889395560e.png)

**Comment by ollo69** [comment]
If you don't have a soundbar, try enabling option "Use volume mute status to detect fake power ON"

**Comment by matata86** [comment]
I use samsung soundbar.

**Comment by mspinolo** [comment]
Hi, I am back to this issue as well and not using a sounbar.
Activated "Use volume mute status to detect fake power ON" but no success

![image](https://user-images.githubusercontent.com/43354538/222745186-25ffb008-7300-44f3-8a28-4c7e44e96278.png)

on another topic I mentioned I had issue with Smarthing connection, but it is no more the case.
So issue persist

**Comment by Marekjdj** [comment]
I'm having the same issue with my Samsung TV. Seems to happen a few minutes after turn off the TV and (pretty much exactly) an hour after turning it off. Very strange.
