### ISSUE TITLE
TV channel names 

### ISSUE THREAD

**Issue by FilippoS1973** [ollo69/ha-samsungtv-smart#20]
Hi Ollo69,
Your integration works well but TV channel names doesn’t update. the name of the tv channel that was tuned when I inserted the tv in smarttings always remains.  the same problem appears with the samsung tizen integration
My tv is q7fn series 2018. Configuration with token

**Comment by ollo69** [comment]
Problem is that from some time Samsing changed samthing at SmartThings side and channel information is not provided anymore properly.
On my side I have to open the smartthings app 1 time, after this the channel is shown properly again until the TV is switched off. 
I still do not understand if there is some command that can be sent to the TV to fix this, for the moment I don't a solution.

**Comment by ollo69** [comment]
TV Channel with last release is not used anymore if not explicity set the option on the integration page. 
Please report here if everythink work properly (obviosly TV channel will not be shown at all).

**Comment by sunsgs** [comment]
Is it possible to have also currently playing on netflix?  with the title?

**Comment by ollo69** [comment]
> Is it possible to have also currently playing on netflix? with the title?

No because this information is not available, there is no way to implement this feature.

**Comment by ollo69** [comment]
Closing inactive issue,
