### ISSUE TITLE
Netflix App causing incorrect status / details reported

### ISSUE THREAD

**Issue by salty2011** [ollo69/ha-samsungtv-smart#204]
**Describe the bug**
When launching the Netflix app through the TV remote the integration reports the devices as either Offline or Displays the details of the previous app launched.

Going into the developer > States to look up information also shows either offline state or the previous app. I am trying to configure the application list so I can launch Netflix on the device from HA. Have tried manually configuring the application with one of the documented AppID's and in developer > State the media title is either not listed due to device showing offline or previous app details listed

From what I can tell it would appear that this is the only app causing this issue.

**Expected behavior**
When launching the netflix app using the remote / tv ui the home assistant entity for this device should be displaying the current source / the developer mode should also display this formation.

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Home Assistant on Ubuntu Server
 - Home Assistant version installed: 
                 Home Assistant 2022.12.7
                Supervisor 2022.11.2
                Frontend 20221213.1 - latest

 - Component version installed: 0.9.1
 - Last know working version: NA, just installed component again for the first time in a year
 - TV model: Samsung Q80 (75)

**Output of HA logs**
Paste the relavant output of the HA log here.

```
2022-12-19 14:28:09.465 ERROR (MainThread) [homeassistant.util.logging] Exception in _update_config_options when dispatching 'samsungtv_smart_config': ()
Traceback (most recent call last):
  File "/config/custom_components/samsungtv_smart/media_player.py", line 447, in _update_config_options
    self._load_tv_lists(first_load)
  File "/config/custom_components/samsungtv_smart/media_player.py", line 434, in _load_tv_lists
    double_list = self._split_app_list(app_list, "/")
  File "/config/custom_components/samsungtv_smart/media_player.py", line 408, in _split_app_list
    value_split = value.split(sep, 1)
AttributeError: 'int' object has no attribute 'split'
```

I do not believe the above is related as the time stamps do not match for when I am reproducing the error. This is only thing mentioned in the log regarding this component

**Additional context**
[config_entry-samsungtv_smart-4d5eeffa8a8e93dc521ae820fac114e5.json (1).txt](https://github.com/ollo69/ha-samsungtv-smart/files/10256981/config_entry-samsungtv_smart-4d5eeffa8a8e93dc521ae820fac114e5.json.1.txt)

**Comment by salty2011** [comment]
Actually, this issue can also be replicated on the following apps when launch directly via the tv

Disney+
AppleTV App
Amazon Prime

**Comment by salty2011** [comment]
nm, turns out there was another id for the netflix app

3201907018807/org.tizen.netflix-app

**Comment by ollo69** [comment]
@salty2011,

can you better clarify what was the issue and how you fix it? I would create some checks to avoid this kind of situation, but I need to better understand why this was happening.

**Comment by salty2011** [comment]
hey @ollo69, root cause of the issue was I was using the wrong app identifier in the Application list config. (Originally was trying the values from LIST 1/2 from the doco). However my tv is using value that match "3201907018807/org.tizen.netflix-app" this is the same for the other apps.

Interesting when the app id are incorrectly set the integration seems to either not work by either not updating the source or indicating an error in the log or the TV will show as offline until the source is changed back to a valid value.

 Did try getting the app list dumped option in the integration but doesn't appear to work for my 2019/20 Q80T Samsung.

Have tried some api requests listed in various posts to dump the app list, but no go.... Also tried looking via the smart things graph API, but that's to an EU version and my tv isn't registered against that (need to look into it more)

Core issue is kinda user error as I did config incorrectly, but given no logs are provided or feedback in the UI to indicate the where the issue may lay.

**Comment by salty2011** [comment]
@ollo69 do you know what API doco I could review as would be interested in seeing if we could

- Get a consistent method for getting a list of installed apps
- Auto configuring installed apps.
- Extending the media_player entity with playback status (ie playing, stopped, idle, paused etc similar to Apple TV if possible)

**Comment by ollo69** [comment]
> Interesting when the app id are incorrectly set the integration seems to either not work by either not updating the source or indicating an error in the log or the TV will show as offline until the source is changed back to a valid value.

This is a bug, will be fixed with next release.

> do you know what API doco I could review as would be interested in seeing...

Unfortunately Samsung documentation about this is very limited and behavior changes depending on TV models. I don't have any valid suggestion for this.

**Comment by ollo69** [comment]
I close this issue, fixed with last release.
