### ISSUE TITLE
App list not saving after update 0.9.1

### ISSUE THREAD

**Issue by fherreror** [ollo69/ha-samsungtv-smart#205]
**Describe the bug**
I had app list configured in yaml.
After last update 0.9.1, In the new App list config UI, I write the app list (e.g. Netflix: 3201907018807/org.tizen.netflix-app) and click on send. I close the config UI, open integration config again and App list config is empty.
In addition. No app (e.g. Netflix) shows now on media card list, while before the update, I had many.
In previous version, I had app list configurated in yaml and it worked fine. Now it does not work even with yaml app list config activated.

**Expected behavior**
The app list should be saved and I should be able to see it in the config UI. The app list should appear too in the media card UI.

**Screenshots**
None

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Hassio
 - Home Assistant version installed: 2022.12.6
 - Component version installed: 0.9.1
 - Last know working version: 0.8.1
 - TV model: UE65TU7172

**Output of HA logs**
Paste the relavant output of the HA log here.
Nothing about config update.

**Additional context**
It is all explained above

**Comment by ollo69** [comment]
To save configuration you must go back to main page (first option in the menu) and click send on that page. You will see a message that options are saved.

**Comment by fherreror** [comment]
> To save configuration you must go back to main page (first option in the menu) and click send on that page. You will see a message that options are saved.

Thanks. That worked perfectly. It was not intuitive returning to the previous page via the first option in the menu.
Thanks for all.
