### ISSUE TITLE
Error when retrieving app on TV

### ISSUE THREAD

**Issue by gsanhaji** [ollo69/ha-samsungtv-smart#214]
Hi,
When I open Netflix on the TV, HA show that it's YouTube and when i open YouTube, it shows Netflix.
I have 4 different TVs in my home and the 4 of them do the same problem.
<img width="505" alt="Capture d’écran 2023-01-08 à 13 27 22" src="https://user-images.githubusercontent.com/110345517/211196030-41ea17da-836c-4e68-8ea9-85fc2a42ceae.png">

I think the problem comes from the link between HA and SmartThings as on SmartThings, the correct app is shown and not on HA.
![IMG_5069](https://user-images.githubusercontent.com/110345517/211196104-a644c8fb-ef0b-42e4-b517-23c97d190066.jpg)

**Environment details:**
 - HAOS 9.4 on generic x86-64
 - Home Assistant 2023.1.1
 - Samsungtv Smart v0.9.4
 - TV model: QE85Q60BAUXXC // QE65Q60RATXXC // UE55NU7470 // UE50NU7470

**Comment by ollo69** [comment]
Did you try is last release fix the issue?

**Comment by gsanhaji** [comment]
@ollo69 First of all, thank you for your work. RESPECT

Sadly, one tv is working and another one load only the output on HDMI and not applications
<img width="579" alt="Capture d’écran 2023-02-08 à 00 52 06" src="https://user-images.githubusercontent.com/110345517/217393997-9537b2bd-8365-4448-a7e7-21149bd1bdf2.png">

**Comment by ollo69** [comment]
Did you try to manual configure application list. Not all TV provide the list of installed application.

**Comment by gsanhaji** [comment]
Not yet, i'm doing it right now.
I think it was interesting to give you this feedback.

**Comment by gsanhaji** [comment]
So, i did it.
All the application works (load on sources and can be controlled) but not Netflix.

**Comment by ollo69** [comment]
Please share your applications list

**Comment by gsanhaji** [comment]
@ollo69 
    app_list: '{"Netflix": "11101200001", "YouTube": "111299001912", "Spotify": "3201606009684"}'

**Comment by ollo69** [comment]
I suppose that you edit JSON config in `configuration.yaml`, but app list now can be configured using UI options and `configuration.yaml` is deprecated.
The AppID that you use for Netflix is the old one, you could try using the new. And also is better to add the SmartThings AppID as backup.
So edit your list (using Integration option and not `configuration.yaml` that will be ignored after first import) in this way:

```
Netflix: 3201907018807/org.tizen.netflix-app
YouTube: 111299001912/9Ur5IzDKqV.TizenYouTube
Spotify: 3201606009684/rJeHak5zRg.Spotify
```

**Comment by gsanhaji** [comment]
Thank you @ollo69 
Great job
