### ISSUE TITLE
Fake TV turn off

### ISSUE THREAD

**Issue by mspinolo** [ollo69/ha-samsungtv-smart#215]
**Describe the bug**
I have fake turn off of my the frame tv. Ethernet connected

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): hass os in proxmox vm 
 - Home Assistant version installed: 2023.1.6
 - Component version installed: 0.9.4
 - Last know working version: not known, it was not happening since few weeks ago
 - TV model: Samsung the frame 2021 version

**Comment by Piero87** [comment]
I have a frame tv 2021, and when I power off I can't see the art like when I press the power off button on the remote or on the smart things app, any idea?

**Comment by ollo69** [comment]
Please explain better what really happen and when. BTW, did you try last version? Issue still present?

**Comment by mspinolo** [comment]
Hi,

So at the end the issue was not on the integration: mis-behavior was due to the fact I adopted pfblockerNG and SmartThings connection was blocked.

So as result I guess TV state check was less reliable (old version)

This weekend I will try next version

**Comment by mspinolo** [comment]
Tested the latest version: MUCH better!
no difference in terms of reliability (good, once I solved my filtering issue), a lot quicker in detecting state change.

Great job!

**Comment by ollo69** [comment]
Thanks, so I close this issue.
