### ISSUE TITLE
Update for media_player.samsung_tv fails in v0.11.2

### ISSUE THREAD

**Issue by tlamoureux24** [ollo69/ha-samsungtv-smart#223]
Hello,

With the last update v0.11.2 i have lot's of error in HA logs.

Cette erreur provient d'une intégration personnalisée

Logger: homeassistant.helpers.entity
Source: custom_components/samsungtv_smart/media_player.py:1007
Integration: SamsungTV Smart (documentation, issues)
First occurred: 15:51:21 (67 occurrences)
Last logged: 16:07:31

Update for media_player.samsung_tv fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in async_device_update
    raise exc
  File "/config/custom_components/samsungtv_smart/media_player.py", line 848, in async_update
    await self._update_media()
  File "/config/custom_components/samsungtv_smart/media_player.py", line 947, in _update_media
    new_media_title = self._get_new_media_title()
  File "/config/custom_components/samsungtv_smart/media_player.py", line 1007, in _get_new_media_title
    if run_app not in list(self._app_list_st.values()):
AttributeError: 'NoneType' object has no attribute 'values'

Rolling back to v0.11.0 solved the issue.

Home Assistant 2023.1.7
Supervisor 2023.01.1
Operating System 9.5
Interface utilisateur : 20230110.0 - latest

Thanks.

**Comment by ollo69** [comment]
Can you better explain the condition that generate the error? Do you have application list configured or is auto generated from the TV? What is the source selected when error occur? It is clear how to fix this specific condition but I would replicate the problem to be sure that there are no other issue.

**Comment by tlamoureux24** [comment]
I just update the integration, doesn't change any parameters.
List is auto generated from the tv, source is antenna in my case.
Rollback to v0.10.0 fix this issue.

**Comment by ollo69** [comment]
Ok, replicated the issue, I will release fix shortly.

**Comment by ollo69** [comment]
Released v0.11.3 to fix this issue

**Comment by tlamoureux24** [comment]
Thank you for these quick fixes !!!!
