### ISSUE TITLE
A progress bar for movies

### ISSUE THREAD

**Issue by LinuxTux193** [ollo69/ha-samsungtv-smart#226]
**Is your feature request related to a problem? Please describe.**
Hi, I'd like to see what point in a movie or series I'm at and be able to go forward or backward in playback.

**Describe the solution you'd like**
A progress bar that indicates where you are in a movie or episode and that you can move to go forward or backward in the video

**Describe alternatives you've considered**
I have no idea

**Additional context**

**Comment by ollo69** [comment]
This is not possible, these informations are not available.

**Comment by LinuxTux193** [comment]
ok, thanks
