### ISSUE TITLE
Error refreshing from SmartThings. Check connection status with TV on the phone App

### ISSUE THREAD

**Issue by nagydavid** [ollo69/ha-samsungtv-smart#229]
**Describe the bug**
I am getting this error everyday almost 5-10 times: 
Error refreshing from SmartThings. Check connection status with TV on the phone App

**Expected behavior**

No error?!

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc):hassio proxmox vm 

 - Home Assistant version installed:
202302.1
 - Component version installed:
V0.11.5
 - Last know working version:
Actually it happened since the beginning.
 - TV model:
Samsung tv 2020
**Output of HA logs**

Logger: custom_components.samsungtv_smart.media_player
Source: custom_components/samsungtv_smart/media_player.py:825 
Integration: SamsungTV Smart (documentation, issues) 
First occurred: 19:21:07 (19 occurrences) 
Last logged: 19:44:52

media_player.tv_living_room - Error refreshing from SmartThings. Check connection status with TV on the phone App
media_player.tv_living_room - Connection to SmartThings restored

```

```

**Additional context**

**Comment by rudizl** [comment]
Same here.

**Comment by ollo69** [comment]
In last release I review a little bit the logic in SmartThings error loggings to provide some more details, but I don't that will fix this problem. SmartThings errors are logged when information are not properly retrieved from the cloud after 4 consecutive polling. This error means that you have some issue connecting to SmartThings, this can depend on your internet connection (that I suppose you will say it's perfect😉), TV or HA connection to the internet or may be an issue at SmartThings side.

**Comment by rudizl** [comment]
Same error after last update 😢
````
This error originated from a custom integration.

Logger: custom_components.samsungtv_smart.media_player
Source: custom_components/samsungtv_smart/media_player.py:847
Integration: SamsungTV Smart (documentation, issues)
First occurred: 16:40:31 (1 occurrences)
Last logged: 16:40:31

media_player.samsung_tv - SmartThings report TV is off but status detected is on. Check connection status with TV on the phone App
````

**Comment by ollo69** [comment]
And as you see that is the error: `SmartThings report TV is off but status detected is on`. Did you try to open SmartThings app on your phone to see what is reported?

**Comment by ollo69** [comment]
And the TV is on, right?

**Comment by rudizl** [comment]
Of course 😊

**Comment by ollo69** [comment]
So error is correct, you need to investigate why SmartThings not working (also in app).

**Comment by rudizl** [comment]
Now ST shows the right state. I really have no idea how to proceed.

**Comment by gsanhaji** [comment]
I had the same issue. I deleted all the TVs on ha AND smartthings and reconfigure them all. 
Everything came back to the normal. I think smartthings changed something on their WS.

**Comment by rudizl** [comment]
Check this https://github.com/ollo69/ha-samsungtv-smart/issues/8
Also this page https://graph-eu01-euwest1.api.smartthings.com/device/list
Now everything works fine. For some reason the type of tv has changed to `placeholder`
