### ISSUE TITLE
Prime Video logo is not shown

### ISSUE THREAD

**Issue by alex-schuska** [ollo69/ha-samsungtv-smart#235]
First of all, thank you for your work! Your Samsung TV integration is working great for me.

I only have discovered one little problem so far: The Prime Video logo is not shown. Everything else works as expected.

![image](https://user-images.githubusercontent.com/126088824/220672750-6a2faf57-7c30-4432-a9a6-70f34389ca47.png)

I guess the reason could be that I have to use "Prime Video": "3201910019365/org.tizen.primevideo" in the application list, instead of the provided example "Prime Video": "3201512006785", to function with my TV. "Prime Video": "3201512006785" will show the Prime Video Logo, but my TV won't start the application.

3201910019365 and org.tizen.primevideo are the correct IDs for my setup. Starting the application and showing the active state is working fine.

My application list:

{"Netflix": "3201907018807/org.tizen.netflix-app", "YouTube": "111299001912/9Ur5IzDKqV.TizenYouTube", "Disney+": "3201901017640/MCmYXNxgcu.DisneyPlus", "Prime Video": "3201910019365/org.tizen.primevideo", "Joyn": "3201502001386/cg2m3QSB89.7tv"}

API result for 3201910019365:

![image](https://user-images.githubusercontent.com/126088824/220667177-6040e1fd-0fb4-4c99-9b2d-8dcca07197ac.png)

Environment:

- HAOS 9.5 Generic x86-64 running on a Lenovo Thinkcentre M600 N3010
- Home Assistant 2023.2.5 (Supervisor 2023.01.1)
- ha-samsungtv-smart V 0.11.6 installed via HACS
- Samsung AU8079 55"

**Comment by Krocko** [comment]
I have the same problem with the emby logo.
