### ISSUE TITLE
TV state flipping to On every 25 mins even when TV is off

### ISSUE THREAD

**Issue by bwoodworth** [ollo69/ha-samsungtv-smart#24]
**Describe the bug**
The state of the tv flips to On and then Off every 25 mins even when TV is off.  This is causing issue with automations based on TV state

**Expected behavior**
I would expect the state of the entity to match the actual TV

**Screenshots**
https://imgur.com/a/dRvoLB7

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): hassio
 - Home Assistant version installed: 0.110.4
 - Component version installed: 0.3.4
 - Last know working version:
 - TV model: Samsung Q6 series

**Output of HA logs**
Paste the relavant output of the HA log here.

```

```

**Additional context**

**Comment by ollo69** [comment]
This is same as issue #23 
How long state result ON? Try to increase the config option "Seconds to delay power ON status" (maximum value now is 60 sec)

**Comment by bwoodworth** [comment]
Thanks!!  Sorry for the duplicate issue.
