### ISSUE TITLE
On/Off status flipping within 1 second

### ISSUE THREAD

**Issue by rogerveijk** [ollo69/ha-samsungtv-smart#249]
**Describe the bug**
When i watch my entity log i see my TV status flipping (on/off) all the time within 1-2 seconds. However my TV is for sure on and playing a stream (problem is not app specific). 

**Expected behavior**
I would expect the on/off status is more stable / or slower polling interval? 

**Screenshots**
https://snipboard.io/yjxFfT.jpg

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Hassio
 - Home Assistant version installed: 2023.3.6
 - Component version installed: 11.6
 - Last know working version: no clue
 - TV model: UE82RU8002UXXH

**Additional context**
TV doesn’t show internet connection issues notifications / errors.

**Comment by wilcomir** [comment]
I have the same issue.

**Comment by rogerveijk** [comment]
The problem is not officially solved, but I’ll share my workaround automations. I’ve put in a delay of 5 sec for status changes, this resolves the unwanted automation behaviour.
