### ISSUE TITLE
TV says it's turning on for a 34 seconds every 25 min or so

### ISSUE THREAD

**Issue by JeffSteinbok** [ollo69/ha-samsungtv-smart#253]
**Describe the bug**
After a recent HA upgrade, am finding that both my Samsung TVs that are off are reporting their status as ON for 34 seconds a couple times per hour. Looks like about every 25m. 

Please advise what logs to collect. 

**Expected behavior**
TVs are off

**Screenshots**
![image](https://user-images.githubusercontent.com/7330767/236115931-c539d4a9-e7e1-42b9-bd19-e59d91a01382.png)

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): 
 - Home Assistant version installed: 2022.05
 - Component version installed: latest
 - Last know working version: unknown. Will try older ones
 - TV model: 

**Output of HA logs**
Paste the relavant output of the HA log here.

```

```

**Additional context**

**Comment by JeffSteinbok** [comment]
Ok, this is clearly the same as #23, but now that you've removed the option to wait more than 30s to see if it's on/off, how should one work around this?

**Comment by wilcomir** [comment]
Hey @JeffSteinbok I was having an issue similar to yours - from the #23 you linked it seems that disabling automatic updates is the way to go, if that is an acceptable solution for you. I just tried on both my TVs and it seem to _finally_ have cured the issue.

**Comment by JeffSteinbok** [comment]
Yeah, I know that's a possible workaround but I'd rather not do that assuming @ollo69 can fix.

**Comment by ollo69** [comment]
This normally occur because the TV looks like on when is checking for update. There are some possible work-around in advanced options, what are your settings?

**Comment by JeffSteinbok** [comment]
What can I send you? 
Old version worked where it did the 30s delay thing.

**Comment by ollo69** [comment]
Just try changing some of that options based on information provided in readme. You can attach to this thread diagnostic so that I can see current settings.

**Comment by JeffSteinbok** [comment]
Not sure what options to change; did read the README.

[config_entry-samsungtv_smart-474e6da75b9b4d03423cd013e20fb23a.json.txt](https://github.com/ollo69/ha-samsungtv-smart/files/11418012/config_entry-samsungtv_smart-474e6da75b9b4d03423cd013e20fb23a.json.txt)

**Comment by JeffSteinbok** [comment]
@ollo69  - Any thoughts?

**Comment by JeffSteinbok** [comment]
Any thought @ollo69? Which settings?  Any replacement for that 30s delay option you used to have?

**Comment by JeffSteinbok** [comment]
@ollo69?

**Comment by JeffSteinbok** [comment]
@ollo69 can you advise what settings to change?  Any chance you can add-back that timeout?

**Comment by JeffSteinbok** [comment]
@ollo69 - Can you please re-open?  Possible to add that delay in detection like it was before?
