### ISSUE TITLE
Original Integration Faster

### ISSUE THREAD

**Issue by milandzuris** [ollo69/ha-samsungtv-smart#259]
Original Integration is Very more Faster, exist some fix for this?

**Comment by milandzuris** [comment]
@ollo69

**Comment by ollo69** [comment]
Faster doing what? Provide more details and example.

**Comment by milandzuris** [comment]
> Faster doing what? Provide more details and example.

faster control etc. if I add a sound it is done immediately same for other controls.

**Comment by ollo69** [comment]
I do not understand what you mean. What does it mean "add a sound". 
When I control my TV using integration (eg volume control, change channel, change app..) TV react with no delay.
Provide a real example of one functionality indicating effective time by native integration and this integration.
