### ISSUE TITLE
send_key not always working

### ISSUE THREAD

**Issue by sunsgs** [ollo69/ha-samsungtv-smart#26]
Hi there,
I use your great plugin with smartThings key

From services:
media_player.play_media

entity_id: media_player.tv
media_content_type: "send_key"
media_content_id: KEY_POWER

it works (some times) only if the tv is on. The key KEY_POWERON/KEY_POWEROFF never works

**Expected behavior**
It always work , I need to switch on the tv with a script

**Environment details:**
 - Environment (HASSIO)

**Comment by ollo69** [comment]
KEY_POWERON/KEY_POWEROFF do not work for Tizen TV, they only use KEY_POWER.
But generally speaking, to turn on and off the TV using script you should use the related service "media_player.turn_off" and "media_player.turn_on", the integration will than manage the right way to change the TV status.

**Comment by ollo69** [comment]
Closing this issue, pls re-open if still have problem.
