### ISSUE TITLE
App list not being generated and apps not showing in sources

### ISSUE THREAD

**Issue by mbarnes106** [ollo69/ha-samsungtv-smart#27]
Clean install of SamsungTV_Smart on Home assistant.

Added the hacs repository, added the integration.
Set up the integration using the UI. 
Pop up appeared on TV asking to give Home Assistant access
Restarted HA.

Integration shows media_player.lounge_tv having been created. File in custom components folder are:

.translations
_init_.py
api (folder)
config_flow.py
const.py
manifest.json
media_player.py
token-192.168.1.138.txt
translations (folder)

Sources available to select are: TV, Hdmi1, Hdmi2, Hdmi3, Hdmi4

No apps are listed anywhere or available for selection

TV model is 2020 QE55Q70TATXXU
HA Core version 0.110.4

![Capture](https://user-images.githubusercontent.com/51041880/84037698-db709b00-a996-11ea-8b77-3dd387d1ce21.JPG)

**Comment by ollo69** [comment]
Can you enable debug log for the component adding this lines in configuration.yaml (please check that `logger:` option is not already present, in case just add the other lines):

```
logger:
  default: info
  logs:
    custom_components.samsungtv_smart: debug
```

Then please post the log related to the component so that I can try to understand where is the issue.

**Comment by mbarnes106** [comment]
Hello, hope this is what you mean / need:

[debuglog.txt](https://github.com/ollo69/ha-samsungtv-smart/files/4750686/debuglog.txt)

**Comment by ollo69** [comment]
Yes, info is correct. Looking at the log seems that app_list is never send back after request.
Just to better understand, are you able to send command to the TV (eg. Volume Up - Volume Down, play / pause, etc)?

**Comment by mbarnes106** [comment]
Yep, I’ve added the generated entity as a media card in HA and can turn tv on, control volume, pause and change source

**Comment by ollo69** [comment]
It will be hard for me solve this, it seems that the standard command do not provide any answer, as always probably samsung change something with last models.
I can try to make some test but I need your support, are you available to install some beta version that I will release on next days and report your feed-back?

**Comment by mbarnes106** [comment]
yep I would be more than happy to help if you dont mind. As you can see I am not the greatest at HA but would love to help get this resolved.

**Comment by ollo69** [comment]
Please install last version released and post again debug log. I don't think this version will solve your issue, but I moved start of comunication channel and I want to see if your TV provide back some information.

**Comment by mbarnes106** [comment]
Thanks. Just to check should I uninstall the old version etc or just update?

**Comment by ollo69** [comment]
Just update

**Comment by mbarnes106** [comment]
Here you go, hope this helps

[debuglog2.txt](https://github.com/ollo69/ha-samsungtv-smart/files/4780848/debuglog2.txt)

**Comment by mbarnes106** [comment]
Did the above help at all?

**Comment by ollo69** [comment]
Not so mutch, I see that other channels starts but nothing more is coming. I have to try moving the call for channel list, but maybe nothing will change.
Unfortunatly my TV is out of order from this week, axactly 2 months after end of warranty, so I cannot do nothing until I will have it back or I will have a new one.

**Comment by ollo69** [comment]
Hi, sorry for late answer.
I did some check, unfortunatly I didn't find a definitive solution. Simply there are some TV model that do not report application list.
In any case I reviewed in last release the method used to check running app, so if you create your app_list in configuration.yaml (see read_me instruction) you should be able to use and see status of app in your list.

Waiting for your feed-back.

**Comment by louisc** [comment]
Hi, 
Just to update this, have the same issues on a 2020 Frame (QE55LS03TAUXXU) 

@ollo69 adding the new app list to config as you suggested does then allow you to switch between apps from HA as well as get the correct read back on the app name

```yaml
samsungtv_smart:
  - host: xx.xx.xx.xx
    app_list: '{"Netflix": "11101200001", "YouTube": "111299001912", "Spotify": "3201606009684", "Internet": "org.tizen.browser" }'
```
I've had no luck casting anything or opening any media from HA to this model though. 

(Sorry to hear about your TV :( )

**Comment by mbarnes106** [comment]
@louisc just checking you added that code within your configuration.yaml for HA did you? Will try this on mine later

**Comment by louisc** [comment]
Indeed @mbarnes106 , just paste as is and add your host. You can pull additional apps and IDs from the links in the docs here: https://github.com/ollo69/ha-samsungtv-smart/blob/master/docs/App_list.md (select the lists)

**Comment by bbrendon** [comment]
I just got a Q90T 2020 model and I can't get the app loading functionality to work as well.

**Comment by mbarnes106** [comment]
I have added that to my config. they are a little slow to work but do now change. All apart from Netflix which will let me select it but will not change the tv to netflix

`samsungtv_smart:
  - host: 192.168.1.138
    app_list: '{"Netflix": "11101200001", "YouTube": "111299001912", "Spotify": "3201606009684", "Internet": "org.tizen.browser" }'
`

**Comment by mbarnes106** [comment]
Just tried this as well:

`"Netflix": "11101200001/org.tizen.netflix-app"`

Still just netflix that will not load.

**Comment by mbarnes106** [comment]
And sorry one more thing while I am trying to sort this all. Is there a way to rename the HDMI1 / 2 / 3 / 4 sources to things like Xbox and Sky etc?

I thought this would work but it does not rename them in the source list and fails to change the source when I select them

`    source_list: '{"HDMI1": "Sky", "HDMI2": "Apple TV", "HDMI3": "Nintendo", "HDMI1": "Xbox"}'`

**Comment by DavidPper** [comment]
@mbarnes106 try this

source_list: '{"ST_HDMI1": "Sky", "ST_HDMI2": "Apple TV", "ST_HDMI3": "Nintendo", "ST_HDMI4": "Xbox"}'

**Comment by mbarnes106** [comment]
> @mbarnes106 try this
> 
> source_list: '{"ST_HDMI1": "Sky", "ST_HDMI2": "Apple TV", "ST_HDMI3": "Nintendo", "ST_HDMI4": "Xbox"}'

That doesnt work I am afraid, that renames all the sources as ST_HDMI1 etc.

**Comment by mbarnes106** [comment]
> > @mbarnes106 try this
> > source_list: '{"ST_HDMI1": "Sky", "ST_HDMI2": "Apple TV", "ST_HDMI3": "Nintendo", "ST_HDMI4": "Xbox"}'
> 
> That doesnt work I am afraid, that renames all the sources as ST_HDMI1 etc.

Changed them round, the description should come first, Samsung name second, so this works.

`
samsungtv_smart:
  - host: 192.168.1.138
    source_list: '{"TV": "ST_TV", "Sky": "ST_HDMI1", "Apple TV": "ST_HDMI2", "Nintendo": "ST_HDMI3", "Xbox": "ST_HDMI4"}'
    app_list: '{"Netflix": "11101200001/org.tizen.netflix-app"   , "Plex": "3201512006963", "YouTube": "111299001912",  "Prime Video" : "3201512006785", "Spotify": "3201606009684", "Internet": "org.tizen.browser" }'

`

Just wish Netflix would open now

**Comment by bbrendon** [comment]
I got the app list to work. I'm not 100% sure but I think what fixed the app list functionality for me was to clear out all the devices from the settings in the TV under Device Connect Manager and then restart smart things on my phone and restart HASS.

**Comment by mbarnes106** [comment]
> I got the app list to work. I'm not 100% sure but I think what fixed the app list functionality for me was to clear out all the devices from the settings in the TV under Device Connect Manager and then restart smart things on my phone and restart HASS.
> 
> EDIT : mbarnes106 : I'm using your `app_list`. The Netflix option doesn't work.

I am using app list in my config yeah. Boo about Netflix! Have you found a way of getting round that?

**Comment by simoa** [comment]
Hi, anyone with the new Samsung tv 2020 is able to run this ?

(Open Netflix)
curl -X POST -i 'http://IP:8001/api/v2/applications/11101200001'

**Comment by mbarnes106** [comment]
Nope can’t load Netflix at all here

**Comment by simoa** [comment]
@mbarnes106 Can you please try this one last time 

(Open Youtube)
curl -X POST -i 'http://IP:8001/api/v2/applications/111299001912'

**Comment by Lemonadel** [comment]
Hello,
I have just found your addon, thank you for creation and developing. 
I am using 2020 Samsung TV, model: QE55Q80TATXXH with Tizen SW 1460 onboard. 

As someone before I could not run any app from HA dropdown list.

I have tested curl from previous message and it’s launching YouTube properly. However Netflix’s curl is having error as response:
![IMG_0781](https://user-images.githubusercontent.com/43881989/103142855-9bdb8780-470b-11eb-905a-5378058fa1e8.jpeg)

But Netflix, YouTube, Browser and AppleTV are recognized after a short time (proper name and logo), turning TV on and off also works but with a big delay. Voice control with tiny.
TV has WiFi 5G Internet, no cable right now.

`app_list: '{"Netflix": "11101200001/org.tizen.netflix-app", "YouTube": "111299001912/9Ur5IzDKqV.TizenYouTube", "AppleTV": "com.samsung.tv.aria-video", "Browser": "org.tizen.browser"}'
`

**Comment by ollo69** [comment]
I don't use http post to launch the application but a dedicated ws. Anyway it is a common problem that some time is not possible to launch some application.
You should enable debug for the component in HA and share it so that I can see what is happening..

**Comment by Lemonadel** [comment]
Could you please guide me how to enable debug mode? I am using HA on HassIO (latest versions) and I have installed this component manually via git clone and moving folder to /config/custom_components path.
As a result this integration / component is not visible and I can only use it via configuration.yaml file.

**Comment by ollo69** [comment]
> Could you please guide me how to enable debug mode?

You should add the following line in `configuration.yaml`:

```
logger:
  default: info
  logs:
    custom_components.samsungtv_smart: debug
```

> I have tried to add repo to Configuration > Integrations but github address was not recognised as a correct repo (as it does with 99% of repos :) )

You mean using HACS? You don't need to add this component in HACS, is a default repository.

**Comment by Lemonadel** [comment]
Thank you. I have to update what I said. Somehow I was using wrong component (silly me).

But with yours I can switch to: Browser and Youtube. Netflix is choosen, recognised in HA as Netflix but nothing happens. I could only turn screen off, waking up even with mac written in settings (configuration.yaml). Audio controls are ok.

With integration installed from HACS I could not set up config properly, so I have installed it manually as mentioned previously.

Please find below a bit long log, where mostly around 3:08 I was trying to run every of app_list elements.
[Logs.txt.txt](https://github.com/ollo69/ha-samsungtv-smart/files/5744027/Logs.txt.txt)

**Comment by ollo69** [comment]
> With integration installed from HACS I could not set up config properly, so I have installed it manually as mentioned previously.

Can you explain better what was your problem installing from HACS and using Configuration Flow?

**Comment by KuChar91** [comment]
Hi 
I've just bought Samsung this year QE65Q80T model and apps don't show up. Is there any solution for this?

**Comment by ollo69** [comment]
> I've just bought Samsung this year QE65Q80T model and apps don't show up. Is there any solution for this?

I have a QE65Q82R that work perfectly. Provide more detail on the problem that you have configuring it. Best thing is open a new issue describing what happen.

**Comment by mbarnes106** [comment]
Issue trying to run curl:

{"code":404,"message":"Not found error.","status":404}
Mattb:~ mattbarnes$ curl -X POST -i 'http://192.168.1.138:8001/api/v2/applications/11101200001'
HTTP/1.1 404 Not Found
content-type: application/json; charset=utf-8
content-length: 55

{"code":404,"message":"Not found error.","status":404}

**Comment by mbarnes106** [comment]
But if i try:

curl -X POST -i 'http://192.168.1.138:8001/api/v2/applications/111299001912'

it loads Youtube just fine.

**Comment by KuChar91** [comment]
> I have a QE65Q82R that work perfectly. Provide more detail on the problem that you have configuring it. Best thing is open a new issue describing what happen.
You got last year tv. In this year Samsung probably changed sometings. I have the same problem as author of this post. Need to manually add applist i cfg.

**Comment by nomc2** [comment]
Same issue here with a QE55Q64TAUXZT bought a few days ago.
According to the debug log it looks like the app list is not returned after the request:
`2021-01-02 03:32:34 DEBUG (SamsungRemote) [custom_components.samsungtv_smart.api.samsungws] Message remote: received connect
2021-01-02 03:32:34 DEBUG (SamsungRemote) [custom_components.samsungtv_smart.api.samsungws] Request app list
2021-01-02 03:32:34 DEBUG (SamsungControl) [custom_components.samsungtv_smart.api.samsungws] Thread SamsungControl started
2021-01-02 03:32:34 DEBUG (SamsungArt) [custom_components.samsungtv_smart.api.samsungws] Thread SamsungArt started`

**Comment by speen** [comment]
I cannot get any apps either. Any other new suggestions? My config looks like this:
samsungtv_smart:
  - host: x.x.x.x
    mac: "xx:xx:xx:xx:xx"
    app_list: '{"Netflix": "11101200001/org.tizen.netflix-app}' (Tried other lists from above comments too)

**Comment by BaQs** [comment]
Hi there,
if it can be any help, same behaviour here: "request app list" in the logs, nothing in return.
Forcing app_list in configuration.yaml doesn't work at all.

curl http://xxx:8001/api/v2/

> {"device":{"FrameTVSupport":"true","GamePadSupport":"true","ImeSyncedSupport":"true","Language":"fr_FR","OS":"Tizen","PowerState":"on","TokenAuthSupport":"true","VoiceSupport":"true","WallScreenRatio":"0","WallService":"false","countryCode":"FR","description":"Samsung DTV RCR","developerIP":"0.0.0.0","developerMode":"1","duid":"uuid:a0dde8a0-x-xx44xxxe9-a1e4-xxxxxx","firmwareVersion":"Unknown","id":"uuid:a0dde8a0-b915-x-xxxxxxa1e4-x","ip":xxxxx"192.168.1.53","model":"20_NIKEM_FRAME","modelName":"QE55LS03TAUXXC","name":"[TV] TheFrame","networkType":"wireless","resolution":"3840x2160","smartHubAgreement":"true","ssid":"24:4b:fe:2e:12:05","type":"Samsung SmartTV","udn":"uuid:a0dde8a0-b915-44e9-a1e4-x","wifiMxxxxxac":"F4:FE:FB:B5:10:09"},"id":"uuid:a0dde8a0-b915-44e9-a1e4-x","isSxxxxxupport":"{\"DMP_DRM_PLAYREADY\":\"false\",\"DMP_DRM_WIDEVINE\":\"false\",\"DMP_available\":\"true\",\"EDEN_available\":\"true\",\"FrameTVSupport\":\"true\",\"ImeSyncedSupport\":\"true\",\"TokenAuthSupport\":\"true\",\"remote_available\":\"true\",\"remote_fourDirections\":\"true\",\"remote_touchPad\":\"true\",\"remote_voiceControl\":\"true\"}\n","name":"[TV] TheFrame","remote":"1.0","type":"Samsung SmartTV","uri":"http://192.168.1.xx:8001/api/v2/","version":"2.0.25"}

**Comment by ollo69** [comment]
Closing this issue 1 year old. Many TV do not return app list, this is not an integration issue. Integration allow manual app list creation as work around.

**Comment by Krocko** [comment]
Hi. I have the same problem with a QN800A.
