### ISSUE TITLE
Cannot cast media to 2023 tv?

### ISSUE THREAD

**Issue by LucasTor** [ollo69/ha-samsungtv-smart#272]
**Describe the bug**

After the TV is connected to home assistant, either with or without Samsung SmartThings, I cannot cast any media to my tv (cameras, static media provided by hass...), even though I can change the volume, turn it on and off, open youtube, netflix, etc...

**Expected behavior**
If applicable, a clear and concise description of what you expected to happen.

Once I try to cast media to my tv, I expect my tv to start playing it

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Armbian with Home Assistant dockerized
 - Home Assistant version installed: Home Assistant 2023.2.5
 - Component version installed: latest
 - Last know working version: ?
 - TV model: 55QN85B - 2023

**Output of HA logs**
Paste the relavant output of the HA log here.

```

```

**Additional context**

**Comment by LauBorch** [comment]
It is not working for me as well.

**Comment by LucasTor** [comment]
Still having the issue...

**Comment by LucasTor** [comment]
Any possible solutions to this problem? It kind of bothers me that I paid so much for a high end product that in theory would work with my home automation stuff and it does not

**Comment by jakelooker** [comment]
I'm experiencing the same issue on my S95B
