### ISSUE TITLE
Allow sending keys via the `remote` service

### ISSUE THREAD

**Issue by BadIdeasBureau** [ollo69/ha-samsungtv-smart#275]
**Is your feature request related to a problem? Please describe.**
Currently, sending keys to the TV invokes the media_player.playmedia service.  Several custom cards assume that such commands will be via the remote.send_command service (as it is on the integrated samsung tv integration, and as is expected by e.g. https://github.com/Nerwyn/android-tv-card )

**Describe the solution you'd like**
Allow remote.send_command to be used to send keycodes, so that:

```service: remote.send_command
target:
  device_id: foo
data:
  command:
    - KEY_CODE
```

functions equivalently to
```service: media_player.play_media
    data:
      entity_id: media_player.samsung_tv55
      media_content_id: KEY_CODE
      media_content_type: "send_key"
```

**Describe alternatives you've considered**
In all cases I've seen, manual configuration of the buttons which assume the use of the `remote` service is possible - it just adds an extra fiddly layer to getting something set up.

**Comment by ollo69** [comment]
Support for remote entity associated to device is available in last release. Please let me know if it works properly.

**Comment by rlust** [comment]
So far I have not any luck with the remote. It is unavailable.

**Comment by ollo69** [comment]
> So far I have not any luck with the remote. It is unavailable.

Can you be more clear? Do you have some error log?

**Comment by rlust** [comment]
> > So far I have not any luck with the remote. It is unavailable.
> 
> Can you be more clear? Do you have some error log?

Here is the error log when requesting remote to turn on:

This error originated from a custom integration.

Logger: custom_components.samsungtv_smart.media_player
Source: custom_components/samsungtv_smart/media_player.py:729
Integration: SamsungTV Smart (documentation, issues)
First occurred: November 3, 2023 at 7:29:49 PM (85 occurrences)
Last logged: 11:18:22 AM

media_player.bedroom_tv_samsungtv_smart - Error refreshing from SmartThings. Check connection status with TV on the phone App. Error: 500, message='Internal Server Error', url=URL('https://api.smartthings.com/v1/devices/4015a6e1-9dd6-4d39-b072-bd725a39ec2b/commands')
media_player.main_tv_samsungtv_smart - Error refreshing from SmartThings. Check connection status with TV on the phone App. Error: 500, message='Internal Server Error', url=URL('https://api.smartthings.com/v1/devices/0d4786b4-c6f1-4af3-816b-6047146116c8/commands')

**Comment by ollo69** [comment]
This error is just saying that your connection to SmartThings is not working, not that remote is not available.

**Comment by ollo69** [comment]
Close this as remote entity is implemented. Open new issue if you have problem with this.
