### ISSUE TITLE
Failed to call service media_player/turn_on. Incorrect MAC address format

### ISSUE THREAD

**Issue by vcxpz** [ollo69/ha-samsungtv-smart#29]
In the latest 2 releases (0.3.7 and 0.3.6, everything works in 0.3.5) whenever I try to turn on my Samsung 2017 Q7F (only this TV, tested others and they work) I get "Failed to call service media_player/turn_on. Incorrect MAC address format" in the bottom left of the screen. 
If I manually turn on the TV the status does not update at all from off with this specific TV
Running Latest Home Assistant Core in docker (0.112.4)

**Error Log:**

> Log Details (ERROR)
> Logger: homeassistant.components.websocket_api.http.connection.23432547509200
> Source: custom_components/samsungtv_smart/media_player.py:821
> Integration: Home Assistant WebSocket API (documentation, issues)
> First occurred: 10:06:09 AM (3 occurrences)
> Last logged: 10:08:38 AM
> 
> Incorrect MAC address format
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
>     connection.context(msg),
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in async_call
>     task.result()
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1295, in _execute_service
>     await handler.func(service_call)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
>     self._platforms.values(), func, call, required_features
>   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 454, in entity_service_call
>     future.result()  # pop exception if have
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 595, in async_request_call
>     await coro
>   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 485, in _handle_entity_call
>     await result
>   File "/config/custom_components/samsungtv_smart/media_player.py", line 826, in async_turn_on
>     await self.hass.async_add_executor_job(self._turn_on)
>   File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/samsungtv_smart/media_player.py", line 821, in _turn_on
>     send_magic_packet(self._mac)
>   File "/usr/local/lib/python3.7/site-packages/wakeonlan.py", line 74, in send_magic_packet
>     packet = create_magic_packet(mac)
>   File "/usr/local/lib/python3.7/site-packages/wakeonlan.py", line 38, in create_magic_packet
>     raise ValueError('Incorrect MAC address format')
> ValueError: Incorrect MAC address format

**Comment by ollo69** [comment]
Can you provide more info? How is your configuration? There are some information inside configuration.yaml?
Looking at the error it seems that MAC address is not correctly provided, but I change nothing about this in last version. If you rollback to 0.3.5, the integration still work?
Eventully are you able to enable and provide debug log?

**Comment by vcxpz** [comment]
there is nothing in my configuration.yaml to do with this integration. I setup using the integration in the webui and you can’t specify the MAC address. If I change nothing and simply reinstall backwards to 0.3.5 this issue does not happen. Upgrading back past 0.3.5 without changing any configurations it goes back to incorrect MAC address format. Not incorrect MAC address. Maybe something happened and it was rewritten as XX-XX-XX-XX instead of XX:XX:XX:XX or similar but I’m not sure. But this is a wake on lan error. It should not stop the TV information from updating if I were to turn it on with other means. Unless WOL is used to see if the tv is on. Is there any way to manually change the MAC address?

**Comment by vcxpz** [comment]
I did some looking around in the core.config_entries file and the TV that's having this problem has a mac address of "none" which I assume is why it's invalid.
FYI I did reinstall HACS, and this integration, and I believe it still failed to pull a mac address
Heres a snipped of the code:

```
            {
                "connection_class": "cloud_poll",
                "data": {
                    "api_key": "xxxxxxxxxxxxxxxxxxxxxxxxx",
                    "device_id": "xxxxxxxxxxxxxxxxxxxxxxxxx",
                    "device_model": "QA65Q7FAM",
                    "device_name": "[TV] Samsung Q7 Series (65)",
                    "device_os": "Tizen",
                    "host": "xxxxxxxxxxxxxxxxxxxxxxxxx",
                    "id": "xxxxxxxxxxxxxxxxxxxxxxxxx",
                    "mac": "none",
                    "name": "Living Room TV",
                    "port": 8002
                },
                "domain": "samsungtv_smart",
                "entry_id": "xxxxxxxxxxxxxxxxxxxxxxxxx",
                "options": {
                    "app_load_method": 3,
                    "power_on_delay": 30.0,
                    "use_st_channel_info": true,
                    "use_st_status_info": true
                },
                "source": "user",
                "system_options": {
                    "disable_new_entities": false
                },
                "title": "Living Room TV (SmartThings)",
                "unique_id": "xxxxxxxxxxxxxxxxxxxxxxxxx",
                "version": 1
            },
            {
                "connection_class": "cloud_poll",
                "data": {
                    "api_key": "xxxxxxxxxxxxxxxxxxxxxxxxx",
                    "device_id": "xxxxxxxxxxxxxxxxxxxxxxxxx",
                    "device_model": "UA43RU7100WXXY",
                    "device_name": "[TV] Samsung 7 Series (43)",
                    "device_os": "Tizen",
                    "host": "xxxxxxxxxxxxxxxxxxxxxxxxx",
                    "id": "xxxxxxxxxxxxxxxxxxxxxxxxx",
                    "mac": "XX:XX:XX:XX:XX:XX",
                    "name": "Master Bedroom TV",
                    "port": 8002
                },
                "domain": "samsungtv_smart",
                "entry_id": "xxxxxxxxxxxxxxxxxxxxxxxxx",
                "options": {},
                "source": "user",
                "system_options": {
                    "disable_new_entities": false
                },
                "title": "Master Bedroom TV (SmartThings)",
                "unique_id": "xxxxxxxxxxxxxxxxxxxxxxxxx",
                "version": 1
            }
```

**Comment by ollo69** [comment]
Can you try open in a browser this address: "http://<your-tv-ip>:8001/api/v2/"
Then let me know the information that you receive back, eventually post it here masking sensible information

**Comment by vcxpz** [comment]
Heres the output obvio:

`{"device":{"FrameTVSupport":"false","GamePadSupport":"true","ImeSyncedSupport":"true","OS":"Tizen","TokenAuthSupport":"true","VoiceSupport":"true","countryCode":"AU","description":"Samsung DTV RCR","developerIP":"0.0.0.0","developerMode":"0","duid":"uuid:<removed>","firmwareVersion":"Unknown","id":"uuid:<removed>","ip":"<removed>","model":"17_KANTM_UHD","modelName":"QA65Q7FAM","name":"[TV] Samsung Q7 Series (65)","networkType":"none","resolution":"3840x2160","smartHubAgreement":"true","type":"Samsung SmartTV","udn":"uuid:<removed>","wifiMac":"none"},"id":"uuid:<removed>","isSupport":"{\"DMP_DRM_PLAYREADY\":\"false\",\"DMP_DRM_WIDEVINE\":\"false\",\"DMP_available\":\"true\",\"EDEN_available\":\"true\",\"FrameTVSupport\":\"false\",\"ImeSyncedSupport\":\"true\",\"TokenAuthSupport\":\"true\",\"remote_available\":\"true\",\"remote_fourDirections\":\"true\",\"remote_touchPad\":\"true\",\"remote_voiceControl\":\"true\"}\n","name":"[TV] Samsung Q7 Series (65)","remote":"1.0","type":"Samsung SmartTV","uri":"http://<removed>:8001/api/v2/","version":"2.0.25"}`

**Comment by ollo69** [comment]
Ok, TV is not reporting the info.
The only option is to force the correct value adding this information in configuration.yaml as explained in readme. You need only to specify ip-address and mac, all other info remain unchanged, like this:

```
samsungtv_smart:
  - host: <YOUR TV IP ADDRESS>
    mac: <YOUR TV MAC>
```
