### ISSUE TITLE
Smartthings.md Instructions point to dead link

### ISSUE THREAD

**Issue by nosciencehere** [ollo69/ha-samsungtv-smart#290]
The URL https://graph-eu01-euwest1.api.smartthings.com/device/list on Samsungs site is no longer active. Been down for the last two days.

The instructions on this page are for setup when automatic detection of SmartThings device ID fails, section & page linked [here](https://github.com/ollo69/ha-samsungtv-smart/blob/master/docs/Smartthings.md#smartthings-device-id). 
I need to find my device ID some other way, can't seem to figure out how else to get it from SmartThings myself.

**Comment by nosciencehere** [comment]
A you can now obtain the ID from the following URL: https://my.smartthings.com/advanced/devices

Would recommend updating instructions

**Comment by ollo69** [comment]
Thanks, document updated.
