### ISSUE TITLE
Not working for (UE55)RU8000 series

### ISSUE THREAD

**Issue by unf0rg0tt3n** [ollo69/ha-samsungtv-smart#30]
**Is your feature request related to a problem? Please describe.**
I can add the TV, on/off not reporting correctly (WOL works only via smarthing, not with this integration)

**Describe the solution you'd like**
Support for the RU8000 series. WiFi WOL works for this TV, some sort of smartthings API thing?

**Comment by ollo69** [comment]
What does it means "WOL works only via smarthing, not with this integration"?

**Comment by unf0rg0tt3n** [comment]
It means that I can wake my TV using the smartthings app (even on wifi). But it won't work with any available integration. I also don't get the allow control popup it has to show.

**Comment by DavidHemsley** [comment]
My 7000 series doesn't turn on from smartthings but does from this addon.
I removed HA from external device manager on the TV, deleted the token, could not get it to reconnect.
I resolved the issue by removing the integration completely from HA and adding back in.
All is working correctly that way.

**Comment by unf0rg0tt3n** [comment]
> My 7000 series doesn't turn on from smartthings but does from this addon.
> I removed HA from external device manager on the TV, deleted the token, could not get it to reconnect.
> I resolved the issue by removing the integration completely from HA and adding back in.
> All is working correctly that way.

Tried that, doesn't work. It doesn't popup the allow connection screen. It shows that my TV is already on but the integration doesn't let me control it

**Comment by ollo69** [comment]
Did you check setting related to external devices?
On TV go to "menu -> general -> external device settings -> device connection" and in "Access notification" set "Only first time"

**Comment by unf0rg0tt3n** [comment]
> Did you check setting related to external devices?
> On TV go to "menu -> general -> external device settings -> device connection" and in "Access notification" set "Only first time"

Yeah it's enabled, still no pop-up :(

**Comment by ollo69** [comment]
Can you provide more deatil about your HA installation? Version, type, guest OS etc...

**Comment by unf0rg0tt3n** [comment]
arch | x86_64
-- | --
chassis | vm
dev | false
docker | true
docker_version | 19.03.8
hassio | true
host_os | HassOS 4.11
installation_type | Home Assistant OS
os_name | Linux
os_version | 5.4.50
python_version | 3.7.7
supervisor | 228
timezone | Europe/Amsterdam
version | 0.112.4
virtualenv | false

Networking:
Lan (vlan0): 192.168.1.0 <-- hassio is here
Wlan (vlan25): 192.168.25.0  <-- tv is here
IOT (vlan50): 192.168.50.0 <-- shelly, hue, blabla

**Comment by ollo69** [comment]
Docker / different subnet not work with ssl component. Check issue #5.

**Comment by unf0rg0tt3n** [comment]
> Docker / different subnet not work with ssl component. Check issue #5.

I made a reservation in the correct vlan to trial and error. I'll post the results tomorrow

**Comment by unf0rg0tt3n** [comment]
Unfortunately it doesn't work :(

**Comment by ollo69** [comment]
You should provide more details, as the HA log with the error and details about your configuration.

**Comment by unf0rg0tt3n** [comment]
> You should provide more details, as the HA log with the error and details about your configuration.

Which details of my setup do you need? I did post my system information. To add my tv I just go to the integrations menu and add: samsung tv smart (yours). It then gives me: unknown error occurred. Which log do you need? I can't find errors inside the supervisor, core, dns, etc. Logs also not in the main log under logs. Doesn't even come up.

**Comment by ollo69** [comment]
Enable HA debug log adding this line in configuration.yaml:

```
logger:
  default: info
  logs:
    custom_components.samsungtv_smart: debug
```

Are you totally sure that HA and the TV are in the same subnet?

**Comment by unf0rg0tt3n** [comment]
> Enable HA debug log adding this line in configuration.yaml:
> 
> ```
> logger:
>   default: info
>   logs:
>     custom_components.samsungtv_smart: debug
> ```
> 
> Are you totally sure that HA and the TV are in the same subnet?

not the same subnet anymore. But everything in my wlan or iot vlans can reach each other.
`2020-07-20 20:14:15 DEBUG (SyncWorker_3) [custom_components.samsungtv_smart] Try config with port: 8001
2020-07-20 20:14:15 DEBUG (SyncWorker_3) [custom_components.samsungtv_smart.api.samsungws] WS url ws://192.168.25.7:8001/api/v2/channels/samsung.remote.control?name=W0hvbWUgQXNzaXN0YW50XSB0dnNhbQ%3D%3D
2020-07-20 20:14:15 DEBUG (SyncWorker_3) [custom_components.samsungtv_smart.api.samsungws] Connection closed.
2020-07-20 20:14:15 DEBUG (SyncWorker_3) [custom_components.samsungtv_smart.api.samsungws] Connection closed.
2020-07-20 20:14:15 DEBUG (SyncWorker_3) [custom_components.samsungtv_smart] Failing config with port: 8001, error: {'event': 'ms.channel.unauthorized'}
2020-07-20 20:14:15 DEBUG (SyncWorker_3) [custom_components.samsungtv_smart] Try config with port: 8002
2020-07-20 20:14:15 DEBUG (SyncWorker_3) [custom_components.samsungtv_smart.api.samsungws] WS url wss://192.168.25.7:8002/api/v2/channels/samsung.remote.control?name=W0hvbWUgQXNzaXN0YW50XSB0dnNhbQ%3D%3D
2020-07-20 20:14:15 DEBUG (SyncWorker_3) [custom_components.samsungtv_smart.api.samsungws] Connection closed.
2020-07-20 20:14:15 DEBUG (SyncWorker_3) [custom_components.samsungtv_smart.api.samsungws] Connection closed.
2020-07-20 20:14:15 DEBUG (SyncWorker_3) [custom_components.samsungtv_smart] Failing config with port: 8002, error: {'event': 'ms.channel.timeOut'}`

The problem is that I don't see that pop-up altho I did set it up in my config
