### ISSUE TITLE
Cannot send notifications/text to TV

### ISSUE THREAD

**Issue by mathiar86** [ollo69/ha-samsungtv-smart#313]
**Describe the bug**
Using the "send text" command, I cannot send a notification to the Samsung Frame TV

**Expected behavior**
When the doorbell is pressed on my google battery doorbell, I want a notification to appear on my TV saying the doorbell has been pressed

**Screenshots**

<img width="466" alt="Screenshot 2024-05-09 at 8 53 26 pm" src="https://github.com/ollo69/ha-samsungtv-smart/assets/65014501/9d2cc0ca-1504-49d4-b379-346dab217fc2">

**Environment details:**
HASSIO installed on Intel N100 (Kamrui AK2)

When I run the automation through HA there are no errors in the logs when I click Traces but nothing appears on the TV at all.

**Comment by Bruhildo** [comment]
Have you seen this discussion?

https://github.com/ollo69/ha-samsungtv-smart/issues/106
