### ISSUE TITLE
URL will not play on Samsung frame tv

### ISSUE THREAD

**Issue by killervette42** [ollo69/ha-samsungtv-smart#315]
**Describe the bug**
I am trying to send a URL from my channels dvr which plays fine in a web browser to the Samsung tv. Nothing happens. 

home assistant source is Media player: Play media.
content id is the http url
content type is: url

log error just says Unsupported media type

**Comment by Andy-Richards** [comment]
Same fro me. Nothing in the debug logs however the browser and url do no open on the frame tv.
