### ISSUE TITLE
TV turning on by itself 

### ISSUE THREAD

**Issue by Antoni-Czaplicki** [ollo69/ha-samsungtv-smart#316]
**Describe the bug**
When this integration is enabled tv is being turned on randomly without any input.

**Expected behavior**
For tv to be off when it should be

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HA Supervisor 
 - Home Assistant version installed: 2024.5
 - Component version installed: v0.13.4
 - Last know working version: None
 - TV model: UE55CU7172UXXH

**Comment by SomeoneSinister** [comment]
I think I am having this problem too. I also have an issue where the integration thinks my tv turns on every 23 min for approximately 1 min, but it is infact off the whole time.
![Screenshot_20240601_223322_Home Assistant](https://github.com/ollo69/ha-samsungtv-smart/assets/92627190/4672d6d9-1953-4d7e-8524-d27222f087c2)
![Screenshot_20240601_223257_Home Assistant](https://github.com/ollo69/ha-samsungtv-smart/assets/92627190/3670b748-4060-445e-a81e-c4f105eb4b80)

**Comment by amroncz** [comment]
Hello,
What is the current status of this issue? My TV also switches itself on completely at random.

**Comment by amroncz** [comment]
When can we expect a fix for this issue or is there a workaround?

My TV comes on randomly and, unlike the previous poster, is actually on and doesn't go off again of its own accord a little later.


Here is some information:

TV:
Model: GQ55Q70RGTXZG
Software version: T-MSMDEUC-1420.0, B1970101/070404, BT-S

Integration version: 0.13.5

Version of Home Assistant (installed on a Raspberry Pi): 
Core: 2024.7.3
Supervisor: 2024.06.2
Operating System: 12.4
Frontend: 20240710.0

I have tested it both via WLAN and LAN.

In the TV's network settings, "Switch on with mobile device" and "IP remote access" are deactivated. "AnyNet+" is also switched off (I read somewhere that switching it off caused the TV to stop switching itself on)
