### ISSUE TITLE
Unable to complete configuration with an API key

### ISSUE THREAD

**Issue by fbutler** [ollo69/ha-samsungtv-smart#319]
**Describe the bug**
I am unable to complete configuration.

I enter the IP address of the TV, the name, and the API Key

I am then prompted to select the correct TV which I select and submit.

![image](https://github.com/ollo69/ha-samsungtv-smart/assets/1867723/90b33b4b-6c2e-4b22-a92a-b24df275b736)

The next screen shows a "SmartThings TV deviceID not found" error

![image](https://github.com/ollo69/ha-samsungtv-smart/assets/1867723/dc81bda4-a237-4454-bd1d-c4f36b26d4cd)

I enter the correct Device ID and submit it and the same "SmartThings TV deviceID not found" error screen is displayed

**Expected behavior**
Complete configuration successfully after entering the required details 

**Screenshots**
Screenshots embedded above

**Environment details:**
Core 2024.6.2
Supervisor 2024.06.0
Operating System 12.3
Frontend 20240610.0
TV Model: UE43TU8000KXXU

**Output of HA logs**
This error originated from a custom integration.

Logger: custom_components.samsungtv_smart
Source: custom_components/samsungtv_smart/__init__.py:431
integration: SamsungTV Smart (documentation, issues)
First occurred: 11:16:44 (3 occurrences)
Last logged: 11:22:10

Connection to SmartThings TV not available.

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:184
First occurred: 11:10:05 (3 occurrences)
Last logged: 11:16:15

Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 630: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues
Detected that custom integration 'samsungtv_smart' accesses hass.helpers.aiohttp_client. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from aiohttp_client directly at custom_components/samsungtv_smart/config_flow.py, line 200: session = self.hass.helpers.aiohttp_client.async_get_clientsession(), please create a bug report at https://github.com/ollo69/ha-samsungtv-smart/issues

**Additional context**
My VPN was disabled when attempting configuration

**Comment by Kahera** [comment]
Same issue here. Additional information - this is the only thing that shows up that seems relevant in my logs: 
```
This error originated from a custom integration.

Logger: custom_components.samsungtv_smart
Source: custom_components/samsungtv_smart/__init__.py:443
integration: SamsungTV Smart (documentation, issues)
First occurred: 19:00:03 (3 occurrences)
Last logged: 19:00:57

Connection to SmartThings TV not available.
```
(I did attempt 3 times this go around). 

When entering the deviceID I do get the popup on my screen asking to approve the connection, but it fails even on accept (but after a short wait, as if it's trying to connect). It immediately fails as expected when I try to deny the connection.

**Comment by plimo** [comment]
Same issue as described by @Kahera also here.

**Comment by D4rk3rd** [comment]
What worked for me was removing the device from SmartThings entirely and re-adding it. After the device worked perfectly.

**Comment by CookieChief** [comment]
I have the same issue and could not resolve it by deleting and readding the component.
