### ISSUE TITLE
Device won't stay in the one state

### ISSUE THREAD

**Issue by phoniclynx** [ollo69/ha-samsungtv-smart#32]
**Describe the bug**
When the TV is physically on, HA recognises it as on but after a few seconds, it displays it as off. It won't accept any commands during the time it is listed as off when the TV is on. So if you leave the TV on and an automation script turns it off and the plugin is displaying the TV is off (when it's actually on) the script won't power off the TV.

**Expected behavior**
The script should know the TV is on whenever the TV is on

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HASSIO
 - Home Assistant version installed: 0.113.3
 - Component version installed:0.3.7
 - Last know working version:
 - TV model:

**Comment by ollo69** [comment]
This is probably caused by another change in SmartThings. With last release should be fixed, but now to have SmartThings feature working you need to open sometimes SmartThings app on the phone or the SmartThings status will become "disconnected because unused from long time"

**Comment by phoniclynx** [comment]
OK.. so I started up SmartThings on the TV and it seems to be working as expected now

**Comment by majkers** [comment]
Nów it happens to me. In 0.3.8 version without SmartThings. Before it was ok. My tv status changes to off and it it is not cause I am still wztching it...

**Comment by ollo69** [comment]
Does it work previous release? If yes install that and wait foe new one on next days. Determinate real-on from fake-on on Samsung TV is quite complex and different from model to model...

**Comment by majkers** [comment]
Yes. I have installed 0.3.7 again and wait for a new version.
