### ISSUE TITLE
[FR] Use instance name as identification

### ISSUE THREAD

**Issue by chemelli74** [ollo69/ha-samsungtv-smart#33]
**Describe the bug**
Plugin present itself as "HomeAssistant" when asking for connection authorization on the TV.
As I'm running more than 1 instance of HA, I get a lot of extra confirmation on the TV at each HA restart.

**Expected behavior**
Would be nice if the instance name is used instead of a fixed name.

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Docker
 - Home Assistant version installed: 0.133.3
 - Component version installed: v0.3.9
 - Last know working version: -
 - TV model: QE55Q85RATXZT

**Output of HA logs**
Paste the relevant output of the HA log here.

```
none
```

**Additional context**

**Comment by ollo69** [comment]
Your request is clear, I worried that changing this all user will receave a new authentication confirmation that can cause confusion. What kind of name do you propose? Can you make some example?

**Comment by chemelli74** [comment]
I would propose to use "HomeAssistant - {name of your HA installation".
For me would be "HomeAssistant-Home-Test":

![image](https://user-images.githubusercontent.com/57354320/89878214-87b24600-dbc1-11ea-8034-8166600ce557.png)

You can always set the new name only if the name of HA installation was changed from default.
As last option, you can consider to add a flag to activate the new naming.

Simone

**Comment by ollo69** [comment]
Not sure how to fetch this info, but I think is not complex.
I agree with the flag, to be added on initial config flow, this will avoid issue on existing installation.
Will update this issue when new release will be ready.

**Comment by chemelli74** [comment]
> Not sure how to fetch this info, but I think is not complex.

https://github.com/home-assistant/core/blob/f286992b1007588ae1221352883259393947fdfe/homeassistant/config.py#L495

Simone

**Comment by ollo69** [comment]
The FR is now available with last release. Can you please try and report your feedback?

**Comment by chemelli74** [comment]
Hi, just arrived back home and tested latest release.

Even if the pop-up shows the instance name, then in the allowed device list of the TV I see only 1 device named "**[Home Assistant] SamsungTV**"(last part is the name I assigned to the entity).

I thing the way to go is to change the first part to make because this is the info device list relies on.

Simone

**Comment by ollo69** [comment]
You must remove component configuration and re-configure it.
It also better that you previously delete the exixtsing permission on the TV. 
If you use instance name friendly name is not used at all!

**Comment by chemelli74** [comment]
Hi,

what I did was:

- update compoment to latest
- remove cfg
- remove all TV auth
- add cfg with

![image](https://user-images.githubusercontent.com/57354320/90343859-b0e53300-e014-11ea-942b-76bf0af718c3.png)

I still see only 1 name (may come from prod isntance) but nothing else.

Simone

**Comment by ollo69** [comment]
You never see the permission popup on the TV when you click submit? If not, try rebooting your HA instance and power off and on the TV, then try reconfigure it.

**Comment by chemelli74** [comment]
I fear to have not explained the issue well :-(

Prod ( still running v0.3.9:

![image](https://user-images.githubusercontent.com/57354320/90344772-32d95a00-e01d-11ea-83fa-87d3ef8d6b78.png)


Test ( running v0.3.10 and with the new box for instance name ticked):

![image](https://user-images.githubusercontent.com/57354320/90344767-235a1100-e01d-11ea-9c8f-44baad0cce38.png)

As you can see the part between square is the same and instead needs to be different.
The name after is the entity name and this can already be specified thus be different between one and the other, but it's not enough.

Let me know if now is more clear.

Thank you for you time and help.

Simone

**Comment by ollo69** [comment]
Why is not enough? The TV is not considering the whole name?

**Comment by chemelli74** [comment]
Seems not, otherwise I would have solved the issue with old version ;-)
As the name before this issue as formed by "[Home Assistant] Entity name".

Simone

**Comment by chemelli74** [comment]
Worked a lot on this issue and I fear we cannot do much :-(
Seems TV store source ip or mac or both and not the string identification passed over by this integration.

As I'm running on Docker, both containers have the same network details.

Simone

**Comment by ollo69** [comment]
Oh, yes, very probably. I'm also surprised that it work for you inside a docker, in most case websocket connection fail.
I think that there is nothing more that I can do, if you don't have any suggestion please close the issue.

**Comment by chemelli74** [comment]
Seems another conflict comes from default integration (zeroconf working again with recently developed PR).

Is there a way to reuse/share the auth token ?

Simone

**Comment by ollo69** [comment]
Wait, may be is because I store the token based on the IP? Do you have in the integration folder the file "token-<ip_address>.txt?
Does it contain same value for both installation?

**Comment by chemelli74** [comment]
> Do you have in the integration folder the file "token-<ip_address>.txt?

Yes, for both install.

> Does it contain same value for both installation?

Nope, value differ.

Simone

**Comment by ollo69** [comment]
Please retry with last release. May be I found a wrong processing of connect message that could assign wrong authentication token

**Comment by chemelli74** [comment]
I'm away from home for vacation for 2 weeks. Will report once back.

Simone

**Comment by chemelli74** [comment]
Unfortunately nothing we can do to fix this issue: root cause is having 2 containers on docker with `--net=host` so the requests looks like coming from the same device.

Simone
