### ISSUE TITLE
KEY_GAME does not work 

### ISSUE THREAD

**Issue by joeminalt** [ollo69/ha-samsungtv-smart#334]
I believe I have my intergration configured correctly. I can use features like KEY_MENU and the navigation keys just fine. However, KEY_GAME does not work along with the picture mode keys. I have a Samsung QN75QN90BAFXZA

**Comment by bigdogevan** [comment]
https://github.com/ollo69/ha-samsungtv-smart/issues/333#issuecomment-2449261442

I just posted this, also might help you for picture modes.
