### ISSUE TITLE
[BUG] Mute not honored if done before starting HA

### ISSUE THREAD

**Issue by chemelli74** [ollo69/ha-samsungtv-smart#34]
**Describe the bug**
If TV is switched on and muted before HA starts, the mute status is not synced.

**Expected behavior**
Sync mute status with SmartThings.

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Docker
 - Home Assistant version installed: 0.133.3
 - Component version installed: v0.3.9
 - Last know working version: - 
 - TV model: QE55Q85RATXZT

**Output of HA logs**
Paste the relevant output of the HA log here.

```
none
```

**Additional context**

**Comment by ollo69** [comment]
This is due to a new feature that use mute status to detect fake power on. If you don't like you can disable the feature using component option from webui, more details are in readme.

**Comment by chemelli74** [comment]
Disabled, let's see if it was the guilty one.

I would say that this options should be disabled when SmartThings integration is active; the mute/unmute state can be fetched from there.
Am I wrong ?

Simone

**Comment by ollo69** [comment]
SmartThings is unreliable and volume / mute info are often wrong. The only real reliable information, till now, is the used input, so I cannot use SmartThings for this.

I think I can add an additional control to ignore the mute check during start-up, I will think about this....

**Comment by chemelli74** [comment]
> SmartThings is unreliable and volume / mute info are often wrong. The only real reliable information, till now, is the used input, so I cannot use SmartThings for this.
> 

Interesting, because when I mute trough the original remote I get the status updated in HA.
This is why I though you already read it from SmartThings, but not during startup.

Simone

**Comment by ollo69** [comment]
volume and mute info are always retrieved from upnp.
I also reviewed the code at startup and it should not have any issue also in case of muted TV. Probably this issue is directly connected to the FR #33 because you have multiple instance of HA.

**Comment by chemelli74** [comment]
> volume and mute info are always retrieved from upnp.
> I also reviewed the code at startup and it should not have any issue also in case of muted TV. Probably this issue is directly connected to the FR #33 because you have multiple instance of HA.

If the value is read from upnp, should not matter how many instances I have, all get the same info. Isn't it ?

Simone

**Comment by ollo69** [comment]
If it fail to start it never reach the point. Not clear how long the mute status stay "not synced" after startup, can you clarify?

**Comment by chemelli74** [comment]
> If it fail to start it never reach the point. Not clear how long the mute status stay "not synced" after startup, can you clarify?

Mute after startup can be synced only toggling mute button on remote or HA media_player.
Will retest later on if needed.

Simone

**Comment by chemelli74** [comment]
Seems that a hard reset of the TV aligned the status. Now it takes 3 to 5 seconds to sync.

Sorry for the false report.

Simone

**Comment by ollo69** [comment]
Closing this issue.
