### ISSUE TITLE
Netflix App Won't Open

### ISSUE THREAD

**Issue by josiamichael** [ollo69/ha-samsungtv-smart#35]
Hi there,

I just did a clean install of ha-samsungtv-smart through HACS to my HA to control my Samsung TU8500 TV.
The problem i found is I can't launch Netflix through my source tab in my HA instance.

For additional information, everything else works fine. I configure the `app_list` manually in my `configuration.yaml` just like the instructions told me and when I open Netflix manually through my remote, in my HA it would say Netflix, but I'm unable to change source through Netflix through HA. Other apps like YouTube and Spotify that I also configure manually in the `app_list` works fine.

If there is anything you need, please let me know. I'm sorry for my lack of understanding since I'm pretty new to these things.

**Comment by DavidHemsley** [comment]
Did you let it create the list for you initially as it can?
You should only need to create it manually if the automatic list doesn't work for you
Sounds like you have a typo in the app, as I use HA to switch to Netflix and other Apps successfully.

**Comment by ollo69** [comment]
Provide additional detail on your configuration and share your app_list here.
Are you using SmartThings?

**Comment by josiamichael** [comment]
@DavidHemsley intially I let it create the list automatically, but it didn't detect any of my apps so I decided to input the `app_list` manually in the HA configuration. I have double checked and I didn't have any typo on my configuration.

Also as a side note, my TV used `org.tizen.netflix-app` I knew it since it was showing up on the source in HA when I turn on netflix manually on my TV.

**Comment by josiamichael** [comment]
@ollo69 

Here is the manual configuration I put on my `configuration.yaml` in HA

`#Samsung TV Integration
samsungtv_smart:
  - host: 192.168.1.209
    source_list: '{"TV": "ST_TV", "TV Box": "ST_HDMI1", "Soundbar": "ST_HDMI2", "Playstation 4": "ST_HDMI3"}'
    app_list: '{"Netflix": "org.tizen.netflix-app", "YouTube": "9Ur5IzDKqV.TizenYouTube", "Spotify": "rJeHak5zRg.Spotify"}'`

Yes, I'm using SmartThings and my initial configuration was using the WebUI and I have put on my SmartThings API Key there.

Also as a side note, all apps & sources are working fine. The only problem I was facing was only the Netflix App and I still can't figure out why

**Comment by ollo69** [comment]
It is better to also use the numeric appID in the list for launching the app, so correct your list as following:

```
app_list: '{"Netflix": "11101200001/org.tizen.netflix-app", "YouTube": "111299001912/9Ur5IzDKqV.TizenYouTube", "Spotify": "rJeHak5zRg.Spotify"}'
```

I don't have the numeric id for spotify, but you should be able to retrieve it from the file `applist-<your-ip>.txt` generated in the custom component folder.

Please id this solve your problem remember to close the issue.

**Comment by josiamichael** [comment]
@ollo69 thanks for the help, but unfortunately adding the numeric AppID in my `app_list` doesn't have any impact. My Netflix still won't open but other apps still works fine (YouTube and Spotify).

**Comment by ollo69** [comment]
I need your HA log with debug enabled to investigate.
Add this lines in configuration.yaml to enable debug:

```
logger:
  default: info
  logs:
    custom_components.samsungtv_smart: debug
```

After using the component with debug enabled, post your log file here.

**Comment by josiamichael** [comment]
@ollo69 

Here is my Home Asssitant log file. Hope this helps

[debuglog.txt](https://github.com/ollo69/ha-samsungtv-smart/files/5070511/debuglog.txt)

From what I can read is SmartThings spitting 404 error everytime I open up Netflix but I'm not sure why since it's the same id that my TV displays when Netflix isn't on the `app_list`

**Comment by ollo69** [comment]
This is because the component is still using the text `org.tizen.netflix-app` AppID and not  the numeric ones, are you sure that you changed the app_list as I suggest and than reboot HA?
The component is displaying correct running app because SmartThings is providing this info, but for launching application the WS channel is used and it must use the numeric AppID.
Please correct the app-list and provide updated log if still not working.

**Comment by DavidHemsley** [comment]
Here are the AppIDs for the main ones on mine which may be of use to you
'YouTube': '111299001912/9Ur5IzDKqV.TizenYouTube', 'Netflix': '11101200001/org.tizen.netflix-app', 'Disney+': '3201901017640/MCmYXNxgcu.DisneyPlus', 'Prime Video': '3201512006785/org.tizen.ignition', 'Spotify - Music and Podcasts': '3201606009684/rJeHak5zRg.Spotify'

**Comment by josiamichael** [comment]
@ollo69 
My bad, I revert my `app_list` configuration to my original configuration before logging the debuglog that I sent.

Here is my debuglog with the numeric AppID and the result is the same, YouTube and Spotify works but Netflix still doesn't work.

[debuglog.txt](https://github.com/ollo69/ha-samsungtv-smart/files/5072607/debuglog.txt)

**Comment by ollo69** [comment]
Ok, so this is really strange.
May be you can try to re-install Netflix app on TV and also power cycle it, if you don't already did.

**Comment by josiamichael** [comment]
@ollo69 

I tried to uninstall Netflix on my TV but it won't let me (I believe its because Netflix was a default app that come with the TV) but I manage to Re-Install it and do a power cycle on my TV. The results are still the same it still gives me 404 error on my HA log.

**Comment by ollo69** [comment]
Yes, re-install is the only option, Sorry but at this moment I have no other idea, I will think if there are possible alternative...

**Comment by ollo69** [comment]
Honestly I don't think this will solve the issue, anyway install last release and try to call the services `media_player.play_media:` with this parameters:

- Test 1
```
entity_id: media_player.tv_sala
media_content_id: "app"
media_content_type: 11101200001,DEEP_LINK
```

- Test 2
```
entity_id: media_player.tv_sala
media_content_id: "app"
media_content_type: 11101200001,NATIVE_LAUNCH
```

and let me know if any of this 2 test launch Netflix app on TV

**Comment by DavidPper** [comment]
Hello, Im having the same issue.
All other apps and sources will open from Home Assistant except for Netflix. If i run Netflix by selecting on the tv it shows up in Home Assistant.
Just out of curiosty, my remote has a dedicated Netflix button, would the tv have a dedicated KEY and if so how could i find what that KEY is.

Regards 
David

**Comment by josiamichael** [comment]
> Hello, Im having the same issue.
> All other apps and sources will open from Home Assistant except for Netflix. If i run Netflix by selecting on the tv it shows up in Home Assistant.
> Just out of curiosty, my remote has a dedicated Netflix button, would the tv have a dedicated KEY and if so how could i find what that KEY is.
> 
> Regards
> David

I'm still using the integration until now and I still haven't found the solution to this problem unfortunately. Do you have the samsung one remote ? if yes i believe it is using bluetooth to connect to the tv and therefore the KEY feature can't be used since it has no registers netflix KEY. CMIIW

**Comment by DavidPper** [comment]
> > Hello, Im having the same issue.
> > All other apps and sources will open from Home Assistant except for Netflix. If i run Netflix by selecting on the tv it shows up in Home Assistant.
> > Just out of curiosty, my remote has a dedicated Netflix button, would the tv have a dedicated KEY and if so how could i find what that KEY is.
> > Regards
> > David
> 
> I'm still using the integration until now and I still haven't found the solution to this problem unfortunately. Do you have the samsung one remote ? if yes i believe it is using bluetooth to connect to the tv and therefore the KEY feature can't be used since it has no registers netflix KEY. CMIIW

I Have the BN5901329C Remote

![BN5901329C Samsung Remote](https://user-images.githubusercontent.com/74324551/99139162-9447ae00-268a-11eb-9843-09f8962c4369.jpg)

**Comment by josiamichael** [comment]
> > > Hello, Im having the same issue.
> 
> > > All other apps and sources will open from Home Assistant except for Netflix. If i run Netflix by selecting on the tv it shows up in Home Assistant.
> 
> > > Just out of curiosty, my remote has a dedicated Netflix button, would the tv have a dedicated KEY and if so how could i find what that KEY is.
> 
> > > Regards
> 
> > > David
> 
> > 
> 
> > I'm still using the integration until now and I still haven't found the solution to this problem unfortunately. Do you have the samsung one remote ? if yes i believe it is using bluetooth to connect to the tv and therefore the KEY feature can't be used since it has no registers netflix KEY. CMIIW
> 
> 
> 
> I Have the BN5901329C Remote
> 
> 
> 
> ![BN5901329C Samsung Remote](https://user-images.githubusercontent.com/74324551/99139162-9447ae00-268a-11eb-9843-09f8962c4369.jpg)
> 
> 

yep, i have the exact same remote as that and as far as i know the remote uses bluetooth for the Netflix button and so the Netflix button isn't registered in the KEY features since it is only IR Keys that are registered there and currently i haven't found solution on how to duplicate that netflix button on the remote

**Comment by DavidPper** [comment]
Just noticed im having the same issue with prime video

**Comment by mbarnes106** [comment]
I  have the exact same issue. everything works apart from Netflix.

`samsungtv_smart:
  - host: 192.168.1.138
    app_list: '{"Netflix": "11101200001/org.tizen.netflix-app"   , "Plex": "3201512006963", "YouTube": "111299001912",  "Prime Video" : "3201512006785", "Spotify": "3201606009684", "Internet": "org.tizen.browser" }'`

**Comment by mbarnes106** [comment]
Tried it without the /org.tizen.netflix-app too, still doesn't work for me

**Comment by mbarnes106** [comment]
Is there anything I can do to help with this issue, logs or anything I can provide?

**Comment by simoa** [comment]
Hi, anyone with the new Samsung tv 2020 is able to run this please ? I think I have found a solution

(Open Netflix)
curl -X POST -i 'http://IP:8001/api/v2/applications/11101200001'

**Comment by mbarnes106** [comment]
Ooh how do you add this? Just that link?

**Comment by simoa** [comment]
@mbarnes106  Can you please simply launch this on your browser http://IP:8001/api/v2/applications/11101200001 replace IP with your current TV IP Address. Thanks very much

**Comment by Ernie11** [comment]
Hello,

I have the same issue. I only have problems with Netflix, everything else works. @simoa, I have tried your url but got an error on the json return. It says code: 404, message: "Not found error.", and status: 404. But I tried using 111299001912, which is youtube, and got the json information correctly. id, name, running, version, visibility all has information. I then tried using RN1MCdNq8t.Netflix and org.tizen.netflix-app but both game the 404 error I initially got from 11101200001.

**Comment by simoa** [comment]
@Ernie11 Thanks so much. So if you test the links below all good?

(Open YouTube)
curl -X POST -i 'http://IP:8001/api/v2/applications/111299001912'

(Open Prime)
curl -X POST -i 'http://IP:8001/api/v2/applications/3201512006785'

(Open browser)
curl -X POST -i 'http://IP:8001/api/v2/applications/org.tizen.browser'

Thanks very much

**Comment by mbarnes106** [comment]
I’m being really slow I am afraid but want to test these tonight. What do you mean put them in your browser though?

**Comment by simoa** [comment]
They need to be executed using a terminal with your TV on so we can make sure that it open the apps on the new Samsung. Thank you

**Comment by mbarnes106** [comment]
Sorry, so I can enter that link with my ip into the browser bar if safari on a Mac on my network you mean and see what happens?

**Comment by simoa** [comment]
@mbarnes106 if you don't know how to launch a terminal you can simply enter these on your browser

http://IP:8001/ws/apps/Netflix
http://IP:8001/api/v2/applications/org.tizen.browser
http://IP:8001/api/v2/applications/3201512006785
http://IP:8001/api/v2/applications/111299001912

Replace IP wth your TV IP. 

Thanks

**Comment by ollo69** [comment]
If open application with the method mentioned above fix your issue, with last integration version you can enable this method in integration options selecting `Rest API Call` for the option `Applications launch method`. You can also try the option `Remote Web Socket Channel` as alternative.

**Comment by mbarnes106** [comment]
Netflix still not working, but the curl commands work for youtube etc.

Looks like its just impossible to load Netflix



Mattb:~ mattbarnes$ curl -X POST -i 'http://192.168.1.138:8001/api/v2/applications/111299001912'
HTTP/1.1 200 OK
content-type: application/json; charset=utf-8
content-length: 5

true
Mattb:~ mattbarnes$ curl -X POST -i 'http://192.168.1.138:8001/ws/apps/Netflix'
HTTP/1.1 401 Unauthorized
content-type: application/json; charset=utf-8
content-length: 29

<html><body>401</body></html>Mattb:~ mattbarnes$

**Comment by nomc2** [comment]
Looks like some of the codes for the applications have changed.
I was having the same issue so I used Tizen Studio to retrieve the webapp list from my tv (2020 QE55Q64TAUXZT) in developer mode.
Below is what I got for Netflix and Prime Video, setting them in my `configuration.yaml` fixed the issue for me and now I can succesfully open Netflix and Prime Video through the integration:

```
[ 1 - Netflix]
- App Name                            :     Netflix
- App Version                         :     5.2.550
- App ID - WAS                        :     3201907018807
- App ID - Tizen                      :     org.tizen.netflixapp
-----------------------------------------------------------------------------------------------------
[ 2 - Prime Video]
- App Name                            :     Prime Video
- App Version                         :     2.01.23
- App ID - WAS                        :     3201910019365
- App ID - Tizen                      :     org.tizen.primevideo
```

YMMV though, as it looks like the codes might be different between versions of the same app.

**Comment by mbarnes106** [comment]
Do you have an example of what you put in your actual config yaml file?

**Comment by nomc2** [comment]
> Do you have an example of what you put in your actual config yaml file?

Here you go:
```
samsungtv_smart:
  - host: <MY_TV_IP_ADDRESS>
    app_list: '{"Netflix": "3201907018807/org.tizen.netflixapp", "Prime Video": "3201910019365/org.tizen.primevideo", "YouTube": "111299001912/9Ur5IzDKqV.TizenYouTube"}'
```

**Comment by ollo69** [comment]
@nomc2, good catch.
Did you change something at integration options or you leave all default?

**Comment by nomc2** [comment]
> @nomc2, good catch.
> Did you change something at integration options or you leave all default?

I did change the `Application Launch Method` to` REST API Call` a few days ago during my tests and never reverted it back, so this works for sure in my TV.
I have just tested reverting it back to `Standard WebSocket Channel` and it works as well.

**Comment by KuChar91** [comment]
@nomc2 how did you retrieved all apps form tv?

**Comment by nomc2** [comment]
> @nomc2 how did you retrieved all apps form tv?

I used the Samsung Tizen SDK and the TV in Developer Mode:
- Download and install Tizen Studio, the SDK (TV Extensions included) as outlined here https://developer.samsung.com/smarttv/develop/getting-started/setting-up-sdk/installing-tv-sdk.html
- Put my TV in Developer Mode and connected to it as outlined here https://developer.samsung.com/smarttv/develop/getting-started/using-sdk/tv-device.html
- I also created a Certificate Profile in Tizen Studio, but not sure it is necessary
- In Tizen Studio Device Manager, right clicked on the entry for the TV and selected `Installed Web App List` in the drop down menu.
That returned me the list of all the Web Apps installed on my TV and for each of them you can find the code as `App ID - WAS` 

It is convoluted but it was the only foolproof way to get the app list as for some reason the integration does not seem to be able to generate it in my TV.

**Comment by Ernie11** [comment]
Hello.

Good find @nomc2. Works for me now. Thanks!

**Comment by mbarnes106** [comment]
Me too @nomc2  thank you!

ps anyone else find it’s probably around 10 seconds from changing source before it shows the new source in HA etc? Anyway to speed this up?

**Comment by 9magic** [comment]
Hi,

I have samsung TU7172 from 2020.
I got select input for apps working by creating list in yaml.

```
samsungtv_smart:
  host: 192.168.0.118
  app_list: '{"Netflix": "3201907018807/org.tizen.netflix-app", "YouTube": "111299001912/9Ur5IzDKqV.TizenYouTube", "EON": "IaJ5S3D7jQ.Eon"}'
```
I had to use the new id for Netflix you provided. Thank you.
I don't have applist-<your-ip>.txt and the list is not created automatically.

I also really want to get app id for this app of mine EON. I tried to follow your way, @nomc2 but with no success yet. I don't have "Installed Web App List" in device manager.

![image](https://user-images.githubusercontent.com/20966412/104236582-0fdd9580-5457-11eb-9df3-30d60c96b074.png)

**Comment by nomc2** [comment]
> Hi,
> 
> I have samsung TU7172 from 2020.
> I got select input for apps working by creating list in yaml.
> 
> ```
> samsungtv_smart:
>   host: 192.168.0.118
>   app_list: '{"Netflix": "3201907018807/org.tizen.netflix-app", "YouTube": "111299001912/9Ur5IzDKqV.TizenYouTube", "EON": "IaJ5S3D7jQ.Eon"}'
> ```
> 
> I had to use the new id for Netflix you provided. Thank you.
> I don't have applist-.txt and the list is not created automatically.
> 
> I also really want to get app id for this app of mine EON. I tried to follow your way, @nomc2 but with no success yet. I don't have "Installed Web App List" in device manager.
> 
> ![image](https://user-images.githubusercontent.com/20966412/104236582-0fdd9580-5457-11eb-9df3-30d60c96b074.png)

Did you install the TV Extensions for the SDK? I had the same issue before installing them and restarting Device Manager

**Comment by 9magic** [comment]
@nomc2 thank you again. I guess I was missing them and I only had TV Extensions Tools.
Now I also have TV Extensions-6.0 and Samsung Certificate Extension. Didn't have to create certificate though to see Installed Web App List now.
I had many problems with Package manager and I would give up if you had not asked me about TV Extensions again and shared your experience:)

**Comment by dgthomson** [comment]
There are some recent app IDs [here](https://github.com/tavicu/homebridge-samsung-tizen/issues/291#issuecomment-759944399).

**Comment by swisschris104** [comment]
Can confirm that "Netflix": "3201907018807" seemed to work for me too

**Comment by gody93** [comment]
Also mine Netflix app didnt work with the example in the Readme. Not with numeric and/or alphabetic variants, but it worked with "Netflix": "3201907018807. Maybe it would be a good idea to change it/ add it in the description.

**Comment by mendoncart** [comment]
Thanks @gody93 ! This list works for my TV.
If anyone still don't know how to use the command, you need to call this service:
```
service: media_player.play_media
data:
  media_content_id: 3201907018807
  media_content_type: app
target:
  entity_id: media_player.YOUR_TV_ENTITY
```
If there is a easier way, please let me know.

**Comment by jk7gr** [comment]
> Hi,
> 
> I have samsung TU7172 from 2020. I got select input for apps working by creating list in yaml.
> 
> ```
> samsungtv_smart:
>   host: 192.168.0.118
>   app_list: '{"Netflix": "3201907018807/org.tizen.netflix-app", "YouTube": "111299001912/9Ur5IzDKqV.TizenYouTube", "EON": "IaJ5S3D7jQ.Eon"}'
> ```
> 
> I had to use the new id for Netflix you provided. Thank you. I don't have applist-.txt and the list is not created automatically.
> 
> I also really want to get app id for this app of mine EON. I tried to follow your way, @nomc2 but with no success yet. I don't have "Installed Web App List" in device manager.
> 
> ![image](https://user-images.githubusercontent.com/20966412/104236582-0fdd9580-5457-11eb-9df3-30d60c96b074.png)

Hi 9magic,
did you manage to get the AppID for EON. I am also looking for CosmoteTV. Maybe you can help?

Thanks man!

**Comment by 9magic** [comment]
Hi,

Yes! I managed to do it. I followed his guide and hints.
https://github.com/ollo69/ha-samsungtv-smart/issues/35#issuecomment-755630610

Sorry later I uninstalled Tizen Studio because I used it only that one time. If I understand correct you are looking for id of different app. In case anyone needs EON app id it is:
"EON": "3201704012154/IaJ5S3D7jQ.Eon"

**Comment by Kraxus998** [comment]
hi, can some one helpme to find a Release version of the Netflix App, im trying to  install it with sdk tizen but i dont have a valid build

**Comment by mirroringcontact** [comment]
Hi. How to launch youtube **with videoId** or browser **with url**  via post request? Any parameters or what?
curl -X POST -i 'http://ip:8001/api/v2/applications/11101200001'
