### ISSUE TITLE
Add media playback status

### ISSUE THREAD

**Issue by WarDrake** [ollo69/ha-samsungtv-smart#37]
**Is your feature request related to a problem? Please describe.**
There is no way to know if the tv is playing something while in an app or just idle in the app, ex. Am I playing something on netflix, or browsing it?

**Describe the solution you'd like**
Adding a playback status to the entity when an app is open, playing, paused, idle, unavailable (while not in an app)

**Describe alternatives you've considered**

**Additional context**

**Comment by ollo69** [comment]
It's not possible because this information is not available

**Comment by WarDrake** [comment]
Ah, I see, that's unfortunate, thanks for the information.
