### ISSUE TITLE
Unsupported _ST source. You must configure SmartThings

### ISSUE THREAD

**Issue by Audiothor** [ollo69/ha-samsungtv-smart#39]
**Describe the bug**
Hi
I've configured the Samsung TVSmart in respecting the processes.
I've defined the host+source_list
I've created the api_key token in the website : https://account.smartthings.com/tokens/new
next I've taken my device id from the smartthings website :
 
```
mnsl: http://www.samsung.com/sec/tv/overview/
dmv: res.1.1.0,sh.1.1.0
di: 5bca4702-a71a-44b3-a04f-xxxxxxxxx
mnmo: UE43RU7105KXXC
mnmn: Samsung Electronics
mnos: 4.1.10
mnpv: Tizen 5.0 
```
and finally add in my config :

`samsungtv_smart:
  - host: 192.168.1.29
    name: Télévision SAMSUNG
    source_list: '{"WDTV": "ST_HDMI1", "PS4": "ST_HDMI2", "TELE": "ST_HDMI3"}'
    api_key: 1b050e01-c71b-4cde-ab1d-xxxxxxxx
    device_id: 5bca4702-a71a-44b3-a04f-xxxxxxxx`

**Expected behavior**
But when I select in lovelace the WDTV or PS4 or TELE, nothing happened.
Checking the log : 

`2020-09-21 23:39:49 ERROR (MainThread) [custom_components.samsungtv_smart.media_player] Unsupported _ST source. You must configure SmartThings`

**Environment details:**
 - Environment (HASSIO, Raspbian, etc):

arch | armv7l
-- | --
chassis | embedded
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.13
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.127-v7
python_version | 3.8.5
supervisor | 245
timezone | Europe/Paris
version | 0.115.2
virtualenv | false

 - Home Assistant version installed: Home Assistant 0.115.2
 - Component version installed: the last !
 - Last know working version: -
 - TV model:UE43RU7105KXXC

I don't understand why this issue because api_key + device_id are defined... Why ST_ couldn't work ?
Thanks for your help !

**Comment by ollo69** [comment]
Don't use configuration.yaml for initial component configuration. Configure with UI, than use configuration.yaml to personalize app list and source list.
Refer to Readme for more details about configuration parameter meaning and usage.

**Comment by Audiothor** [comment]
Hi
I've mixed the configuration.xml description + creation in HA for the installation. You've right.
Just HA + token works very well. Thanks for your work !
