### ISSUE TITLE
Error in the log: "SamsungTV Smart - Detected fake power on, status not updated"

### ISSUE THREAD

**Issue by spider7611** [ollo69/ha-samsungtv-smart#41]
**Describe the bug**
Always get this error in the log:

Logger: custom_components.samsungtv_smart.media_player
Source: custom_components/samsungtv_smart/media_player.py:643
Integration: SamsungTV Smart (documentation)
First occurred: 14:11:23 (1 occurrences)
Last logged: 14:11:23

SamsungTV Smart - Detected fake power on, status not updated

**Expected behavior**
If applicable, a clear and concise description of what you expected to happen.

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HA in Docker
 - Home Assistant version installed: Latest 0.115.2
 - Component version installed: latest
 - Last know working version: don't know
 - TV model: Samsung Q65

**Output of HA logs**
Paste the relavant output of the HA log here.

```
Logger: custom_components.samsungtv_smart.media_player
Source: custom_components/samsungtv_smart/media_player.py:643
Integration: SamsungTV Smart (documentation)
First occurred: 14:11:23 (1 occurrences)
Last logged: 14:11:23

SamsungTV Smart - Detected fake power on, status not updated

```

**Additional context**

**Comment by ollo69** [comment]
This is not an error but a warning. Do you also have issue with the TV status that is not properly detected?

**Comment by spider7611** [comment]
Status update a little bit late, but it is ok. Only this warning in the log.

**Comment by ollo69** [comment]
So just ignore it, is warning you that the TV network is on but is not a real status. I will lower this message to info in the future.

**Comment by spider7611** [comment]
Ok, thank your good work!
