### ISSUE TITLE
TV name/icon issues on HomeKit

### ISSUE THREAD

**Issue by iondarie** [ollo69/ha-samsungtv-smart#42]
**Describe the bug**
On iOS13 HomeKit receives the TV icon but the name is set to "Other"
On iOS14 HomeKiti does not get the TV icon and the name is always set to "TV"

**Screenshots**
iOS13
![ios13](https://user-images.githubusercontent.com/9055885/94348847-2991d300-0048-11eb-8f30-d7c07b73a537.jpeg)

iOS14
![ios14](https://user-images.githubusercontent.com/9055885/94348853-2f87b400-0048-11eb-8a52-090aa54cb67e.jpeg)

**Environment details:**
 - hassio
 - HassOS 4.13 / Home Assistant 0.115.3
 - Component version installed: v0.3.14
 - Last know working version: ...
 - TV model: UE55MU6172 / UE43RU7102KXXH

**Comment by ollo69** [comment]
This integration have nothing to do with HomeKit, this issue should be reported to Home Assistant.

**Comment by iondarie** [comment]
Thank you for your prompt answer. I will report the issue to Home Assistant
