### ISSUE TITLE
No entity created on adding device

### ISSUE THREAD

**Issue by PDekker** [ollo69/ha-samsungtv-smart#47]
**Describe the bug**
After finishing adding the device trough the ui, the proces is finished and can select “the headline” of my new TV in the integrations panel. However, there is no device and no entity created
**Expected behavior**
If applicable, a clear and concise description of what you expected to happen.

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Hassio
 - Home Assistant version installed: 0.118.3
 - Component version installed: 0.3.14
 - Last know working version:
 - TV model: Samsung Q60T

**Output of HA logs**

Logger: homeassistant.components.media_player
Source: custom_components/samsungtv_smart/api/smartthings.py:329
Integration: Mediaspeler (documentation, issues) 
First occurred: 20:33:44 (4 occurrences) 
Last logged: 20:38:49

samsungtv_smart: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
    await task
  File "/config/custom_components/samsungtv_smart/media_player.py", line 617, in async_update
    await self._st.async_device_update(use_channel_info)
  File "/config/custom_components/samsungtv_smart/api/smartthings.py", line 329, in async_device_update
    device_all_sources = json.loads(
  File "/usr/local/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

**Additional context**

**Comment by ollo69** [comment]
What I see from your log is that is failing while trying to retrieve source list from SmartThings, that is empty. May be is a bug, but are you sure that TV is properly configured in you SmartThings phone app?

**Comment by PDekker** [comment]
Yes, however... I do not have any HDMI devices connected or some kind of antenna. I only use the apps.

I’ll try to connect a hdmi device and report back

**Comment by ollo69** [comment]
Ok, wait for you feed-back, probably this is the the issue. If this is the cause, I will fix because it is a not managed condition.

**Comment by ollo69** [comment]
I just released a new version that should fix this issue.

**Comment by PDekker** [comment]
> I just released a new version that should fix this issue.

It’s working! Thanks
