### ISSUE TITLE
please send tv hdim1 to hdim2

### ISSUE THREAD

**Issue by pafftis** [ollo69/ha-samsungtv-smart#48]
please send me script tv hdim1 or hdim2

**Comment by ollo69** [comment]
I do not understand what you are asking for.

**Comment by Fidaninho** [comment]
Hello ollo69,
I can only think that he wants to know how to integrate more than just TV and HDMI.
Like: TV, HDMI 1, HDMI2, HDMI3

**Comment by fusionstream** [comment]
Should close this issue. OP doesn't clarify his cryptic post
