### ISSUE TITLE
connect not successful

### ISSUE THREAD

**Issue by cazbrat** [ollo69/ha-samsungtv-smart#5]
Hi,
I can't connect the tv.
I try first using the web UI, but the error is the same: _not_successful_

`2020-03-28 09:06:26 ERROR (MainThread) [custom_components.samsungtv_smart.config_flow] Error during setup of host 192.168.1.107 using configuration.yaml info. Reason: not_successful`

HA and TV are on different subnets, but there is no firewall between them.
Where do you think the problem may be?
thx

**Comment by ollo69** [comment]
Different subnet may have problem related to the routing. Is this the only error taht you see in the log?

**Comment by cazbrat** [comment]
Is the only error in the log.
`2020-03-28 10:05:13 ERROR (MainThread) [custom_components.samsungtv_smart.config_flow] Error during setup of host 192.168.1.107 using configuration.yaml info. Reason: not_successful`

The other devices that are on the same subnet as the TV do connect:
`2020-03-28 10:04:27 INFO (Thread-3) [roomba.roomba] Connected to Roomba`

**Comment by ollo69** [comment]
Yes, but connection to the TV use different protocol and port. Are you using SmartThings in config?

**Comment by cazbrat** [comment]
lol, yes the tv was online and pinging tv from HA to verify the connection, during HA reboot
I use SmartThing.
And the popup never appeared on the tv screen.
My TV is QN65Q60RAGXZS

**Comment by ollo69** [comment]
What is your TV model?
You should check settings for external device on your TV menu to be sure that connection check is done the first time.

**Comment by ollo69** [comment]
What is your environment / OS? Are you using HASSIO?

**Comment by cazbrat** [comment]
My TV model is QN65Q60RAGXZS
And HA is a docker https://hub.docker.com/r/homeassistant/home-assistant over SynologyNAS (linux OS).

I review the TV menu, for external device item, it's ok too.

**Comment by ollo69** [comment]
Honestly I'm not expert with HassOS / Docker installation but I think that you cannot run this custom_component because it use requests inside component script. You should have a manual installation on linux / rasbian / windows to make it work.

**Comment by cazbrat** [comment]
I will try that with a raspberrypi on the same subnet of the TV and I will tell you.
Thank you

**Comment by cazbrat** [comment]
Yes sir!.... You're right
In a HASSIO and in the same subnet, my TV model QN65Q60RAGXZS, works!
thx!!

**Comment by pepsonEL** [comment]
Is any chance to add integration for TV Samsung which is in other VLAN than VLAN with HomeAssistant ?
