### ISSUE TITLE
Remote Control from Remote app on iPhone

### ISSUE THREAD

**Issue by Teglgaard** [ollo69/ha-samsungtv-smart#51]
In the iPhone Remote App I can choose the Samsung TV after setting it up with ha-samsungtv-smart. But it does not send the commands to the tv from the iPhone Remote App. I would love to be able to use my iPhone as a remote just like i have used to do with HomeBridge instead. Alternatives could be to be able to remote control from inside Home Assistant, but it is still more convenient to use the iPhone Remote App.

And, btw great work!

**Comment by ollo69** [comment]
Sorry but I do not understand what is your request. What is the iPhone Remote App?

**Comment by Teglgaard** [comment]
No worries. The iPhone remote app is an app built in to iOS at least in iOS 14 that can be used to control an apple tv or compatible tv. I thought it would make sense to have ha-samsungtv-smart to pick up on the remote control which currently only can be controlled to my knowledge through the SmartThings integration in Home Assistant. Together with this and the HomeKit integration the tv can be controlled by using the automation posted below. I thought it could be smart just to natively pick up the event from homekit and pass it on to the Samsung TV since the keys are the same across the Samsung tv lineup. 

You can see my automation setup here:

alias: Call Samsung TV on HomeKit Remote key presses
description: ''
trigger:
  - platform: event
    event_type: homekit_tv_remote_key_pressed
    event_data: {}
condition: []
action:
  - service: media_player.play_media
    data_template:
      entity_id: '{{ trigger.event.data[''entity_id''] }}'
      media_content_type: send_key
      media_content_id: >-
        {% set key_map = {'arrow_right': 'KEY_RIGHT', 'arrow_down' : 'KEY_DOWN',
        'arrow_left': 'KEY_LEFT', 'arrow_up': 'KEY_UP',  'select': 'KEY_ENTER',
        'back': 'KEY_RETURN', 'information': 'KEY_HOME'} %} {{
        key_map[trigger.event.data['key_name']] }}
mode: single

**Comment by ollo69** [comment]
Sorry but I have no idea on how to test / fix this. Should this work using homekit? Do you have some specific error to check?

**Comment by Teglgaard** [comment]
Hi again, with homekit installed as seen in the integrations below then you get the platform events "homekit_tv_remote_key_pressed" when using the iPhone Control Center Remote control for the TV.
<img width="264" alt="Screen Shot 2021-01-07 at 20 43 24" src="https://user-images.githubusercontent.com/15330608/103937455-10a9bb00-5129-11eb-8ac3-0f520b930bf4.png">

Then all Samsung TVs respond to the same key clicks sent to it e.g. "KEY_UP" to click upwards on the tv or "KEY_HOME" to go to the Menu. So my suggestion was just to have the ability to pick up those types of events so everyone can enjoy using the iPhone Control Center Remote to control their Samsung TVs.

So to test this you just install the HomeKit Integration and listen to events "homekit_tv_remote_key_pressed" and then use the automation above to learn how to integrate it into your repo.

I hope it helps with this explanation.

**Comment by pilot1981** [comment]
@ollo69  this i Apple remote on iPhone: 
![Uploading 2C04DB97-4EE8-4A1D-90ED-AA66C9A5D0D0.jpeg…]()

**Comment by pilot1981** [comment]
![ED11CE3E-CA27-4C19-AA09-E2E17156F6C3](https://user-images.githubusercontent.com/46350465/111073262-60688200-84de-11eb-8b3d-2d5c7e1cf2f3.jpeg)

**Comment by pilot1981** [comment]
> No worries. The iPhone remote app is an app built in to iOS at least in iOS 14 that can be used to control an apple tv or compatible tv. I thought it would make sense to have ha-samsungtv-smart to pick up on the remote control which currently only can be controlled to my knowledge through the SmartThings integration in Home Assistant. Together with this and the HomeKit integration the tv can be controlled by using the automation posted below. I thought it could be smart just to natively pick up the event from homekit and pass it on to the Samsung TV since the keys are the same across the Samsung tv lineup.
> 
> You can see my automation setup here:
> 
> alias: Call Samsung TV on HomeKit Remote key presses
> description: ''
> trigger:
> 
> * platform: event
>   event_type: homekit_tv_remote_key_pressed
>   event_data: {}
>   condition: []
>   action:
> * service: media_player.play_media
>   data_template:
>   entity_id: '{{ trigger.event.data[''entity_id''] }}'
>   media_content_type: send_key
>   media_content_id: >-
>   {% set key_map = {'arrow_right': 'KEY_RIGHT', 'arrow_down' : 'KEY_DOWN',
>   'arrow_left': 'KEY_LEFT', 'arrow_up': 'KEY_UP',  'select': 'KEY_ENTER',
>   'back': 'KEY_RETURN', 'information': 'KEY_HOME'} %} {{
>   key_map[trigger.event.data['key_name']] }}
>   mode: single

I didn’t understand your automation: where I have to use it?

With it Apple remote works fine?

**Comment by Teglgaard** [comment]
Your library does not pass on commands to my samsung tv from iOS Remote as you posted a picture off above. Maybe it has changed but I had to make my own automation together with homekit to make it work instead of your library just listening for the commands as shown in my automation.

**Comment by Teglgaard** [comment]
So for me your library did not work with my samsung tv but maybe it is updated I have not tested without my own automation from iOS remote

**Comment by pilot1981** [comment]
@Teglgaard this component don’t work in Apple remote control; where I can use your automation to fix it?

**Comment by Teglgaard** [comment]
I do not know how to built components so I do not know where it fits into your code. Running above code as an automation in home assistant solves the problem. My suggestion is just to have it natively in your library. For that I do not know how to code it.

**Comment by pilot1981** [comment]
what I don't understand is where you used this code in HA:

platform: event
event_type: homekit_tv_remote_key_pressed
event_data: {}
condition: []
action:
service: media_player.play_media
data_template:
entity_id: '{{ trigger.event.data[''entity_id''] }}'
media_content_type: send_key
media_content_id: >-
{% set key_map = {'arrow_right': 'KEY_RIGHT', 'arrow_down' : 'KEY_DOWN',
'arrow_left': 'KEY_LEFT', 'arrow_up': 'KEY_UP', 'select': 'KEY_ENTER',
'back': 'KEY_RETURN', 'information': 'KEY_HOME'} %} {{
key_map[trigger.event.data['key_name']] }}
mode: single

**Comment by pilot1981** [comment]
@Teglgaard how many item you have in homekit integration?

I have different item for HA bridge and Samsung TV...
![homekit](https://user-images.githubusercontent.com/46350465/111186185-11405100-85b3-11eb-9cd6-5464e23e9216.jpg)

**Comment by Teglgaard** [comment]
Hi again, 
@pilot1981 I only have one device as seen below
<img width="265" alt="Screen Shot 2021-03-15 at 18 11 46" src="https://user-images.githubusercontent.com/15330608/111192943-eb6a7a80-85b9-11eb-87ba-e837860e5c0e.png">

The code you see is inputted into "Configuration"->"Automation"->"Add Automation" button
Then edit the in yaml through the three dotted menu in top right corner and input:
`
alias: Call Samsung TV on HomeKit Remote key presses
description: ''
trigger:
  - platform: event
    event_type: homekit_tv_remote_key_pressed
    event_data: {}
condition: []
action:
  - service: media_player.play_media
    data_template:
      entity_id: '{{ trigger.event.data[''entity_id''] }}'
      media_content_type: send_key
      media_content_id: >-
        {% set key_map = {'arrow_right': 'KEY_RIGHT', 'arrow_down' : 'KEY_DOWN',
        'arrow_left': 'KEY_LEFT', 'arrow_up': 'KEY_UP',  'select': 'KEY_ENTER',
        'back': 'KEY_RETURN', 'information': 'KEY_HOME'} %} {{
        key_map[trigger.event.data['key_name']] }}
mode: single

`

**Comment by pilot1981** [comment]
Hi @Teglgaard,
I tried to import this yaml code:

`
  - platform: event
    event_type: homekit_tv_remote_key_pressed
    event_data: {}
    condition: []
    action:
  - service: media_player.play_media
    data_template:
    entity_id: '{{ trigger.event.data[''entity_id''] }}'
    media_content_type: send_key
    media_content_id: {% set key_map = {'arrow_right': 'KEY_RIGHT', 'arrow_down' : 'KEY_DOWN', 'arrow_left': 'KEY_LEFT', 'arrow_up': 'KEY_UP', 'select': 'KEY_ENTER', 'back': 'KEY_RETURN', 'information': 'KEY_HOME'} %} {{key_map[trigger.event.data['key_name']] }}
    mode: single
`

but HA GUI answer: message malformed


what is wrong?

**Comment by Teglgaard** [comment]
Hi again, it is malformed because it contains formatting that interferes with Github
I have added it to the file below
[Code.txt](https://github.com/ollo69/ha-samsungtv-smart/files/6146719/Code.txt)

**Comment by pilot1981** [comment]
ok, now I'm able to add it to HA: thanks @Teglgaard !

this is the code:

`alias: Call Samsung TV on HomeKit Remote key presses
description: ''
trigger:
  - platform: event
    event_type: homekit_tv_remote_key_pressed
    event_data: {}
condition: []
action:
  - service: media_player.play_media
    data_template:
      entity_id: '{{ trigger.event.data[''entity_id''] }}'
      media_content_type: send_key
      media_content_id: >-
        {% set key_map = {'arrow_right': 'KEY_RIGHT', 'arrow_down' : 'KEY_DOWN',
        'arrow_left': 'KEY_LEFT', 'arrow_up': 'KEY_UP',  'select': 'KEY_ENTER',
        'back': 'KEY_RETURN', 'information': 'KEY_HOME'} %} {{
        key_map[trigger.event.data['key_name']] }}
mode: single
`

You already tried to add this automation in:

 integration->samsungtv->sasmungtv->automation


?

**Comment by pilot1981** [comment]
@Teglgaard your automation acceptd fine from HA, but I'm not able to change channel using arrow up/down right/left.

please can you share also configuration.yaml? I think it depend from source_list/channel_list...

**Comment by Teglgaard** [comment]
Hi again, you can decide how it should work based on [https://github.com/tavicu/homebridge-samsung-tizen/wiki/Commands](url)

Then you just edit as you would like.

This is the entry in configuration.yaml for the tv
`samsungtv_smart:
  - host: 192.168.0.xx
    name: Samsung TV
    api_key: xxxxxxxxxx`

**Comment by pilot1981** [comment]
Hi @Teglgaard, thanks for reply! so you don't add source list and channel list option in configuration.yaml?

**Comment by pilot1981** [comment]
thanks @Teglgaard all very usefull! all works fine!

**Comment by antonio1475** [comment]
@Teglgaard **THANK**. **YOU**.

It works very nicely. Coming from an LG TV that works with homekit, this was missing in the Samsung TV.

It has some "dead time" between taps, so you have to wait half a second before tapping again, but it's so much better than nothing.

It was pretty hard finding this information (Samsung TV, iOS Remote, with or without HA). I hope one day this is native in the integration like the LG WebOS integration.

Plus, I learned that the iOS app sends events to HA, so it can be customized. Thanks again

**Comment by doudigit** [comment]
I’ve figured out a way on how to get rid of that delay, unfortunately it only works on android based tv or any other tv that has restApi that can send commands.  Due to adb shell commands with android tv integration being slow to respond compared to native remote and my tv not having any restApi I’ve used an android keyboard with restApi that allows adb shell input key commands. Now the response speed of the control center remote is the same as native physical remote. Plus I’ve included a way to control play pause and volume up and down using the same principles. You can find it all here at [Home assistant community link](https://community.home-assistant.io/t/ios-shortcuts-siri-homekit-remote-ha-integrations/420234/6?u=digitone)

**Comment by antonio1475** [comment]
@doudigit I don't remember what the delay felt like when I wrote that, but it works super fast now.

Do you guys get volume control working. Mine worked for a while but not anymore. All the rest works through the automation above.

**Comment by doudigit** [comment]
@antonio1475 volume up and down, as well play/pause works and can be modified by using automation in the link I’ve posted.

**Comment by antonio1475** [comment]
Just to clarify, I'm not using what you posted regarding restAPI (my QN93A isn't Android TV, and I don't know if it supports restAPI or not - doen't really matter for me), but I'm using the Automation by Teglgaard above:

```
alias: 'Tele comedor: HomeKit Remote'
description: ''
trigger:
  - platform: event
    event_type: homekit_tv_remote_key_pressed
    event_data:
      entity_id: media_player.samsungtv_smart
condition: []
action:
  - service: media_player.play_media
    data_template:
      entity_id: '{{ trigger.event.data[''entity_id''] }}'
      media_content_type: send_key
      media_content_id: >-
        {% set key_map = {'arrow_right': 'KEY_RIGHT', 'arrow_down' : 'KEY_DOWN',
        'arrow_left': 'KEY_LEFT', 'arrow_up': 'KEY_UP',  'select': 'KEY_ENTER',
        'back': 'KEY_RETURN', 'information': 'KEY_HOME', 'volume_up':
        'KEY_VOLUP', 'volume_down': 'KEY_VOLUP'} %} {{
        key_map[trigger.event.data['key_name']] }}
mode: single
```

Even though I have volume in there, the Volume keys from iOS Remote App aren't transmitted to Home Assistant (listening to events homekit_tv_remote_key_pressed shows that).

However, I found [another issue](https://github.com/ollo69/ha-samsungtv-smart/issues/96#issuecomment-1081896141) in this repo mentioning this, that took me to [this one. As per the last comment](https://github.com/home-assistant/core/issues/63043#issuecomment-1125013606), **removing the TV from Homekit app and re-adding it** (Ha automatically generated a new code), **it all now works** (volume + automation keys). Let's hope it lasts.

Cheers 😄

**Comment by doudigit** [comment]
@antonio1475 volume up Down and play pause can only be controlled when declared using a custom media player that you declare in config yaml. Everything is in that link what you need to do and just modify it to your use. Automation is for every other key tho besides these 4. As for issue when remote doesn’t work a simple reload of only tv bridge fixes it
