### ISSUE TITLE
no entity created on first device added

### ISSUE THREAD

**Issue by jalejandrio2** [ollo69/ha-samsungtv-smart#52]
This is my first time reporting something! hope i did it well and thanks for reading me.

**Describe the bug**
After finishing adding the device trough the ui, the proces is finished and can select “the headline” of my new TV in the integrations panel. However, there is no device and no entity created
Expected behavior
If applicable, a clear and concise description of what you expected to happen.

**Environment details:**
Environment (HASSIO, Raspbian, etc): Hassio
Home Assistant version installed: 2020.12.1
Component version installed: 0.3.16
TV model: Samsung QE85Q80TATXXC

**Output of HA logs**
samsungtv_smart: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
    await task
  File "/config/custom_components/samsungtv_smart/media_player.py", line 614, in async_update
    await self._st.async_device_update(use_channel_info)
  File "/config/custom_components/samsungtv_smart/api/smartthings.py", line 329, in async_device_update
    device_all_sources = json.loads(
  File "/usr/local/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

When I go to lovelace on the card of mediaplayer I don't see the entity and I don't understand why. Either way I don't see the entity on the entity list.

Thanks for the help

**Comment by ollo69** [comment]
This is strange because I thought I had already solved this problem, obviously there are some conditions that I had not foreseen. I changed the SmartThings source list load in last release, please try it and report if it solve.
Just one question: do you have some devices connected to HDMI TV ports or not?

**Comment by jalejandrio2** [comment]
hello thanks for responding! :)
You are GREAT! solved it with the update

I have 2 HDMI with nintendo switch and another with ps4

thanks sooooo much

**Comment by ollo69** [comment]
So i suppose that this 2 inputs are not detected by the integration, right?

**Comment by jalejandrio2** [comment]
yes they are detected also. Works perfect thanks so much

**Comment by ollo69** [comment]
That's fine, so I close this issue.
