### ISSUE TITLE
UE75NU7100 does not turn on

### ISSUE THREAD

**Issue by romanovroman74** [ollo69/ha-samsungtv-smart#53]
The component works perfectly through the api of smart things. My problem is this: if the TV has been turned off for more than a few minutes, then it can only be turned on manually via the infrared remote control. After starting manually via the infrared remote control, the component continues to work successfully. Because of this, I cannot use the TV in my scripts. If you turn off the TV and try to turn it on again through the component within the first 2 minutes, then, as a rule, the TV turns on successfully. But nothing more.

**Comment by 8osman** [comment]
I'm investigating this on my UE32N5300AKXXU, I've noticed that the 'on' selection within the smartthings app is lost suggesting it's a samsung issue. At a guess, I would say the TV's are going into a "deepsleep" mode after a few mins.

**Comment by ollo69** [comment]
Is your TV connected via LAN or WiFi?
Try with last released version using the new option "Number of time WOL packet is sent to turn on TV". Try increasing the value to see if fix the issue.

**Comment by romanovroman74** [comment]
Thank you for your responses. I tried each of the 20 values. And none of them help me turn on my TV. It is connected via a wireless network, but I have the option of connecting it to the network with a cable. A year ago I already had a similar problem, but I really didn't use your component then. I talked to the technical support of the Samsung, with the question "Why does my smart things app not start my TV" They said that the camera should be connected wirelessly. And it worked for a while. This is why I have been using a wireless connection ever since. Now I cannot start the TV either from the component or from the smart things application if it falls deeply asleep.

**Comment by ollo69** [comment]
I can confirm after some test that SmartThings is able to control Power ON only when TV is connected using Wi-Fi.
In last release I added a configuration options to use SmartThings as Power ON method as alternative to WOL packet (that should work with wired connection), but if you are not able to turn-on TV from SmartThings app, I think that this will not help.
Related to the option to send multiple time the WOL packet, I was not convinced about this when I was implementing, it was just a test. I will probably reduce the maximum number of packet that can be sent to 5. In my case with TV wired connected 1 WOL packet is always enough.

**Comment by kanintesova** [comment]
I have the same problem with my TV. Sometimes it works. Sometimes it doesn't.

Unfortunately I can not integrate smartthings. TV does not even communicate ok with their API. I had one instance of the TV added there since old. But now it doesn't seem to work. Maybe something on Samsung 's part.
