### ISSUE TITLE
input text in text fields via ha-service

### ISSUE THREAD

**Issue by GatoPharaoh** [ollo69/ha-samsungtv-smart#56]
Hi - is there any way to send a text as a whole to the text field on the tv. e.g. an app wants me to input an email address or a password, is there a service call to send the email address or the password to the tv via Home Assistant?

At the moment, I am using key codes to send input text - which of course is not an optimal solution.

thanks in advance

**Is your feature request related to a problem? Please describe.**
is there a possible way, to input text into textfields on the tv via Home Assistant? E.g. i want to input an email-address on the tv and want to push the whole email address as one via Home Assistant to the text field on the tv.

**Describe the solution you'd like**
input text in Home Assistant and push it to the text field on the tv

**Describe alternatives you've considered**
as an alternative at the moment, I'm sending key presses via Home Assistant to use the on-tv-keyboard on an automated basis.

**Comment by ollo69** [comment]
In last release I added the possibility to send text using the `play_media` service setting `media_type = send_text`
Please let me know if ot work properly.

**Comment by GatoPharaoh** [comment]
nice - thank you very much. just tried it and it does work e.g. in the browser. however, it didn't work in the dazn app. any idea if this can also be done?
