### ISSUE TITLE
Picture Mode KEY_DYNAMIC & KEY_STANDARD won't work

### ISSUE THREAD

**Issue by romquenin** [ollo69/ha-samsungtv-smart#57]
First of all i would like to thank you for this amazing component, it makes my tv smarter and i absolutely love it !
For exemple with my Q7 from 2018, i can turn my av-amplifier on or off depending on the source the tv is on, and that's pretty smart.
I would love to go beyond that and set as well the picture mode (standard for tv and dynamic for netflix) but unfortunately those keys dont seem to work.
I have been able to use the key KEY_PMODE, so i have created an input_boolean to switch between the two modes from the picture menu depending on the source but it's far from prefect and it fails quite often.
Do you know if there is a fix or a key pattern to fire the picture mode keys ?
Thank you for your help and your great efforts.

**Comment by romquenin** [comment]
I partially solved this issue with some SmartThings Scenes:
https://github.com/jaruba/ha-samsungtv-tizen/issues/121

But it would be perfect to do this natively from HA.

I hope you will be able to find the correct entry in the API.

Thanks.

**Comment by ollo69** [comment]
Just implemented this feature in last component release using SmartThings.
Please let me know if it works for you (it does for me).

**Comment by romquenin** [comment]
Hello, thank you for your reply. I have updated the component and i just tried the KEY_DYNAMIC and KEY_STANDARD and it doesn't seem to work.
I have used this code in the dev service:
```
entity_id: media_player.samsung_tv_remote
media_content_id: KEY_DYNAMIC
media_content_type: send_key
```
I have also tried with "ST" instead of "KEY" but unfortunately it doesn't work.

**Comment by ollo69** [comment]
In `media_player` entity there is an option called `sound_mode` that now should be available:

![image](https://user-images.githubusercontent.com/60491700/107202748-d3bc3700-69fa-11eb-9cbf-b607edc102a2.png)

Also exist the service `select_sound_mode` that you can call to select the desired sound mode.

No KEY_DYNAMIC or KEY_STANDARD

**Comment by ollo69** [comment]
Sorry,

I only realized now that you are interested to picture mode and not sound mode. 
I'm also working on it, I will let you know when this will be ready.

**Comment by romquenin** [comment]
You are amazing

**Comment by ollo69** [comment]
Picture mode feature implemented. Because this is not native option for `media_player` entity, I created a new service called `select_picture_mode`. You can find additional detail in `readme` or in service documentation.
Please let me know if it work properly.

**Comment by romquenin** [comment]
Grazie mille @ollo69 ! You've just make my AV automations dreams come true, and being able to do this locally it's the cherry on the cake. Thank you for your help and your time, will buy you a coffee to celebrate this major feature !
