### ISSUE TITLE
Samsung TV no longer connecting

### ISSUE THREAD

**Issue by P3nkiln** [ollo69/ha-samsungtv-smart#58]
**Bug**
The integration no longer connects to my TV. It was working correctly until today.

Then I got this:

Call-service API error. Error Message: Invalid close opcode.

I tried reinstalling but HA and the integration no longer connect to the TV. The other integration says:

Aborted
This Samsung TV device is currently not supported.

**Expected behavior**
I expect the integration to control the TV.

**Environment details:**

Version | core-2021.2.2
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
Virtual Environment | false
Python Version | 3.8.7
Operating System Family | Linux
Operating System Version | 5.4.94
CPU Architecture | x86_64
Timezone | Europe/London

TV : QE49Q7FAM

**Output of HA logs**
Can't see anything relevant in the logs

**Comment by P3nkiln** [comment]
I wonder if it has anything to do with this issue that a lot of people are seeing?

[https://community.home-assistant.io/t/udevd-529-bind-failed-address-in-use/278578](url)

**Comment by ollo69** [comment]
Did you update something (HA, component version)?
I don't know how to help if it was working until yesterday, I don't think that is a component issue.

**Comment by P3nkiln** [comment]
I did. I updated HA and the OS today. I'm thinking it might be related to the link I posted above as it was working well until today. It's interesting that no version of the Samsung Integrations is working for me now.

**Comment by ollo69** [comment]
If you updated HA and OS it is clear that issue is related to what you updated. Please close this issue and eventually open HA side. Probably those updates break something related to WebSocket connection, for this reason no version of the Samsung Integrations are working.

**Comment by P3nkiln** [comment]
I will do that. Thanks for the advice
