### ISSUE TITLE
'version' key missing in the manifest 

### ISSUE THREAD

**Issue by chemelli74** [ollo69/ha-samsungtv-smart#59]
Current dev build of HA shows this warning:

`2021-02-10 09:31:51 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'samsungtv_smart'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'samsungtv_smart'`

Should be easy to fix ;-)

Thank you,

Simone

**Comment by ollo69** [comment]
Thanks for advise, added in last release.
