### ISSUE TITLE
PowerOff/On error on SmartThings

### ISSUE THREAD

**Issue by mariomazon** [ollo69/ha-samsungtv-smart#60]
**Describe the bug**
Got a 422, unprocessable entity when using smartthings to poweron/off.
_async_send_command gots a data_cmd parameter, but async_turn_off and async_turn_on doensn't call _command to prepend it.

**Expected behavior**
Prepend _command to COMMAND_POWER_OFF / COMMAND_POWER_ON in async_turn_off and async_turn_on functions

**Screenshots**

**Environment details:**

**Output of HA logs**

```

```

**Additional context**
Correct sugestion: change async_turn_off and turn_on functions (lines 439 and 443) to the following:

data_cmd = _command(COMMAND_POWER_OFF)
await self._async_send_command(data_cmd)

and

data_cmd = _command(COMMAND_POWER_ON)
await self._async_send_command(data_cmd)

**Comment by ollo69** [comment]
Yes, this is a bug, I will fix in next release.
