### ISSUE TITLE
TV on/off state

### ISSUE THREAD

**Issue by robyevolution** [ollo69/ha-samsungtv-smart#66]
Hi I have configured through UI integration, I have correctly configured smart things, but the status of the tv remains off, configured through yaml I can see the status on / off, in the log I do not see any errors, how can I solve?

**Comment by mmatus1112** [comment]
I have the same issue. I am able to turn the TV on and off, but HA shows the TV status as off. This prevents me from controlling the TV input and volume change. Any ideas?

**Comment by ollo69** [comment]
Please check if in HA log are present some errors and in case share here.

**Comment by srodighiero** [comment]
Same problem:

Device info
UE50NU7400 ([TV] Samsung 7 Series (50))

![image](https://user-images.githubusercontent.com/4833164/140961578-49b5fb07-fe0f-478f-89b9-5f1e6213892d.png)
It appears to be after every 25 minutes of (correct) off state, then reporting false "on" state for 20 seconds. Not happening during TV turned on. 

I do not have any supervisor/core log about
