### ISSUE TITLE
Websocket select option during setup process

### ISSUE THREAD

**Issue by Snakesms** [ollo69/ha-samsungtv-smart#69]
**Is your feature request related to a problem? Please describe.**
Can't add TV based in the network different from HA server i.e TV is in 192.168.2.x HA server is in 192.168.1.x

**Describe the solution you'd like**
Either add an option to select the type of WebSocket during initial setup, 
or an option to change TV's IP after the initial setup completed

Thanks and Regards

**Comment by accik** [comment]
My tv in on 192.168.30.x and HA on 192.168.1.x. Firewall is allowing all to the HA server, pi-hole is off, ping is fine.
So the issue is in the integrations? Stock one refuses immediately.

**Comment by ollo69** [comment]
As I know Samsung TV do not allow WebSocket connection from devices on different subnet. Try put HA and TV on same subnet, should solve the issue.

**Comment by accik** [comment]
You were right, thank you!

**Comment by ollo69** [comment]
Can we close the issue?

**Comment by ollo69** [comment]
@Snakesms ,

your ft request is not possible for 2 reasons:

1) The Samsung TV do not accept ws connection  from different subnet, so if you change the network after configuration the integration will not work in any case
2) Change the TV IP in integration configuration is not possible because the IP is used as uniqueID

**Comment by Snakesms** [comment]
As its not possible to implement, please closes the issue.
Just out of curiosity: what does the type of WebSocket mean then?
If Samsung doesn't support WebSocket connection from the other network, how "remote WebSocket" can exist after all?

**Comment by ollo69** [comment]
I do not exactly understand what do you mean with "type of WebSocket" and "remote WebSocket". What you are referring?
I think that Samsung set this limitation for security issue, permitting connection to TV only to device in the same LAN.

**Comment by Snakesms** [comment]
[https://nextcloud.snakesms.dev/s/nQSQ7c8XWMXPfe5](url)
Can you have a look at the screenshot, please?

**Comment by ollo69** [comment]
Nothing to do with remote / local, this just refer to `websocket` channel names provided by TV (normally are 3) used to launch application. The scope of the option is just for tuning application launch because the `standard` one sometimes do not work properly. I understand now your misunderstanding, I could rename `remote` to `alternative`.

**Comment by Snakesms** [comment]
Yeah I've got confused with the wording and thanks for the explanation.

Despite of your statement "The Samsung TV do not accept ws connection from different subnet"
If it won't require too much effort from your side, it will be great if you can "add an option to select the type of WebSocket during initial setup"(may be even in some test/dev version) as I think I was able to connect from another network once selected "remote" option. The only error I've got that time was - such TV already added to the system.

So it will be really great to test and prove either connectivity works or not
Thank again got your hard work with this integration!

**Comment by ollo69** [comment]
Let me better clarify: exist only 1 `websocket` connection to the TV, and the TV must accept the connection (this is what is done during initial setup). If the connection is accepted, than 3 different channel are opened, 1 for remote control, 1 for app control and (eventually) 1 for frame TV. It is not possible to open the 2nd and the 3rd if the 1st do not connect successfully. The 2nd channel used for app launch in some case do not work, so in this case you can change the option to force using the 1st channel (called remote) also to launch the app.
So providing an "option to select the type of WebSocket during initial setup" simply do not make sense.

**Comment by Snakesms** [comment]
Thanks for the explanation.
It sounds like for setting it up properly I would have to move HA back and force between network segments...
