### ISSUE TITLE
Data files (token, applist) stored outside storage folder

### ISSUE THREAD

**Issue by frenck** [ollo69/ha-samsungtv-smart#71]
**Describe the bug**

Things like token files:

```py
token_file = (
    os.path.dirname(os.path.realpath(__file__))
    + "/token-"
    + self._hostname
    + ".txt"
)
```

Or dumpfiles/applists:

```py
dump_file_name = (
    os.path.dirname(os.path.realpath(__file__))
    + "/applist-"
    + self._host
    + ".txt"
)
```

Should not be stored in the custom integration folder itself.

These files belong in the Home Assistant storage folder.
Example:

```py
from homeassistant.helpers.storage import STORAGE_DIR

token_file = hass.config.path(STORAGE_DIR, f"samsungtv-token-{self._hostname}.txt")
```

Of course, migration of the current file would be needed.

**Expected behavior**

Not to have file changes in the custom component folders. I almost accidentally committed and published my tokens (hidden in the code) to GitHub.

**Screenshots**

N/A

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): All
 - Home Assistant version installed: All
 - Component version installed: v0.3.30
 - Last know working version: None
 - TV model: Irrelevant

**Output of HA logs**

Not relevant.

**Additional context**

No additional context.

**Comment by ollo69** [comment]
Hi @frenck, thanks for suggestion, I will work on this change with next release.

**Comment by ollo69** [comment]
This should be fixed with [last release](https://github.com/ollo69/ha-samsungtv-smart/releases/tag/v0.3.31).
Please let me know if it is ok.

**Comment by frenck** [comment]
Alright, thanks, going to test it right away 👍

**Comment by frenck** [comment]
Nice! Works like a charm, thanks 🥇
