### ISSUE TITLE
App Logos not appearing in the media control

### ISSUE THREAD

**Issue by JeffSteinbok** [ollo69/ha-samsungtv-smart#75]
Not sure if this is a bug or feature request.  The SamsungTV_Tizen repo this was forked from supports logos for the currently running app.  Any chance you can add that to your fork of the repo?  Aside from that, I find your version much more stable.

**Comment by ollo69** [comment]
There is a project to merge this fork with SamsungTV Tizen. When completed all features will be available in new version of the original repo.

**Comment by ollo69** [comment]
Merge project at the moment is stopped, for this reason I implemented logo feature here. I close this issue issue because solved
