### ISSUE TITLE
Volume slider. 

### ISSUE THREAD

**Issue by larsoss** [ollo69/ha-samsungtv-smart#76]

**Comment by larsoss** [comment]
i have a problem with the volume slider. Previously, the slider worked, changing the volume on the TV. However, I can now only change it by standing on the map, and then pressing the + / -. I have the latest version of SamsungTV Smart v0.3.33 and HA 2021.3.4. Also with the previous version of HA it no longer worked.
![7F9CBB79-08AE-496B-A0B4-622D4A3A9612](https://user-images.githubusercontent.com/3639942/115960147-fcd76880-a50f-11eb-8b64-e4e9104ac026.png)

**Comment by ollo69** [comment]
Nothing changed component side, so it is a TV problem. Did you connect some audio device to the TV (e.g. a soundbar?)

**Comment by larsoss** [comment]
well I do have a soundbar connected via optic.

**Comment by ollo69** [comment]
Soundbar do not allow volume control with slider. Try disconnect it and check if slider is available again

**Comment by leksmw** [comment]
is it possible to use the slider if the soundbar is connected to the TV via an optical cable? the soundbar is perfectly controlled from the TV remote control. integration controls volume only with + and - buttons

**Comment by ollo69** [comment]
Your question is already answered in previous post, why you ask again?

**Comment by mitzu2250** [comment]
> Your question is already answered in previous post, why you ask again?

This should be added to a FAQ or something. I have the same configuration (with a Soundbar) and I thought that it's an issue before finding this topic.
