### ISSUE TITLE
howto control soundbar SAMSUNG

### ISSUE THREAD

**Issue by pilot1981** [ollo69/ha-samsungtv-smart#77]
Hi,
I would know if it's possibile to power on/off today or in the future also soundbar SAMSUNG attached to Samsung TV: I need to attach it with HDMI ARC port? It can works also using audio coaxial cable?

**Comment by ollo69** [comment]
I think that this option come native from device itself. I have a Soundbar (not Samsung BTW) attached with HDMI ARC port and TV automatically turn sound bar on and off with the TV and volume can be controlled from TV remote. But this has nothing to do with integration

**Comment by pilot1981** [comment]
I ordered a new Samsung Soundbar available in Samrthings...I let you know what/how to do soon...

**Comment by pilot1981** [comment]
Soundbar Samsung S60A arrived: I go to try your integration!

**Comment by pilot1981** [comment]
![Uploading 6D791FE6-ED2C-4C94-8572-7DBBA02BC81E.png…]()

**Comment by pilot1981** [comment]
![8875E489-68F3-442F-B792-D5959E23D65C](https://user-images.githubusercontent.com/46350465/144652797-c042220d-95fa-4f26-8012-e3600477b450.png)

**Comment by ollo69** [comment]
I really don't think that soundbar implements `tizen` protocol that is core part of this integration.

**Comment by pilot1981** [comment]
You think so? It has IP address And it can be controlled directly from Samsung SmartThings app…

**Comment by ollo69** [comment]
This is true also for a new Samsung dishwasher

**Comment by pilot1981** [comment]
I can also control soundbar via Alexa...
