### ISSUE TITLE
false positve TV powered on on Frame version

### ISSUE THREAD

**Issue by pilot1981** [ollo69/ha-samsungtv-smart#78]
Hi,
I have a TV FRAME 2020 and all seems works fine.

I notice sometime happen:
- TV is in ART MODE
- HA component say TV in ON

problem is random and I'm not able to replicate it.

how can help you to find bug? How I can collect logs/information

**Comment by Poggen** [comment]
I'm also getting this issue with the [official Samsung TV integration](https://www.home-assistant.io/integrations/samsungtv), so I doubt it has something to do with this integration. Still curious if anyone finds a solution, though!

**Comment by pilot1981** [comment]
yes, some time I saw samsung TV powered on in HA, but really it was in art mode...

Also me, I see italia uno onin both HA and Smarthings app...but really TV is in art mode...I think this will be more difficult to solve...

**Comment by ollo69** [comment]
Can we close this issue?

**Comment by pilot1981** [comment]
Thanks!

now I can be sure to power off my FRAME TV (starting from art mode or power on state)!

Now this is the most featured custom components for home assistant to manage SAMSUNG FRAME TV (with art mode active!!!

the only command I don’t find is howto to go to art mode, starting from powered off or powered on state…

it will need a 3 state button power off/art mode/power on…feature request for the future?  :-)

**Comment by ollo69** [comment]
Integration provide a service to control art mode. You can use the service to create button on the UI or automation.

**Comment by ollo69** [comment]
Closing this issue, Fix was released and no additional feed-back from +3 months.
