### ISSUE TITLE
Samsung TV works fine on WiFi but when wired doesnt work at all.

### ISSUE THREAD

**Issue by Nick-116** [ollo69/ha-samsungtv-smart#81]
**Describe the bug**
Hello, when I connect my TV, it works well when wirelessly connected. When I try to connect it using ethernet to my network, it doesn't work at all. I've tried this using just the IP, and with both the IP and the smart things code. It says it can't find the DeviceID, so I went into the settings on my TV and copied the device ID down, but it still didn't work.

**Expected behavior**
I expected it to add the device, but instead, it said no device ID found, and when I put the device ID in it said device not found. It does give me a prompt on the TV saying to approve control of the device when I put in the deviceID though, so I know it's the right ID.

**Environment details:**
 - HASSIO in a docker container in Unraid.
 - Home Assistant version installed: core-2021.5.1 (OS version 5.10)
 - Component version installed: Newest, installed last night.
 - Last know working version: None for the ethernet
 - TV model: UN65RU7100FXZA

**Output of HA logs**
Paste the relevant output of the HA log here.

```
<img width="1388" alt="Screen Shot 2021-06-02 at 11 54 21 AM" src="https://user-images.githubusercontent.com/60558212/120512377-4b8ee280-c399-11eb-97fa-709261250999.png">

```

**Comment by ollo69** [comment]
I think that the problem is related to the SmartThings registration. Please provide HA log so that i can better identify the problem during setup.

**Comment by Nick-116** [comment]
```2021-05-31 22:01:00 ERROR (SyncWorker_9) [custom_components.samsungtv_smart] Web socket connection to SamsungTV 192.168.1.253 failed```
```2021-05-31 22:04:49 ERROR (SyncWorker_16) [custom_components.samsungtv_smart] Web socket connection to SamsungTV 192.168.1.253 failed```
These were all I was able to find, and also the ones in this picture.
https://imgur.com/a/hem4UY8
Thanks for the quick response!

**Comment by ollo69** [comment]
From this log I just can understand that HA is not able to connect to the TV at all. I don't know the topology of your network, but this cannot be considered an integration issue, there are no difference in the kind of connection used by the TV (with my TV I'm able to connect without issue using both Wired and Wireless connection). Only suggestion that  can give to you is to try to reset and power cycle your TV and try again. Also remember that Samsung TV do not allow connection using different subnet / VLAN, so if your LAN is in different VLAN than HA this could be the issue.

**Comment by Nick-116** [comment]
It is on the same subnet as my home-assistant instance and has an IP address. I don't use VLANs currently either. Is there somewhere else I can get better logs for this, so you can tell what the specific issue is?

**Comment by Nick-116** [comment]
I fixed it! I had to go to settings>network>expert settings> then turn off and back on IP control. It seems I have to do this every time I reconfigure the tv. 
Thanks for the help!
