### ISSUE TITLE
Add a way to poll the TV so it is more activly shows its state in Home Assistant

### ISSUE THREAD

**Issue by Nick-116** [ollo69/ha-samsungtv-smart#83]
**Is your feature request related to a problem? Please describe.**
I am always frustrated when I turn on my TV with the remote, and HA says it's off, even a minute or 2 after I turn it on. If there was a way to set a polling time to poll the TV, maybe every 30 seconds or something, that would be great.

**Describe the solution you'd like**
I want the tv entity in HA(Home Assistant) to turn on when I turn on the TV with the remote. It doesn't have to be quick but within 30 seconds would be nice.

**Describe alternatives you've considered**
Not using the remote. I would hate this alternative though..

**Comment by ollo69** [comment]
Polling is 20 secs, but problem is that detect status change take longer, Unfortunately there is no way to improve this, I try several method but this is the best that we can do.

**Comment by Nick-116** [comment]
What if you ping the IP? Is there any other way to tell if the TV is on or off than from the media player entity?

**Comment by ollo69** [comment]
Did you try to adjust the related configuration option? Integration delay some seconds (by default 30 if I well remember) to avoid fake ON detection due to TV activity like firmware check update. This value can be reduced in the option, but of course the risk is to have TV state ON when it is OFF.

**Comment by Nick-116** [comment]
Sorry i'm just getting back to this project now. No I cant seem to find that option anywhere. I have an IR sensor in front of my TV, so to be honest I dont even use that entity to turn on and off the TV. I have 2 issues now.

Issue 1: When I use that IR sensor to turn on the tv (seperate device), then tell the TV to go to Disney+, it takes 60+ seconds for the tv entity to update, so I cant set the TV to disney+ or hulu or whatever. Is there any way to set the tv as "always on"? I really just need the input control.

Issue 2: I have devices connected to all my HDMI ports on that TV. There doesnt seem to be a way to control them. Is it possible to add that functionality, or even just use a curl/post command outside this integration to set that input? You seem to know a lot about this API, and I cant make it work.

BTW Thanks again for all the hard work in this integration, it works better than any other one i've used.
