### ISSUE TITLE
Another unable to connect :(

### ISSUE THREAD

**Issue by sirs2k** [ollo69/ha-samsungtv-smart#9]
Hey guys, 

So I try to setup the integration (frontend). Put in my Smart Things key and all.
Next page asks which TV (I have 2 connected). 
The permission popups up on tv, I immediately select it

The integration says it couldn't connect.
Tried this on both TVs, 1 is RU7100 (65") the other is NU8000 (82")
Tried it with all permitted devices deleted from TV.
When I press allow on the tv, I can see the HA device has been allowed and the unique name that I put into this components setup is there.

The component shows "Unable to connect to this Samsung TV device."
I check the token file and there's nothing inside...
Is there a way to request token manually to see if that helps?

Nothing in HA logs

The TV is on the same subnet and it's not on a separate vlan
Using Unifi gear (if that helps)

The default samsung integration does work for me but as we all know it's very basic and I'd like HA to know when content is "playing" or "idle". That's the main thing for me

Thank you

**Comment by ollo69** [comment]
Problem doesn't seems be related to SmartThings but to local initial connection.
Did you try leaving SmatThings key blank?
Can you try to put this url: http://{host}:8001/api/v2/ (replacing {host} with your TV IP) in a browser and provide me the result (removing your mac-address from result)

**Comment by sirs2k** [comment]
Thanks for the prompt reply @ollo69 

Here you go

Please let me know if I should be censoring any other details 

```
{"device":{"FrameTVSupport":"false","GamePadSupport":"true","ImeSyncedSupport":"true","OS":"Tizen","TokenAuthSupport":"true","VoiceSupport":"true","countryCode":"AU","description":"Samsung DTV RCR","developerIP":"0.0.0.0","developerMode":"0","duid":"uuid:0b0fb24c-e019-4498-b8a7-18c0fdd91a86","firmwareVersion":"Unknown","id":"uuid:0b0fb24c-e019-4498-b8a7-18c0fdd91a86","ip":"192.168.1.118","model":"18_KANTM2_UHD","modelName":"UA82NU8000","name":"[TV] Cinema TV","networkType":"wired","resolution":"3840x2160","smartHubAgreement":"true","type":"Samsung SmartTV","udn":"uuid:0b0fb24c-e019-4498-b8a7-18c0fdd91a86","wifiMac":"xxxxxxx"},"id":"uuid:0b0fb24c-e019-4498-b8a7-18c0fdd91a86","isSupport":"{\"DMP_DRM_PLAYREADY\":\"false\",\"DMP_DRM_WIDEVINE\":\"false\",\"DMP_available\":\"true\",\"EDEN_available\":\"true\",\"FrameTVSupport\":\"false\",\"ImeSyncedSupport\":\"true\",\"TokenAuthSupport\":\"true\",\"remote_available\":\"true\",\"remote_fourDirections\":\"true\",\"remote_touchPad\":\"true\",\"remote_voiceControl\":\"true\"}\n","name":"[TV] Cinema TV","remote":"1.0","type":"Samsung SmartTV","uri":"http://192.168.1.118:8001/api/v2/","version":"2.0.25"}
```

Thanks

**Comment by ollo69** [comment]
Did you try without SmartThings key?

> I'd also like to ask, if I manage to get this integration working. Will HA be able to report when the TV is `playing` something or is `idle`?

what do you mean with `playing` something? You will be able to know if tv is turned on and wich app / source / channel is selected.

**Comment by sirs2k** [comment]
Thanks @ollo69 I tried without smartthings and it worked great straight away.

How do I go on about adding Plex as one of the sources?

What I meant was when content is being streamed from netflix or plex it would show as `playing` .

If you've ever tried the Plex or Kodi integration you'd know what I mean, It also gives you the content name that's being played etc...

Just the playing or idle states would be great!

**Comment by ollo69** [comment]
To have better experience you should connect to SmartThings.
Did you follow the guide for SmartThinks token generation? Is your TV logged in SmartThings?

**Comment by sirs2k** [comment]
Yeah I have already created a token... But as my OP mentions, it never worked.
It only worked when you suggested I try without token, I'm going to try to include the token in the configuration.yaml

What's weird is that both my TVs are signed into samsung account but only one is showing under https://graph-eu01-euwest1.api.smartthings.com/device/list (the NU8000)

**Comment by ollo69** [comment]
With multiple TV it is better to use config_flow for configuration so you will understand what is happening.
`configuration.yaml` is to be used only post configuration to add app_list. The main info are always stored in the registry

**Comment by ollo69** [comment]
I close this issue because I do not receave any feed-back from more that 1 months
