### ISSUE TITLE
Hard pinning generic Python dependency to specific version.

### ISSUE THREAD

**Issue by frenck** [ollo69/ha-samsungtv-smart#90]
**Describe the bug**

This integration hard pins a generic dependency to a specific version, which will break other integrations:

From the manifest:

```json
"websocket-client==1.0.1"
```

**Expected behavior**

Not to hard-pin generic Python dependencies.
This is bad practice and breaking setups for end-users.

**Screenshots**

 n/a

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Any
 - Home Assistant version installed: Irrelevant
 - Component version installed: v0.3.35
 - Last know working version: older.
 - TV model: Doesn't matter

**Output of HA logs**

Irelevant 

**Additional context**

Nope.

**Comment by ollo69** [comment]
Your observation is clear, but this library introduce a breaking change in version [v.0.58.0](https://github.com/websocket-client/websocket-client/releases/tag/v0.58.0), so previous version do not work properly with current code.
What do you think I should use in dependencies, something like `"websocket-client>=0.58.0"`?

**Comment by frenck** [comment]
ranges are a better choice, pinning a specific version is problematic.

**Comment by frenck** [comment]
Thanks!
