### ISSUE TITLE
Does this integration require the Samsung SmartThings Hub?

### ISSUE THREAD

**Issue by iDVB** [ollo69/ha-samsungtv-smart#91]
**Describe the bug**
Does this integration require the Samsung SmartThings Hub?
If yes, it might be a good idea to call this out in the docs. I'm not as familiar with SmartThings and so I don't know if there are some features they can do directly with the TV vs thru the hub.

To make things even more confusing Samsung has TWO areas of their site that can track Devices:

Samsung Account:
![image](https://user-images.githubusercontent.com/189506/126788508-9a1b6f32-66a2-4888-9599-3c4fbd491126.png)

SmartThings Account:
![image](https://user-images.githubusercontent.com/189506/126788372-296a2fdb-326f-443e-8886-1d673667100c.png)

**Comment by ollo69** [comment]
Don't know exactly what is SmartThings hub, but instruction on how configure this integration to use SmartThings is explained in the [here](https://github.com/ollo69/ha-samsungtv-smart/blob/master/docs/Smartthings.md).

**Comment by flintstones-fred** [comment]
@ollo69 I followed your instructions at the link you provided. However, I don't see any "Current States" listed. Does that mean my 2016 smart tv (which is listed) is not supported?
