### ISSUE TITLE
Volume control over Homekit not possible

### ISSUE THREAD

**Issue by tnagels** [ollo69/ha-samsungtv-smart#96]
According to the docs of the Homekit integration it should be possible so set the TV volume with the iOS Remote widget if HA supports volume control. It does not work for your integration; I suspect because the "supported_features" json is not configured correctly. Could you look into this?

**Comment by Bl4cksus** [comment]
+1 from me, this is already the best Samsung intigration for HA out there, and the only one that properly detects on/off status for me, every time. Just missing that volume control in HomeKit.

**Comment by ollo69** [comment]
I don't have `Homekit` so I need more detail about what should be done.
About [supported features](https://developers.home-assistant.io/docs/core/entity/media-player#supported-features), integration is configured with SUPPORT_VOLUME_MUTE, SUPPORT_VOLUME_SET and SUPPORT_VOLUME_STEP so I don't think that could be the issue.

**Comment by pavolholes** [comment]
I've just opened an Issue for Home Assistant Core `integration: homekit` with the same issue as is docummented here.

[HomeKit TV Remote Widget Volume Control Not Working](https://github.com/home-assistant/core/issues/63043)

@tnagels and @Bl4cksus can you please subscribe to that Issue and comment if the developers will need something what I don't undersand?

Thanks.

**Comment by ollo69** [comment]
I'll be happy to change what needed if in the open issue will result that something have to be fixed at this side👍

**Comment by vazome** [comment]
+1!
Would be nice to have volume options in HomeKit, Apple Home App.

**Comment by pavolholes** [comment]
Yesterday I’ve updated to the latest version 0.7.5 and today I just found the volume control for the TV appeared in the HomeKit and it’s working perfectly.
Thanks a lot!
![3253E8D0-BD61-49B5-9D44-D556EB7927D2](https://user-images.githubusercontent.com/35877348/186974553-6caf4701-9663-4986-bbfe-b014707fff22.jpeg)

**Comment by ollo69** [comment]
Really good to know, but I don't think that is related to last component version. More probably is due to some changes in HA or eventually in your TV software.
