### ISSUE TITLE
Arrow or cursor control

### ISSUE THREAD

**Issue by theastadler** [ollo69/ha-samsungtv-smart#98]
I have all the Apps listed and working, but to me is kind of useless. 

I might not know how to use it, but there is no way of selecting what I want to watch on Netflix, youtube, etc through the app. 

If you could add the arrows as there is on the remote and on Smartthing it would be perfect.

**Comment by raz0rf0x** [comment]
[Key Codes](https://github.com/ollo69/ha-samsungtv-smart/blob/master/docs/Key_codes.md)
````
service: media_player.play_media
data: {
  "entity_id": "media_player.living_room_tv",  
  "media_content_type": "send_key",
  "media_content_id": "KEY_DOWN",
}
````
