### ISSUE TITLE
Uncaught thread exception isAlive

### ISSUE THREAD

**Issue by gpongelli** [ollo69/ha-samsungtv-smart#99]
**Describe the bug**
Home Assistant log reports uncaught exception from this component.

**Expected behavior**
No exception should be raised. 

**Screenshots**
No screenshot applicable

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Raspberry, Docker Home assistant installation
 - Home Assistant version installed: 2021.9.1
 - Component version installed: 0.3.36
 - Last know working version: -
 - TV model:  -

**Output of HA logs**
Paste the relevant output of the HA log here.

```
Questo errore ha avuto origine da un'integrazione personalizzata. (traslation is: This error comes from a custom integration)

Logger: root
Source: custom_components/samsungtv_smart/api/samsungws.py:345 
Integration: SamsungTV Smart (documentation, issues) 
First occurred: 18:15:21 (1 occurrences) 
Last logged: 18:15:21

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/websocket/_app.py", line 305, in run_forever
    dispatcher.read(self.sock.sock, read, check)
  File "/usr/local/lib/python3.9/site-packages/websocket/_app.py", line 66, in read
    if not read_callback():
  File "/usr/local/lib/python3.9/site-packages/websocket/_app.py", line 269, in read
    return teardown()
  File "/usr/local/lib/python3.9/site-packages/websocket/_app.py", line 230, in teardown
    if thread and thread.isAlive():
AttributeError: 'Thread' object has no attribute 'isAlive'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/config/custom_components/samsungtv_smart/api/samsungws.py", line 345, in _client_remote_thread
    self._ws_remote.run_forever(
  File "/usr/local/lib/python3.9/site-packages/websocket/_app.py", line 311, in run_forever
    teardown()
  File "/usr/local/lib/python3.9/site-packages/websocket/_app.py", line 230, in teardown
    if thread and thread.isAlive():
AttributeError: 'Thread' object has no attribute 'isAlive'


```

**Additional context**
changing the call to is_alive() should fix this, or probably update websocket dependency to a version that does not use isAlive.

Thanks for your integration, it is the only one that runs correctly on Home Assistant and my Samsung QLED !

**Comment by ollo69** [comment]
Minimum requirement for [websocket-client](https://github.com/websocket-client/websocket-client) in `manifest.json` is 0.58.0 that already contain this fix. I think that you have an older version of the library due to some integration that probably force download of an older version (unfortunately this is very common). Check the version of `websocket-client` and upgrade to version >= 0.58.0 to fix this issue.

**Comment by gpongelli** [comment]
you got it!

some dependency that are locked to websocket-client < 0.58 comes directly from homeassistant/core:
- [ibm-watson==5.2.2](https://github.com/home-assistant/core/blob/4e1e7a4a718396ccbdaa37b17c6f6410d12528c8/requirements_all.txt#L841)
```
* ibm-watson==5.2.2
 - websocket-client [required: ==1.1.0, installed: 0.58.0]
```

- [mycroftapi==2.0](https://github.com/home-assistant/core/blob/4e1e7a4a718396ccbdaa37b17c6f6410d12528c8/requirements_all.txt#L1018)
```
* mycroftapi==2.0
 - websocket-client [required: ==0.44.0, installed: 0.58.0]
```

for me you can close this issue, thanks!

**Comment by ollo69** [comment]
Probably the HA core team should find a way to avoid this kind of conflict, whenever possible. Here we have 2 native integration totally incompatible with each other.
